### ISSUE TITLE
// and many others!

### ISSUE THREAD

**Issue by muescha** [SwifterSwift/SwifterSwift#104]
instead of `// and many others!` i would like to see a full doc of all functions and extensions

and mandatory for new pull requests

**Comment by omaralbeik** [comment]
@muescha There is no enough space to list all extensions examples in the README, but they are all listed with examples in the [Docs repo](https://github.com/SwifterSwift/SwifterSwiftDocs)

**Comment by muescha** [comment]
I See this Doc repo the First time.


 It should places In the readme. Before the examples. 

And of course alway a link at the line `// and many others`
