### ISSUE TITLE
Request a new version

### ISSUE THREAD

**Issue by robin202205** [SwifterSwift/SwifterSwift#1112]
I've experienced a compilation error in my project while using SwifterSwift, as there are naming conflicts with Color and Font in SwiftUI. I noticed that the master branch has already addressed this issue. Could you kindly release an updated version?

**Comment by powfulhong** [comment]
+1, the newest version in cocoapods is 5.2.0, but not 5.3.0

**Comment by guykogus** [comment]
It should now be available in 6.0.0.Can you confirm, @robin202205?

**Comment by robin202205** [comment]
It's ok on version 6.0.0.
