### ISSUE TITLE
NSTextField in AppKit encounters a bug with 'backgroundColor': Ambiguous use of 'backgroundColor'.

### ISSUE THREAD

**Issue by xtaykhksghy** [SwifterSwift/SwifterSwift#1120]
Xcode 14.3 or Xcode 15.0 beta
macOS 13.4

<img width="716" alt="SCR-20230703-jggh" src="https://github.com/SwifterSwift/SwifterSwift/assets/6407189/d0c0d6d6-7b7b-49a1-92cb-508e990afee2">
<img width="645" alt="SCR-20230703-jgqj" src="https://github.com/SwifterSwift/SwifterSwift/assets/6407189/cbd90b28-77eb-44a0-8f03-84c1b75b4791">

**Comment by Vithanco** [comment]
I have the same issue. NSTextField already has its own backgroundColor implementation, leading to problems using it.

**Comment by RomanPodymov** [comment]
Hello @Vithanco @xtaykhksghy 
For now you can fix this using `(t as NSView).backgroundColor = .purple`.
