### ISSUE TITLE
Cannot compile for visionOS app

### ISSUE THREAD

**Issue by Bill-Haku** [SwifterSwift/SwifterSwift#1123]
**Describe the bug**
Xcode cannot compile app used SwifterSwift for a visionOS app because of `'CLVisit' is unavailable in visionOS`

**Screenshots**
<img width="724" alt="image" src="https://github.com/SwifterSwift/SwifterSwift/assets/48173350/ffbc209e-6aca-4169-b728-dd1abe865206">

**Desktop:**
 - OS: macOS 13.4.1 (c)
 - Xcode: 15.0.0-Beta.4

**Target:**
 - Device: Apple Vision Pro Simulator
 - Version: visionOS 1.0 beta (21N5165f)

- [x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

**Comment by MarcoEidinger** [comment]
@LucianoPAlmeida  the compilation issue for `CLVisit` extension can be observed in early Xcode 15 betas but starting with Xcode 15 Beta 6, the conditional compilation directive`#if os(iOS)` will no longer return `true` running on Vision Pro. Hence, this particular issue is no longer valid.

However, the `SwifterSwift` project shows other compilation errors when compiling with VisionOS SDK. I'll create a PR.

**Comment by LucianoPAlmeida** [comment]
@MarcoEidinger Great that is awesome!
