### ISSUE TITLE
update 5.3.0 in CocoaPods

### ISSUE THREAD

**Issue by WonderJeffy** [SwifterSwift/SwifterSwift#1126]
SwifterSwift had released 5.3.0 and not update in CocoaPods where only 5.2.0 can be found.
Same problems:
#1121 
#1112 

- [x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

**Comment by WonderJeffy** [comment]
@omaralbeik

**Comment by guykogus** [comment]
We couldn't release 5.3.0 as it had a compilation error with the latest Xcode, so we released 6.0.0 instead.
