### ISSUE TITLE
UIView Extension `addGradient(colors: locations: direction:)`

### ISSUE THREAD

**Issue by Andy0570** [SwifterSwift/SwifterSwift#1151]
**Describe the bug**
Unable to pass `direction` parameter when adding a gradient to a view via extension method `addGradient(colors: locations: direction:)`

**To Reproduce**
In Xcode project, add gradient to `UIView` instance:
```swift
let colors = [UIColor(hexString: "#ffede7").require(), UIColor(hexString: "fffae5").require()]
addGradient(colors: colors, direction: GradientDirection.rightToLeft)
```
Xcode show Error:
```text
'rightToLeft' is inaccessible due to 'internal' protection level
```

**Expected behavior**

**Screenshots**
![Screenshots](https://blog-andy0570-1256077835.cos.ap-shanghai.myqcloud.com/uPic/%E6%88%AA%E5%B1%8F2023-10-20%2015.05.02.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 
 - Version: 13.5.2

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS17.0.3

**Additional context**
SwifterSwift 6.0.0
Xcode 15.0

**Suggestions**

Access control needs to be added to `GradientDirection` Struct in UIView extension, such as:

```Swift
/// SwifterSwift: Add gradient directions
struct GradientDirection {
    public static let topToBottom = GradientDirection(startPoint: CGPoint(x: 0.5, y: 0.0),
                                               endPoint: CGPoint(x: 0.5, y: 1.0))
    public static let bottomToTop = GradientDirection(startPoint: CGPoint(x: 0.5, y: 1.0),
                                               endPoint: CGPoint(x: 0.5, y: 0.0))
    public static let leftToRight = GradientDirection(startPoint: CGPoint(x: 0.0, y: 0.5),
                                               endPoint: CGPoint(x: 1.0, y: 0.5))
    public static let rightToLeft = GradientDirection(startPoint: CGPoint(x: 1.0, y: 0.5),
                                               endPoint: CGPoint(x: 0.0, y: 0.5))

    let startPoint: CGPoint
    let endPoint: CGPoint

    public init(startPoint: CGPoint, endPoint: CGPoint) {
        self.startPoint = startPoint
        self.endPoint = endPoint
    }
}
```

**Reference**

* <https://stackoverflow.com/questions/54673224/public-struct-in-framework-init-is-inaccessible-due-to-internal-protection-lev>
* <https://forums.swift.org/t/public-struct-init-is-unexpectedly-internal/5028>

**Comment by lauren-g-miller** [comment]
Hello,
Is any help needed on this bug. I read through and I am interested in working on it.
Thanks!

**Comment by guykogus** [comment]
@lauren-g-miller sorry I'd already fixed it, although it would've been a good one to offer as a first issue. Have a look at the other ones, maybe for example providing support for `visionOS`?
