### ISSUE TITLE
Cannot build `FutureExtensionsTests` in Xcode 15.1

### ISSUE THREAD

**Issue by RomanPodymov** [SwifterSwift/SwifterSwift#1156]
🚀
**Describe the bug**
Hello.
Thank you for SwifterSwift.
Found out that I cannot build `FutureExtensionsTests` (I added this class to the project).

**To Reproduce**
1. Open **SwifterSwift.xcworkspace** in Xcode 15.1.
2. Select **SwifterSwift-macOS** target.
3. Run **Product** -> **Test**.
4. Getting **'self' is not a member type of protocol 'Swift.Error'** in `testInitAsyncThrows`.

**Expected behavior**
Tests are running.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 14.1.2

- [x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

**Comment by RomanPodymov** [comment]
Looks like the issues is cased by SwiftFormat, it replaces `(any Error).self` to `any Error.self`.

**Comment by guykogus** [comment]
@LucianoPAlmeida can you reproduce this issue? I can't.

**Comment by LucianoPAlmeida** [comment]
> Looks like the issue is cased by SwiftFormat, it replaces `(any Error).self` to `any Error.self`.

Since is a swift format issue, let's close this
