### ISSUE TITLE
Add `removeBlur()` in UIImageViewExtensions

### ISSUE THREAD

**Issue by regi93** [SwifterSwift/SwifterSwift#1158]
**Is your feature request related to a problem? Please describe.**

Hello, thankfully I regularly use SwifterSwift.
I have used the blurred function from UIImageViewExtensions. However, I wanted to revert the image view to its original state without blur, but there was no such function available. 

**Describe the solution you'd like**
Therefore, I would like to contribute by adding the removeBlur function.

**Describe alternatives you've considered**

**Additional context**
```swift    
/// SwifterSwift: Removes the applied blur effect from the image view.
func removeBlur(){
        let blurredEffectViews = self.subviews.filter { $0 is UIVisualEffectView }
        blurredEffectViews.forEach { $0.removeFromSuperview() }
}
```

- [X] I've read, understood, and done my best to follow the [Contributing guidelines]

**Comment by guykogus** [comment]
Done in #1159
