### ISSUE TITLE
func XCTAssertEqualAsync

### ISSUE THREAD

**Issue by RomanPodymov** [SwifterSwift/SwifterSwift#1166]
🚀
**Is your feature request related to a problem? Please describe.**
Hello.
Thank you for SwifterSwift.
Found out that this code does not work
```
XCTAssertEqual(await asyncFunction(), await otherAsyncFunction())
```
Probably we need something like `XCTAssertEqualAsync`.

**Describe the solution you'd like**
```
func XCTAssertEqualAsync<T: Equatable>(
    _ expression1: @autoclosure () async -> T,
    _ expression2: @autoclosure () async -> T
) async {
    let expression1Value = await expression1()
    let expression2Value = await expression2()
    XCTAssertEqual(expression1Value, expression2Value)
}
```

**Describe alternatives you've considered**
No alternatives, but you can propose something.

**Additional context**
Nothing.

- [x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

**Comment by guykogus** [comment]
@RomanPodymov if you want to already call `await` then modern `XCTest` allows you to do that.
```swift
final class XCTestTests: XCTestCase {
    func testAsyncTests() async {
        let getValue: () async -> Int = { 1 }
        let a = await getValue()
        let b = await getValue()
        XCTAssertEqual(a, b)
    }
}
```

However if you wanted to create the function it could work like this
```swift
public extension XCTestCase {
    func XCTAssertEqualAsync<T: Equatable>(
        _ expression1: @escaping () async -> T,
        _ expression2: @escaping () async -> T
    ) {
        let expectation = expectation(description: "XCTAssertEqualAsync")
        Task {
            let expression1Value = await expression1()
            let expression2Value = await expression2()
            XCTAssertEqual(expression1Value, expression2Value)
            expectation.fulfill()
        }
        wait(for: [expectation])
    }
}
```
and then you can just test it like this:
```swift
func testXCTAssertEqualAsync() async {
    let getValue: () async -> Int = { 1 }
    XCTAssertEqualAsync(getValue, getValue)
}
```

**Comment by RomanPodymov** [comment]
Hello @guykogus 
Many thanks. But how can we share this function as a part of SwifterSwift?

**Comment by guykogus** [comment]
@RomanPodymov we'd need to create a separate package for test extensions in the Sources folder, because we can't add it to the core package or it will fail to build for anyone using SPM. Do you want me to set it up? Is it really necessary? Why not just use what is already available, as I suggested?
