### ISSUE TITLE
Add Privacy Manifest

### ISSUE THREAD

**Issue by mvn-toantruong-dn** [SwifterSwift/SwifterSwift#1171]
Hello,
I am an employee of Monstarlab company. I have a question about the Privacy Manifest.

At WWDC23 Apple is requiring all api calls that fall under this ruleset https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278394
be added to a privacy manifest file.
Does SwifterSwift need to include this manifest?
Please let me know about your upcoming plans to apply the privacy manifest.

Thank you!!!

**Comment by myouzh** [comment]
Hello，
I find that “Userdefaults API” is used, please add  a privacy manifest file.
Thank you!!!
