### ISSUE TITLE
appendingQueryParameters incomplete

### ISSUE THREAD

**Issue by tospery** [SwifterSwift/SwifterSwift#1192]
let url = URL(string: "https://google.com?q=abc")!
let param = ["q": "Swifter Swift"]
url.appendingQueryParameters(params) -> "https://google.com?q=abc&q=Swifter%20Swift"
will have two q parameter, should fix:
func appendingQueryParameters(_ parameters: [String: String]) -> URL {
         var urlComponents = URLComponents(url: self, resolvingAgainstBaseURL: true)!
        var queryItems = urlComponents.queryItems ?? []
        for param in parameters {
            if let index = queryItems.firstIndex(where: { $0.name == param.key }) {
                queryItems[index] = URLQueryItem(name: param.key, value: param.value)
            } else {
                queryItems.append(URLQueryItem(name: param.key, value: param.value))
            }
        }
        urlComponents.queryItems = queryItems
         return urlComponents.url!
}

**Comment by guykogus** [comment]
@tospery there's nothing wrong with a query having the same parameter name multiple times. Some libraries use this to create arrays of values. If you want an option to replace duplicates you will need to add another solution (as suggested in your PR).
