### ISSUE TITLE
'CAGradientLayerType' is only available in macOS 10.14 or newer - XCode 16 beta

### ISSUE THREAD

**Issue by Vithanco** [SwifterSwift/SwifterSwift#1203]
:rocket:

**Describe the bug**
SwifterSwift cannot compile

**To Reproduce**
Use Xcode 16 beta and compile the package

**Expected behavior**
SwifterSwift compiles without errors

**Screenshots**
<img width="950" alt="image" src="https://github.com/user-attachments/assets/a147f4ae-5b11-40c4-85e3-e6770b7cd8fc">

**Desktop (please complete the following information):**
 - OS:  macOS 14.6 (23G80)

**Additional context**

- [x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

**Comment by guykogus** [comment]
Fixed in #1197

**Comment by so-creations** [comment]
Hello,

Any indication on when this will be released please ?

**Comment by guykogus** [comment]
@so-creations we were waiting for macOS 15 and Xcode 16 to be available. I'll prepare a release soon.

**Comment by guykogus** [comment]
@so-creations releasing version 7.0.0 now.

**Comment by so-creations** [comment]
Thanks a lot @guykogus! Keep up the good work ;)
