### ISSUE TITLE
UIImage-Handling the problem of blurry network images

### ISSUE THREAD

**Issue by wangyuchaogeek** [SwifterSwift/SwifterSwift#1214]
**Describe the bug**

When using network images, there is no need to specify the resolution, because the code will get the default screen resolution

**To Reproduce**
        let format = UIGraphicsImageRendererFormat()
        // format.scale = self.scale <------- delete this line

**Expected behavior**
The original code will cause the transformed image to be blurry,
self.scale is always 1, when UIImageView.image will be setted

**Comment by guykogus** [comment]
@wangyuchaogeek can you please provide some kind of example. I'm not sure how reusing the image scale breaks the transformation.
