### ISSUE TITLE
'CATransform3D' is unavailable in watchOS

### ISSUE THREAD

**Issue by anddygon** [SwifterSwift/SwifterSwift#1216]
**Describe the bug**
When I was using Xcode 15.3, everything was fine. Today, after upgrading to Xcode 16, this error occurred. I’m using version 6.2.0.

**Screenshots**
![image](https://github.com/user-attachments/assets/d503e31a-e80e-4c24-8b50-c3cc1cb925cc)

**Desktop (please complete the following information):**
 - OS: iOS

**Smartphone (please complete the following information):**
 - Device:  iPhone11
 - OS: MacOS 17.5.1
 
 I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

**Comment by guykogus** [comment]
Fixed in #1202
