### ISSUE TITLE
Problem with SPM

### ISSUE THREAD

**Issue by gperdomor** [SwifterSwift/SwifterSwift#128]
Hi, i can't install with SPM...

using `.Package(url: "https://github.com/SwifterSwift/SwifterSwift.git", versions: Version(1,4,0)..<Version(2, .max, .max))` i got this error:

```
Cloning https://github.com/SwifterSwift/SwifterSwift.git
error: The dependency graph could not be satisfied. The package (https://github.com/SwifterSwift/SwifterS
wift.git) with version tag in range (1.4.0..<2.9223372036854775807.9223372036854775807) is not found. Fou
nd tags ([1.0.2])
```

and with `.Package(url: "https://github.com/SwifterSwift/SwifterSwift.git", majorVersion: 1, minor: 6)` i got something similar

**Comment by omaralbeik** [comment]
Problem was because the Swift Package manager doesn't recognize tags with the prefix "v"
I Re-released version 1.6.2 without the "v"

This should have fixed the problem
