### ISSUE TITLE
Int.randomBetween(min:max) is changed to Int.random(between:max)

### ISSUE THREAD

**Issue by bennokress** [SwifterSwift/SwifterSwift#130]
In the latest version Xcode is complaining about Int not having a static function called randomBetween. After looking at the source code I found that it is changed from `Int.randomBetween(min: 5, max: 25)` to `Int.random(between: 5, max: 25)`. This change is not yet documented in [your documentation](https://github.com/SwifterSwift/SwifterSwiftDocs/blob/master/Docs/IntExtensions.md#randombetweenmin-int-max-int).

I would also like to suggest tweaking the syntax to the following for nicer readability:
```swift
public static func random(between min: Int, and max: Int) -> Int {
	return random(inRange: min...max)
}
```

This would result in usage as `Int.random(between: 5, and: 25)`

**Comment by omaralbeik** [comment]
@bennokress I totally agree with you, using and makes more sense, will update it in the next release
about the documentation, we're working on updating the docs as some are outdated, feel free to contribute :)
