### ISSUE TITLE
Naming of Dequeue Functions in `UITableView` and `UICollectionView`

### ISSUE THREAD

**Issue by ShivaHuang** [SwifterSwift/SwifterSwift#136]
I found the functions in `UITableView` and `UICollectionView` extensions for dequeue cell have the prefix `deque` like the following:

`public func dequeReusableCell<T: UITableViewCell>(withClass name: T.Type, for indexPath: IndexPath) -> T`

, not **`dequeue`**. Is this a typo or for some reason?

**Comment by SD10** [comment]
@ShivaHuang Yes, thank you for pointing this out! I always misspell queue and dequeue. Feel free to submit a pull request or I can take care of it myself.

**Comment by ShivaHuang** [comment]
@SD10 I just submitted a pull request https://github.com/SwifterSwift/SwifterSwift/pull/137, please review it.

**Comment by omaralbeik** [comment]
Thank you @ShivaHuang and @SD10
