### ISSUE TITLE
M_PI has yellow issues 

### ISSUE THREAD

**Issue by g001613001** [SwifterSwift/SwifterSwift#147]
M_PI have to changed to Double.pi

**Comment by omaralbeik** [comment]
@g001613001 Could you please specify where M_PI is used?

**Comment by g001613001** [comment]
XCode 8.3 will show all the yellow issues.
Like this
[img](http://imgur.com/3VV7pIu)

**Comment by omaralbeik** [comment]
@g001613001 Please run `pod update` if you are using cocoapods or download the current version of the library
M_PI has been removed long time ago.

**Comment by g001613001** [comment]
OK, I'm try , thank you!

**Comment by omaralbeik** [comment]
Anytime @g001613001, let me know if you still face the same problem after updating.
