### ISSUE TITLE
Array: item(at: ) error if index is same as items

### ISSUE THREAD

**Issue by wousser** [SwifterSwift/SwifterSwift#148]
[1, 2, 3, 4, 5].item(at: 2) -> 3
 [1.2, 2.3, 4.5, 3.4, 4.5].item(at: 3) -> 3.4
 ["h", "e", "l", "l", "o"].item(at: 10) -> nil

//bug
["h"].item(at: 1) -> error, should be nil
["h", "e"].item(at: 2) -> error, should be nil

xcode: 8.3
swift: 3.1
swifterswift: 1.6.3

**Comment by SD10** [comment]
Thanks @wousser. I've fixed it. 👍
