### ISSUE TITLE
Swift Source Compatibility

### ISSUE THREAD

**Issue by pawurb** [SwifterSwift/SwifterSwift#168]
Hello @omaralbeik . I have been away for a while but could not find time for contributing recently. Just found out that Apple is including OS projects into its Swift source compatibility testing. Maybe you would be interested in joining it? Unfortunately in the nearest future I will not have time to look into it.

https://swift.org/source-compatibility/

**Comment by omaralbeik** [comment]
Great idea @pawurb, will work on adding it as soon as we can
Thank you!

**Comment by omaralbeik** [comment]
Pull request submitted
https://github.com/apple/swift-source-compat-suite/pull/32

**Comment by omaralbeik** [comment]
SwifterSwift was added today
https://swift.org/source-compatibility/#current-list-of-projects
Thanks @pawurb for letting me know
