### ISSUE TITLE
Array withoutDuplicates

### ISSUE THREAD

**Issue by Ccmi** [SwifterSwift/SwifterSwift#172]
![image](https://cloud.githubusercontent.com/assets/17047142/26041393/0e5a8892-395f-11e7-8d9f-907ea4f782e6.png)

**Comment by SD10** [comment]
Hey @Ccmi,

I believe that `withoutDuplicates` has been renamed to:
`duplicatesRemoved()` - the non-mutating version
`removeDuplicates()` - the mutating version

Let me know if this helps you!

**Comment by Ccmi** [comment]
Thanks
