### ISSUE TITLE
Drop method is missing

### ISSUE THREAD

**Issue by dviet** [SwifterSwift/SwifterSwift#173]
The following method is missing:

> drop(while condition: (Element) -> Bool)
> 
> Drop elements of Array while condition is true.
> 
> type: Mutating Method.
> parameters:
> condition: condition to evaluate each element against.
> availability: iOS 8+ tvOS 9+ watchOS 3+ macOS 10.10+.

Please update, thank you.

**Comment by LucianoPAlmeida** [comment]
@dviet Hi, this method was removed on [PR#165](https://github.com/SwifterSwift/SwifterSwift/pull/165) because that already exists in the Swift Standard Library.
