### ISSUE TITLE
Swift 4 Support

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#177]
## Swift 4
Xcode 9 beta with Swift 4 was announced yesterday 🎉, [whats new](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/WhatsNewXcode/xcode_9/xcode_9.html)
All Swift 4 work will be done in the [`swift-4`](https://github.com/SwifterSwift/SwifterSwift/tree/swift-4) branch and will be released as soon as Swift 4 is available officially

**Comment by gabriellanata** [comment]
Will this be released soon? Thanks!

**Comment by omaralbeik** [comment]
@gabriellanata We're working or releasing `v.4.0.0` within the next 7 days 😃

**Comment by RamblinWreck77** [comment]
Hello! Any update? Hope it's going well!

**Comment by omaralbeik** [comment]
@RamblinWreck77 everything is going well, I was busy with other projects 😅 
will release `v4` today hopefully

**Comment by omaralbeik** [comment]
![screen shot 2017-09-27 at 14 59 48](https://user-images.githubusercontent.com/8127757/30912249-8c3a6c24-a394-11e7-85b1-314f02255288.jpg)
