### ISSUE TITLE
Poll: Change SwifterSwift Versioning

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#178]
Change versioning to match Swift versioning.
example: next major release will be **SwifterSwift 4.0**.

**Comment by SD10** [comment]
@omaralbeik I think this is a good idea, then from here on out we should follow [semantic versioning](http://semver.org). 

We could possibly add a `CHANGELOG.md` file and then when users add new extensions or make changes they have to update the changelog.

This would give us a more accurate description of what's new in each version of SwifterSwift and then we don't have to sort through all the past commits doing a new version write up.

We would have 3 sections in the CHANGELOG:
`API Breaking Changes`
`Enhancements`
`Bugfixes`

e.g) 
- changing an extension name or signature == `API Breaking`
- added a new extension == `Enhancement`
- `Bugfixes` are self explanatory

**Comment by omaralbeik** [comment]
Community voted to change versioning, next version will be 3.0 👍
