### ISSUE TITLE
Tests are failing at non-english machine / Bug in String.double

### ISSUE THREAD

**Issue by flashspys** [SwifterSwift/SwifterSwift#187]
I forked and run SwifterSwift on my machine with a german region setting and I noticed that the tests are failing. To be exact the `testDouble()` crashes (not fails). With german region setting the number formatter created in String.double is watching for german doubles (`8,23` instead of `8.23`) and is returning nil here. 
I think all the number formatters used should be using an english locale.

**Comment by SD10** [comment]
@flashspys Thank you for reporting this. I'll look into it tonight.

**Comment by SD10** [comment]
@flashspys I'm not sure if I want to make the `NumberFormatter` have a specific locale. This would be an API breaking change. I didn't know some languages use commas over periods in number formatting. I think it should format to the current locale. What do you think?

My suggestion is updating the Unit Tests to use a String that is formatted to the current locale.

**Comment by omaralbeik** [comment]
Fixed in v3.1.0
