### ISSUE TITLE
Poll: 'SwifterSwift/withoutDate' subspec

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#200]
Some users prefer to use other libraries for Date extensions

How about a new subspec that lets them have all the great extensions without Date ones by adding the following line to `Podfile`
```ruby
pod 'SwifterSwift/withoutDate'
```

**Comment by SD10** [comment]
I think adding something like this is a slippery slope. The `withoutDate` subspec is also vague and confusing. I think a better approach would be to recommend users to control what they import type by type. This results in the same solution without the need for subspecs. I'll add writing documentation on how to do this to my todo list.

**Comment by Alex293** [comment]
Why don't just separate date extension and get them with SwifterSwift/Date ?

**Comment by omaralbeik** [comment]
@Alex293 The problem is some users are using the entire library without DateExtensions, maybe they have a UI framework (like a calendar) that has Date extensions which conflicts with SwifterSwift, we are looking for a way to prevent this, possible solutions:

1. `pod 'SwifterSwift/withoutDate'`
2. I'm working with @SD10 on another solution in #201
