### ISSUE TITLE
Add Import Extensions Documentation

### ISSUE THREAD

**Issue by SD10** [SwifterSwift/SwifterSwift#201]
### Add Documentation For Importing Extensions

SwifterSwift is a large framework and sometimes our extensions conflict with extensions provided in other libraries. 

Example: SwifterSwift provides many `Date` extensions that may conflict with a library that provides a calendar UI element or other date tools.

### How can we resolve conflicts?

By importing SwifterSwift components at the type level instead of the entire framework:

```swift
import SwifterSwift // imports all SwifterSwift extensions and prone to conflict
import struct SwifterSwift.Date // only imports SwifterSwift Date extensions
```

**Comment by omaralbeik** [comment]
@SD10 The above solution didn't work for me, I'm still getting **Ambiguous use of 'hour'** error although I imported just UIColor from SwifterSwift

```swift

import UIKit
import DateToolsSwift
import class SwifterSwift.UIColor

class ViewController: UIViewController {
	
	override func viewDidLoad() {
		super.viewDidLoad()
		
		let date: DateToolsSwift.Date = Date()
		let hour = date.hour
	}
	
}

```

**Comment by SD10** [comment]
@omaralbeik Thanks for testing this! 
I have some ideas as to what's happening and will look into it further.

**Comment by omaralbeik** [comment]
Looks like adding `module_name = "SwifterSwift"` in **SwifterSwift.podspecs** will help with this
