### ISSUE TITLE
Rename String.lastCharacter to String.lastCharacterAsString

### ISSUE THREAD

**Issue by SD10** [SwifterSwift/SwifterSwift#206]
### Starter Task For New Contributors

`String.lastCharacter` returns a **String**, should be renamed to `String.lastCharacterAsString`

```Swift
	/// SwifterSwift: Last character of string (if applicable).
	public var lastCharacter: String? {
		guard let last = characters.last else {
			return nil
		}
		return String(last)
	}
```

**Comment by omaralbeik** [comment]
Already done in v3.1.0 with many other enhancements, will submit a PR pater tomorrow

**Comment by SD10** [comment]
Dang! We should use these for starter tasks 😭

**Comment by omaralbeik** [comment]
@SD10 Don't worry I'll add some very soon!
