### ISSUE TITLE
Fix UISlider test by using XCTExpectation

### ISSUE THREAD

**Issue by SD10** [SwifterSwift/SwifterSwift#209]
### Fix race condition in async test

The test below relies on `XCTAssert` + a completion flag. This causes it to fail in rare cases. It needs to be refactored to use `XCTExpectations`. We use these elsewhere in the project so you can probably find a few examples. If you have any questions let me know 😃
 
```Swift
   func testSetValue() {
        let slider = UISlider()
        slider.minimumValue = 0
        slider.maximumValue = 100
        var completionCalled = false
        
        slider.setValue(99) {
            completionCalled = true
            XCTAssert(completionCalled)
        }
        XCTAssertFalse(completionCalled)
        XCTAssertEqual(slider.value, 99)
        
    }
```

**Comment by omaralbeik** [comment]
@LucianoPAlmeida Could you please take care of this issue when you have some free time :)

**Comment by LucianoPAlmeida** [comment]
@omaralbeik Sure :)
