### ISSUE TITLE
CoreImage not available on watchOS

### ISSUE THREAD

**Issue by tache** [SwifterSwift/SwifterSwift#214]
[x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

In the latest commit, I added `CoreImage` accessor extension, but in testing it further, I discovered that it does not have watchOS support. https://developer.apple.com/documentation/coreimage

In order to resolve this issue, there are two options ... please let me know and I will correct the issue.

Should I remove it? 
or 
Should I wrap it?

```
    #if os(iOS) || os(tvOS)
        /// SwifterSwift: CoreImage.CIColor (read-only). Only available on iOS and tvOS
         public var coreImageColor: CoreImage.CIColor? {
             return CoreImage.CIColor(color: self)  // The resulting Core Image color, or nil
        }
    #endif
```

**Comment by omaralbeik** [comment]
@tache I'd suggest you wrap it 👍

**Comment by omaralbeik** [comment]
@tache Could you pleas submit a PR with the functions wrapped only for not watchOS :)
