### ISSUE TITLE
Bring support for more Number types

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#224]
## Bring support for more Number types like UInt, Int8, Int16, ...

This will introduce new files like **SignedNumberExtensions.swift** and **IntegerExtensions.swift**, however this will also:
- Refactor many duplicated extensions between FloatingPoint and Integer types into single extensions.
- Bring support for other Number types.
- All extensions should behave same as before. **No API breaking changes!**

 
_Example:_

###### Before
```swift
public extension FloatingPoint {
    public var abs: Int {
        return Swift.abs(self)
    }
}

public extension Int {
    public var abs: Int {
        return Swift.abs(self)
    }

    public var isEven: Bool {
        return (self % 2) == 0
    }
}
```
###### After
```swift
public extension SignedNumber {
    public var abs: Self {
        return Swift.abs(self)
    }
}

public extension Integer {
    public var isEven: Bool {
        return (self % 2) == 0
    }
}
```

**Comment by SD10** [comment]
I already have some of this code on an old SwifterSwift branch. I'll see if I can rebase the changes and push them up this week.

**Comment by SD10** [comment]
I just tried taking a crack at it and there are a lot less refactoring opportunities than I thought. I'll still see what I can do but this is still a good starter task as some are already listed in this example.

**Comment by kennic** [comment]
Compile error on XCode 9.0 Beta 5:

`SignedNumberExtensions.swift:12:8: Non-nominal type 'SignedNumber' (aka 'Comparable & SignedNumeric') cannot be extended`

`SignedNumberExtensions.swift:15:18: Global function cannot return 'Self'`

**Comment by omaralbeik** [comment]
@kennic SwifterSwift 3 is not compatible with Xcode9/Swift4.
We're working on v4 in the [`swift-4`](https://github.com/SwifterSwift/SwifterSwift/tree/swift-4) branch, which will bring support for Xcode9 and Swift 4.

> v4 in still in development and not production ready yet
```
pod 'SwifterSwift', :git => 'https://github.com/SwifterSwift/SwifterSwift.git', :branch => 'swift-4'
```

**Comment by Bruce-pac** [comment]
Compile error on XCode 9.0 Beta 6:

SignedNumberExtensions.swift:12:8: Non-nominal type 'SignedNumber' (aka 'Comparable & SignedNumeric') cannot be extended

SignedNumberExtensions.swift:15:18: Global function cannot return 'Self'

I set Build Settings/Swift language Version to Swift 3.2,but still as above.

**Comment by omaralbeik** [comment]
@Bruce-pac as in my above comment, please use `v4` if you want to use with Xcode 9
