### ISSUE TITLE
"Linking against a dylib" warning message

### ISSUE THREAD

**Issue by timyply** [SwifterSwift/SwifterSwift#232]
<img width="509" alt="capture d ecran 2017-09-01 a 14 59 46" src="https://user-images.githubusercontent.com/31541067/29970870-a0cda750-8f26-11e7-89ef-3adfc69597ce.png">

I get the following warning message when I build my app.
After a few researches, it looks as if the warning will prevent my app from being approved to the App Store.

What am I supposed to do to fix this ?
I'm quite new to Xcode and Swift and I must admit that I don't really understand the answers I have found so far.

Thanks for your help

**Comment by omaralbeik** [comment]
@timyply, the [App Extension Programming Guide](https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html) suggest the following:

> To configure an app extension target to use an embedded framework, set the target’s “Require Only App-Extension-Safe API” build setting to Yes. If you don’t, Xcode reminds you to do so by displaying the warning “linking against dylib not safe for use in application extensions”.\

Please let us know if that fixes the issue you are facing, otherwise please help us understand the problem better by providing the following information
 
- SwifterSwift version
- Xcode version
- macOS version running Xcode:
- Platform(s) running SwifterSwift

**Comment by timyply** [comment]
<img width="694" alt="capture d ecran 2017-09-01 a 23 51 43" src="https://user-images.githubusercontent.com/31541067/29989009-b29fc4d2-8f70-11e7-8322-a1a2fb688ae4.png">
<img width="874" alt="capture d ecran 2017-09-01 a 23 52 14" src="https://user-images.githubusercontent.com/31541067/29989008-b29fde2c-8f70-11e7-9d33-ef027a5d0096.png">

I have read about this setting to set to Yes
But when I do so, I'm getting all these errors when I build

**Comment by omaralbeik** [comment]
@timyply We're still waiting for the following information to investigate the issue
- SwifterSwift version
- Xcode version
- macOS version running Xcode:
- Platform(s) running SwifterSwift

**Comment by omaralbeik** [comment]
@timyply We will close this issue for now, please feel free to re-open it again if you faced the same issue
