### ISSUE TITLE
Xcode 9 beta 6 Compile Error

### ISSUE THREAD

**Issue by pkuzia** [SwifterSwift/SwifterSwift#234]
Issue: When i try to compile project with SwifterSwift I get this error:

![zrzut ekranu 2017-09-04 o 16 34 18](https://user-images.githubusercontent.com/26796889/30030854-59310e30-918f-11e7-96f2-6f37d45cabe4.png)

Xcode 9 beta 6
SwifterSwift 3.1.1
macOS 10.12.6

Thanks for your help! 🙂

**Comment by omaralbeik** [comment]
@pkuzia SwifterSwift 3 is not compatible with Xcode9/Swift4.
We're working on v4 in the [`swift-4`](https://github.com/SwifterSwift/SwifterSwift/tree/swift-4) branch, which will bring support for Xcode9 and Swift 4.

> v4 in still in development and not production ready yet
```
pod 'SwifterSwift', :git => 'https://github.com/SwifterSwift/SwifterSwift.git', :branch => 'swift-4'
```
