### ISSUE TITLE
Rethink files structure and subspec

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#236]
# Files Structure
I think this structure will make the library more modular and help people add new categories of extensions in the future

## SwiftStdlib
> All Swift Standard Library extensions
- ArrayExtensions.swift
- BoolExtensions.swift
- CharacterExtensions.swift
- CollectionExtensions.swift
- DictionaryExtensions.swift
- DoubleExtensions.swift
- FloatExtensions.swift
- FloatingPointExtensions.swift
- IntExtensions.swift
- OptionalExtensions.swift
- SignedIntegerExtensions.swift
- SignedNumericExtensions.swift
- StringExtensions.swift

## Foundation
> All Foundation extensions
- DataExtensions.swift
- DateExtensions.swift
- LocaleExtensions.swift
- NSAttributedStringExtensions.swift
- URLExtensions.swift

## UIKit
> All UIKit extensions
- UIAlertControllerExtensions.swift
- UIBarButtonItemExtensions.swift
- UIButtonExtensions.swift
- UICollectionViewExtensions.swift
- UIColorExtensions.swift
- UIImageExtensions.swift
- UIImageExtensions.swift
- UIImageViewExtensions.swift
- UILabelExtensions.swift
- UINavigationBarExtensions.swift
- UINavigationControllerExtensions.swift
- UINavigationItemExtensions.swift
- UISearchBarExtensions.swift
- UISegmentedControlExtensions.swift
- UISliderExtensions.swift
- UIStoryboardExtensions.swift
- UISwitchExtensions.swift
- UITabBarExtensions.swift	Add tests
- UITableViewExtensions.swift
- UITextFieldExtensions.swift
- UITextViewExtensions.swift
- UIViewControllerExtensions.swift
- UIViewExtensions.swift

## AppKit
> All AppKit (macOS) extensions
> was Cocoa before
- NSColorExtensions.swift
- NSViewExtensions.swift

## CoreGraphics
> All CoreGraphics extensions
- CGColorExtensions.swift
- CGFloatExtensions.swift
- CGPointExtensions.swift
- CGSizeExtensions.swift

## CoreLocation
> All CoreLocation extensions
- CLLocationExtensions.swift

## Cocoapods Subspecs

these changes will be reflected to [SwifterSwift.podspec](https://github.com/SwifterSwift/SwifterSwift/blob/master/SwifterSwift.podspec) as well, adding new subspecs for new categories and renaming Cocoa to AppKit

**Comment by SD10** [comment]
What about **SwiftStdlib Extensions**?

### Swift Standard Library
- ArrayExtensions.swift
- BoolExtensions.swift
- CharacterExtensions.swift
- CollectionExtensions.swift
- DictionaryExtensions.swift
- DoubleExtensions.swift
- FloatExtensions.swift
- FloatingPointExtensions.swift
- IntExtensions.swift
- OptionalExtensions.swift
- SignedIntegerExtensions.swift
- SignedNumericExtensions.swift
- StringExtensions.swift

**Comment by LucianoPAlmeida** [comment]
@SD10 I like SwiftStdlib :)

**Comment by omaralbeik** [comment]
@SD10 @LucianoPAlmeida I updated the list above to have a SwiftStdlib section
