### ISSUE TITLE
UIViewController extension 'navigationBar' causes crash on iOS 11

### ISSUE THREAD

**Issue by drewpitchford** [SwifterSwift/SwifterSwift#243]
> Please fill out this template when filing an issue.
>
> All comment lines beginning with an **>** instruct you with what info we expect. You can delete those lines once you've filled in the info.
>

[x ] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
I have my own UIViewController extension file where I have a method for setting up the `prefersLargeTitles` for my various VCs. The following line causes a crash with error `Thread 1: EXC_BAD_INSTRUCTION (code=1, subcode=0x0)`:

`navigationBar?.prefersLargeTitles = true`

### What did you expect to happen?
I would expect it to access the navigationBar just like it would in iOS 10 without crashing.

### What happened instead?
A crash occurred (see above). Bad instruction was the error. Note: This only happens when running on an iOS 11 device.

### SwifterSwift Environment

- SwifterSwift version: SwifterSwift branch `swift-4`
- Xcode version: 9.0 beta 6 (9M214v)
- macOS version running Xcode: 10.12.6 (16G29)
- Swift version: 4.0
- Platform(s) running SwifterSwift: iOS

### Demo Project
[SwifterSwiftDemo.zip](https://github.com/SwifterSwift/SwifterSwift/files/1293253/SwifterSwiftDemo.zip)

**Comment by omaralbeik** [comment]
All what `navigationBar` is doing behind the scenes is referring to `self.navigationController?. navigationBar`.
The app crashes with or without the use of `SwifterSwift`.

I think it is crashing because there is parent navigation controller, but there is no navigation bar. In order to get this to work, the view controller should have an active navigation item.

@drewpitchford I updated your demo project to have a button in `ViewController` which push to `ViewController2` and there I'm setting `navigationBar?.prefersLargeTitles = true`

Please let me know if this helps :)

[SwifterSwiftDemo.zip](https://github.com/SwifterSwift/SwifterSwift/files/1293421/SwifterSwiftDemo.zip)

**Comment by drewpitchford** [comment]
Yes, it crashes if you use that because the extension is on UIViewController. So if you do `navigationController?.navigationBar`, it still accesses SwifterSwift's extension. Try the project without SwifterSwift installed and you see that it will not crash when accessing via `navigationController?.navigationBar`. @omaralbeik

**Comment by SD10** [comment]
@drewpitchford What SwifterSwift extension is causing this problem?

**Comment by drewpitchford** [comment]
@SD10 `navigationBar` on UIViewController Extensions.

**Comment by omaralbeik** [comment]
I'm sorry for the misunderstanding

@SD10 it looks like having a variable called `navigationBar` in **UIViewControllerExtensions.swift** causes the issue, I'm not sure if it is a bug in UIKit or Apple has some private variable with the same name, what do you guys think?
when the name is changed to anything else everything works 🤔 

@drewpitchford for now you can comment out or remove the extension while we investigate the issue more

**Comment by drewpitchford** [comment]
Yes, that’s what I did. I tried to fix it and wanted to submit a PR, but could not figure out the issue.

**Comment by SD10** [comment]
I downloaded the example project but I can't even see where this `prefersLargeTitles` extension is declared?

**Comment by drewpitchford** [comment]
It is part of UINavigationBar in iOS 11.

**Comment by SD10** [comment]
@drewpitchford Thanks for reporting this, this extension will be removed in `v3.2`. 

What was happening is we extend `UIViewControlelr` with a property called `navigationBar`. This property is then inherited by `UINavigationController` which already has a `navigationBar` property of its own. 

The SwifterSwift version of this property is favored over the `UINavigationController` version and they have different types. One returns optional and one returns non-optional. This is what causes the crash.
