### ISSUE TITLE
SignedNumber extension does not compile on Xcode9

### ISSUE THREAD

**Issue by sisoje** [SwifterSwift/SwifterSwift#244]
[ ] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
Compiled a project that worked in Xcode8

### What did you expect to happen?
Success

### What happened instead?
Compiler error

### SwifterSwift Environment

- SwifterSwift version: 3.1.1
- Xcode version: 9
- macOS version running Xcode:
- Swift version:
- Platform(s) running SwifterSwift: ios

### Demo Project
>Please link to or upload a project we can download that reproduces the issue.

**Comment by SD10** [comment]
@sisoje What version of SwifterSwift are you using?

**Comment by sisoje** [comment]
xcode uses swift 4 i guess

**Comment by omaralbeik** [comment]
@sisoje SwifterSwift 3 is not compatible with Xcode9/Swift4.
We're working on v4 in the [`swift-4`](https://github.com/SwifterSwift/SwifterSwift/tree/swift-4) branch, which will bring support for Xcode9 and Swift 4.

```
pod 'SwifterSwift', :git => 'https://github.com/SwifterSwift/SwifterSwift.git', :branch => 'swift-4'
```

Please let me know if you still face the same issue using v4

**Comment by sisoje** [comment]
hey swifter swift 3.1.0 works!

**Comment by omaralbeik** [comment]
@sisoje `v3` is not meant to be used with Swift4 or Xcode 9.
Please use `v4` as in the above message :)

**Comment by sisoje** [comment]
The point is that i only use /Foundation subspec, so in my case it's sufficient to use 3.1.0
I will wait for the final v4 release patiently, I am lazy to patch Podfiles, its easier to fix it in the podspec of my own pod, Thanks anyway
