### ISSUE TITLE
Non-nominal type 'SignedNumber' (aka 'Comparable & SignedNumeric') cannot be extended

### ISSUE THREAD

**Issue by mperovic** [SwifterSwift/SwifterSwift#245]
> Please fill out this template when filing an issue.
>
> All comment lines beginning with an **>** instruct you with what info we expect. You can delete those lines once you've filled in the info.
>

[x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
Try to compile app in Xcode 9 GM

### What did you expect to happen?
Compilation without error

### What happened instead?
Received error: Non-nominal type 'SignedNumber' (aka 'Comparable & SignedNumeric') cannot be extended

### SwifterSwift Environment

- SwifterSwift version: SwifterSwift (3.1.1)
- Xcode version: Version 9.0 (9A235)
- macOS version running Xcode: 10.13 Beta (17A362a) (GM candidate)
- Swift version: 3.2
- Platform(s) running SwifterSwift: iOS & tvOS

### Demo Project
-

**Comment by omaralbeik** [comment]
@mperovic as mentioned in #234 SwifterSwift 3 is not compatible with Xcode9/Swift4.
We're working on v4 in the [`swift-4`](https://github.com/SwifterSwift/SwifterSwift/tree/swift-4) branch, which will bring support for Xcode9 and Swift 4.

```
pod 'SwifterSwift', :git => 'https://github.com/SwifterSwift/SwifterSwift.git', :branch => 'swift-4'
```

Please let me know if you still face the same issue using v4

**Comment by mperovic** [comment]
I'm still on Swift 3.2, so this suggestion doesn't help :(

**Comment by omaralbeik** [comment]
@mperovic I see 🤔, as a temporary solution you can use `v3.0.0` while we investigate the issue more tomorrow :)
