### ISSUE TITLE
How to use the NSColor extensions in swift 3 

### ISSUE THREAD

**Issue by Kanhaiyakon** [SwifterSwift/SwifterSwift#247]
suppose I have a UI button and I wanted to give the colour of Facebook so how can I use the extension pls suggest me

**Comment by SD10** [comment]
@Kanhaiyakon We have an extension called `NSColor.facebook` which you can use to get the color for Facebook 😃

**Comment by Kanhaiyakon** [comment]
@SD10  I am a new learner of swift so please see my code and pls correct it. 


import UIKit

class ViewController: UIViewController {
  
    

    @IBOutlet weak var Button: UIButton!
    override func viewDidLoad() {
        super.viewDidLoad()
    Button.backgroundColor = NSColor.social.facebook
    }

}
#if os(macOS)
    import Cocoa
public extension NSColor {
    
    
    public struct social {
        // https://www.lockedowndesign.com/social-media-colors/
        
        /// red: 59, green: 89, blue: 152
        public static let facebook = NSColor(red: 59, green: 89, blue: 152)
    }

}
#endif

**Comment by SD10** [comment]
@Kanhaiyakon You're using `NSColor` which is available on `macOS`. You need to be using `UIColor` if you're working on iOS:

```Swift
import UIKit

class ViewController: UIViewController {
  
    

    @IBOutlet weak var Button: UIButton!
    override func viewDidLoad() {
        super.viewDidLoad()
    Button.backgroundColor = UIColor.social.facebook
    }

}

public extension UIColor {
    
    
    public struct social {
        // https://www.lockedowndesign.com/social-media-colors/
        
        /// red: 59, green: 89, blue: 152
        public static let facebook = UIColor(red: 59, green: 89, blue: 152)
    }

}
#endif
```

**Comment by Kanhaiyakon** [comment]
@SD10  thanks so much
