### ISSUE TITLE
Carthage Build Failed: SwifterSwift 3.2.0, Xcode 8.3.3, swift 3.2

### ISSUE THREAD

**Issue by sixty8** [SwifterSwift/SwifterSwift#249]
Build Failed
	Task failed with exit code 65:

This usually indicates that project itself failed to compile.

**Comment by SD10** [comment]
@sixty8 If you're using SwifterSwift 3.2 you need to be using Xcode 9

**Comment by omaralbeik** [comment]
@sixty8 Will close the issue for now, please let us know if you faced the same issue after using `v4` with Xcode9
