### ISSUE TITLE
Make Travis run SwiftLint and pod lint lint

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#256]
It would be very helpful to let Travis run both `swiftlint` and `pod lib lint` and report any problems!

**Comment by SD10** [comment]
We just need to add this to the Dangerfile. I added the SwiftLint danger plugin:
```Ruby
# Run SwiftLint
swiftlint.lint_files
```

**Comment by SD10** [comment]
This is closed by #264
