### ISSUE TITLE
Add unit tests for NSColor extensions

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#257]
Add tests for NSColor extensions as we have for UIColor

**Comment by SD10** [comment]
I'm pretty sure our unit tests can take the same approach as we use for the extensions? I have a project with a test target where I do tests on both `UIImage` and `NSImage`.

**Comment by omaralbeik** [comment]
@SD10 that makes sense, then we need to have a **Shared** folder for both `UIKit` and `AppKit` tests and rename `UIColor` to `Color`
