### ISSUE TITLE
Add isWithin method to Date extensions

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#258]
Right now we have a convenient way to check if date is within a current component using the `isInCurrent` method, but sometimes we want to check if date is within a component of another date.
Example: is date within February of year 2015?

A suggested way to do this:
```
func isWithin(_ value: Int, _ component: Calendar.Component, of date: Date) -> Bool {
   ...
}
```

**Comment by omaralbeik** [comment]
This will be helpful when using with a calendar framework like [JTAppleCalendar](https://github.com/patchthecode/JTAppleCalendar) to check if a date is within the currently displayed month

**Comment by vadimue** [comment]
I also have tried to implement this method, and have created method signature proposed @omaralbeik
```
public func isWithin(_ value: Int, _ component: Calendar.Component, of date: Date) -> Bool {
    var newDate = date
    switch component {
    case .second:
      newDate.second = value
    case .minute:
      newDate.minute = value
    case .hour:
      newDate.hour = value
    case .weekOfMonth:
       newDate.day = date.adding(.weekOfMonth, value: value).day
    case .month:
      newDate.month = value
    case .year:
      newDate.year = value
    default:
      break
    }
    return calendar.isDate(self, equalTo: newDate, toGranularity: component)
  }
```
The difference between @ayastrebov version in `value:  Int` parameter. But I think your version more proper.
