### ISSUE TITLE
Avoid triggering Travis build if only README is updated

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#266]
This should also apply to other **non-code** files, we don't want to bother Travis with stuff he does not know 😂

**Comment by gempir** [comment]
This is not possbile at the moment: https://github.com/travis-ci/travis-ci/issues/6301

**Comment by omaralbeik** [comment]
@gempir then it is not a starter-task anymore 😅, thank you for the update
