### ISSUE TITLE
Chained comparison operators (5 < 6 < 7)

### ISSUE THREAD

**Issue by sidmani** [SwifterSwift/SwifterSwift#274]
I wrote some code for chaining comparison operators, and would love to contribute it to SwifterSwift. Here's what it looks like:  
```
infix operator <: AdditionPrecedence
public extension Comparable {
    public static func <(accumulator: (Bool, Self), right: Self) -> (Bool, Self) {
        return (accumulator.0 && accumulator.1 < right, right)
    }

    public static func <(accumulator: (Bool, Self), right: Self) -> Bool {
        return accumulator.0 && accumulator.1 < right
    }

    public static func <(left: Self, right: Self) -> (Bool, Self) {
        return (left < right, right)
    }
/// ... repeat for other comparison operators
}
```  
This allows comparisons of an arbitrary number of Comparable objects, so `(a < b && a > c)` can be replaced with `(b > a > c)`. Any thoughts? I'll write a pull request if you like the idea.

**Comment by omaralbeik** [comment]
@sidmani I love it!
Please go ahead and open a pull request, and I will make sure to merge it as soon as possible

**Comment by sidmani** [comment]
@omaralbeik Having a couple issues with ambiguous operators that didn't show up in the playground I tested it in, but I'll let you know if it works.

**Comment by BenLeggiero** [comment]
Any progress on this? I'd love to see it!

**Comment by sidmani** [comment]
@BenLeggiero The code I posted only works in playgrounds for some reason, and fails in real projects because of overloading ambiguity. I have no idea why it succeeds in one setting but not the other- do you have any insight?

**Comment by BenLeggiero** [comment]
@sidmani I decided to try my hand at this, starting from scratch. Making the names long and descriptive helped alot! I got it working just fine in a framework
https://gist.github.com/BenLeggiero/5bbd4f0b9cf0fc55dc62be6296b266d1

**Comment by sidmani** [comment]
@BenLeggiero Did you try adding your code to SwifterSwift? It still doesn't work for me- the same compile error "Ambiguous operator declarations found for operator" shows up in the test target.

**Comment by sidmani** [comment]
I think the problem occurs when you import Foundation because that’s where the other operators are defined. That’s why SwifterSwift’s test target doesn’t compile.

**Comment by BenLeggiero** [comment]
@sidmani Yes, in my test project (a console app) I'm using Foundation and it works fine for me. Perhaps it's because I'm using Swift 4?

**Comment by sidmani** [comment]
@BenLeggiero I'm using swift 4 too. Can you try adding the code to SwifterSwift itself?

**Comment by omaralbeik** [comment]
I'm going to close this for now, please let me know if you were able to add it to SwifterSwift 👍
