### ISSUE TITLE
Not working in xcode 9

### ISSUE THREAD

**Issue by sahabe1** [SwifterSwift/SwifterSwift#277]
Not working in xcode 9

**Comment by omaralbeik** [comment]
@sahabe1 
We're already using SwifterSwift in Xcode 9, [installation guide](https://github.com/SwifterSwift/SwifterSwift#installation).
However if it didn't work for you, please specify more details to let us assist you:
- what exactly is not working?
- what version of SwifterSwift are you using?
- what method are you using to integrate SwifterSwift into your project?
- Attach an example if possible.

**Comment by sahabe1** [comment]
please see attachment

<img width="1184" alt="screen shot 2017-10-08 at 11 56 07 am" src="https://user-images.githubusercontent.com/1065015/31314497-e633e5be-ac1f-11e7-9261-be58d09286c6.png">
<img width="826" alt="screen shot 2017-10-08 at 11 56 33 am" src="https://user-images.githubusercontent.com/1065015/31314498-e644933c-ac1f-11e7-80cc-ef7d17b84dad.png">

**Comment by omaralbeik** [comment]
@sahabe1 It looks like you are still using `v3` please update to `v4`.
You can update your pods by typing
```
pod update
```

**Comment by agfa555** [comment]
I'm using Xcode Version 9.0 (9A235) with SwifterSwift version 4.0.1
Here's the list of errors Xcode throws:

<img width="367" alt="screenshot 2017-10-10 10 14 50" src="https://user-images.githubusercontent.com/584359/31367797-e9c48ab4-ada3-11e7-9773-bdaef39b525d.png">

**Comment by SD10** [comment]
@agfa555 What version of Swift are you using? You need `Swift 4` for `SwifterSwift 4.0`

**Comment by agfa555** [comment]
I had forgotten about that minor little detail. 👯‍♂️ 
All solved now.
Sorrrry...

**Comment by jeff77731** [comment]
Hi, @agfa555 

I have the same problem

How do you solve it?
