### ISSUE TITLE
CodeCov is not displaying coverage for Sources

### ISSUE THREAD

**Issue by SD10** [SwifterSwift/SwifterSwift#282]
CodeCov is no longer showing coverage for `SwifterSwift/Sources`. I think this could be due to the refactoring of the projects internal structure.

**Comment by omaralbeik** [comment]
@SD10 I think this issue started after adding macOS testing to Travis
All UIKit tests are not running as in [codecov report](https://codecov.io/gh/SwifterSwift/SwifterSwift/tree/master/Tests)

**Comment by SD10** [comment]
Thanks for fixing this 👍 @omaralbeik
