### ISSUE TITLE
SpriteKit and SceneKit extensions

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#303]
Think about extensions to help game developers using SpriteKit and SceneKit; examples:
- Bring `UIColor` extensions to `SKColor`
- Add methods to simplify animating `SKNode` objects
- and more ..

Unfortunately my experience with developing games is very limited, but I think adding such extensions to SwifterSwift would be a nice addition, especially that we're now using spspecs!

**Comment by BennX** [comment]
Actually:
```Swift
typealias SKColor = UIColor
```
