### ISSUE TITLE
Add CHANGELOG Guidelines

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#317]
I was reviewing the 29 commits we had after our last release and making sure CHANGELOG is up to date. I won't lie, it was not fun at all to check each commit and figure our changes 😅 

Here is an [amazing guideline](https://github.com/MessageKit/MessageKit/blob/master/CHANGELOG_GUIDELINES.md) from [MessageKit](https://github.com/MessageKit) maybe we can use it as a reference if @SD10 doesn't
 mind 😃 for future PRs?

**Comment by kaphacius** [comment]
maybe we should add it as a one of the checklist items when opening a PR, so users won't forget about it :)

**Comment by omaralbeik** [comment]
Closed by #353
