### ISSUE TITLE
Add replacingOccurrences extension to NSAttributedString

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#322]
Add `replacingOccurrences` method to `NSAttributedString` to replace occurrences of a string with another string, like `String` has:

```swift
replacingOccurrences(of: StringProtocol, with: StringProtocol)
```

**Comment by omaralbeik** [comment]
It would be even better to post an answer with the extension to this [Stackoverflow thread](https://stackoverflow.com/questions/47515536/replace-all-occurrences-of-a-character-in-an-substring-of-nsattributedstring) as well :)

**Comment by Najdan** [comment]
@omaralbeik Stackoverflow thread link points to non existing page (404).

**Comment by omaralbeik** [comment]
@Najdan, it looks like the question was removed 😞. anyway, it was a thread where someone asked the same question above :)

**Comment by SD10** [comment]
I think this extension should be on `NSMutableAttributedString` (if it isn't already) and not `NSAttributedString`.

**Comment by Najdan** [comment]
@SD10, you are correct `NSMutableAttributedString` already contains method [`replaceOccurrences(of:with:options:range:)`](https://developer.apple.com/documentation/foundation/nsmutablestring/1412453-replaceoccurrences ).

<img width="796" alt="replace occurrences test" src="https://user-images.githubusercontent.com/4264802/34547787-f7a60d72-f0fd-11e7-9934-0d88afab3e85.png">

**Comment by SD10** [comment]
Thanks @Najdan 👍

**Comment by omaralbeik** [comment]
Thank you guys 💯
