### ISSUE TITLE
After installing SwifterSwift my view´s corner radius changed

### ISSUE THREAD

**Issue by jpghelfi** [SwifterSwift/SwifterSwift#329]
### What did you do?
>  I set myView.layer.cornerRadius = 8 first, then after installing this Pod...

### What did you expect to happen?
> myView.layer.cornerRadius = 8 // Corner rounded 8pts

### What happened instead?
> I see the corners very rounded.. at leaat 20pts. And no matter what value I set.. it always look very rounder. Before installing the Pod, it worked

### SwifterSwift Environment

- SwifterSwift version: 4.0.1
- Xcode version: 9.0
- macOS version running Xcode: Sierra 10.12.6
- Swift version: 3.2
- Platform(s) running SwifterSwift: iOS 11

**Comment by omaralbeik** [comment]
Hey @jpghelfi, I'm not sure I understood the problem clearly :)

SwifterSwift has the extension [`cornerRadius `](https://github.com/SwifterSwift/SwifterSwift/blob/master/Sources/Extensions/UIKit/UIViewExtensions.swift#L76) to set corner radius a for a UIView, all it does is setting cornerRadius for view's layer, and nothing more.

Could you please place 2 `print(yourView.layer.cornerRadius)` statements before and after setting `cornerRadius` to see what is exactly happening.

**Comment by omaralbeik** [comment]
@jpghelfi any update on this :)
