### ISSUE TITLE
Error occured after updating 4.1.0 in xcode 9.2 

### ISSUE THREAD

**Issue by sahabe1** [SwifterSwift/SwifterSwift#331]
<img width="843" alt="screen shot 2017-12-06 at 4 39 37 pm" src="https://user-images.githubusercontent.com/1065015/33659046-c6aa2c2c-daa4-11e7-94e6-be9e9c2a54c9.png">

**Comment by omaralbeik** [comment]
@sahabe1 Could you clean and rebuild from Product menu in Xcode and let me know if the problem still exist

**Comment by sahabe1** [comment]
still facing same issue

**Comment by omaralbeik** [comment]
@sahabe1 Are you using Swift 3.2 or 4 ?

**Comment by sahabe1** [comment]
<img width="295" alt="screen shot 2017-12-07 at 4 49 25 pm" src="https://user-images.githubusercontent.com/1065015/33712812-c5fb1dfc-db6e-11e7-835e-2b541b7c81fd.png">

**Comment by omaralbeik** [comment]
@sahabe1 This is SwifterSwift version, I meant your project that you are using SwifterSwift in
