### ISSUE TITLE
Add an extension to create a MD5 hash from a string

### ISSUE THREAD

**Issue by JulianYu** [SwifterSwift/SwifterSwift#338]
[ ] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you expect to happen?
> how about add something like md5

**Comment by omaralbeik** [comment]
@JulianYu, thats a nice extension to have, could you please submit a pull request and I'll make sure to review it and get it merged in as soon as I can 👍

**Comment by omaralbeik** [comment]
I found this [stackoverflow thread](https://stackoverflow.com/questions/32163848/how-to-convert-string-to-md5-hash-using-ios-swift) that has a suggested way of doing this.

**Comment by SD10** [comment]
@omaralbeik What do you think about this? SwifterSwift has very little to no limitations when it comes to which extensions we accept into the project, but I think avoiding adding cryptography extensions is a healthy limitation.

**Comment by omaralbeik** [comment]
@SD10 I agree. let's not get into cryptography for now

**Comment by omaralbeik** [comment]
@JulianYu Thank you for bringing this to the table. We don't think SwifterSwift is a good fit for cryptography extensions at the moment, [CryptoSwift](https://github.com/krzyzanowskim/CryptoSwift) is taking care of this :)
