### ISSUE TITLE
Update LICENSE copyright date to 2018

### ISSUE THREAD

**Issue by SD10** [SwifterSwift/SwifterSwift#350]
https://github.com/SwifterSwift/SwifterSwift/blob/master/LICENSE
```diff
MIT License
-- Copyright (c) 2015-2017 SwifterSwift (https://github.com/swifterswift)
++ Copyright (c) 2015-2018 SwifterSwift (https://github.com/swifterswift)
```

**Comment by richgabrielli** [comment]
Hi. I am looking to get involved with a Swift project this year. Is anyone working on this? How can I get started / help?

**Comment by SD10** [comment]
Hey @richgabrielli,

First, you need to fork the `SwifterSwift` repository to your personal account. You can see the fork button in the top right corner next to the stars. (Please start the project if you haven't already 😂)

Then you need to clone your fork to your local machine, make changes to the LICENSE.md file, and
then push your changes back up to your fork.

After you do that, you need to create a pull request from your fork to SwifterSwift `master` branch.

If any of these steps are unclear, try and Google the process. I couldn't find a guide that I was happy with at the moment. Of course, you can also ask questions here

**Comment by richgabrielli** [comment]
Thanks! I will give it a shot. I have done a few tutorials on GitHub and I understands all your words so I will give it a shot. 🤣

**Comment by richgabrielli** [comment]
I submitted the pull request, but received a message I was not expecting. Do I need to do anything else? Can you help?

<img width="815" alt="screen shot 2018-01-02 at 4 43 23 pm" src="https://user-images.githubusercontent.com/7821160/34501271-22ba0298-efdc-11e7-9fd4-6cd5b551a5b4.png">

**Comment by SD10** [comment]
@richgabrielli No worry. That is just our continuous integration software. Everytime someone submits a PR it runs the changes against all our unit tests to make sure nothing broke

**Comment by SD10** [comment]
This was closed by #351

**Comment by richgabrielli** [comment]
Great! That was pretty awesome. I need to look at a Swift topic. Can I ask a quick question? Do I need to delete my fork and re-fork each time I want to work on an issue?

**Comment by SD10** [comment]
No you don’t have to. However, sometimes a fork can go stale... meaning it doesn’t reflect the changes of the original repo. I would recommend you read:

https://help.github.com/articles/configuring-a-remote-for-a-fork/

This tells you how to add a remote reference to the original repository

and then how to pull the changes into your local copy:

https://help.github.com/articles/syncing-a-fork/


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by richgabrielli** [comment]
@SD10 - why does my local forked branch show up as out of sync with the update I changed?
<img width="1015" alt="screen shot 2018-01-03 at 9 50 22 am" src="https://user-images.githubusercontent.com/7821160/34525188-16d16ad0-f06c-11e7-8351-f481e4129fc7.png">

**Comment by SD10** [comment]
@richgabrielli your fork doesn't mirror the original repo. this is because maybe you want to fork a project and then work on it / take things in another direction. you have to update it manually if you want it to stay in sync. that's what those 2 links above are for

**Comment by richgabrielli** [comment]
Thanks. Which two links?

**Comment by richgabrielli** [comment]
@SD10 - I just noticed this: thoughts?

<img width="684" alt="screen shot 2018-01-03 at 11 07 18 am" src="https://user-images.githubusercontent.com/7821160/34528280-646277da-f076-11e7-8a29-bd645196343c.png">

**Comment by SD10** [comment]
I meant this:
https://github.com/SwifterSwift/SwifterSwift/issues/350#issuecomment-354885903

CI error is fine, I canceled the build because there were no code changes.

**Comment by richgabrielli** [comment]
@SD10 - Thanks. I did follow the links and had no issues executing the commands.  
I still have this message: This branch is 1 commit ahead, 1 commit behind SwifterSwift:master.
I still receive this when I do a compare next to the message above

<img width="1039" alt="screen shot 2018-01-03 at 11 21 42 am" src="https://user-images.githubusercontent.com/7821160/34529042-b7b80e3e-f078-11e7-8282-14036f36dc2a.png">
:

**Comment by richgabrielli** [comment]
@SD10 - I have really confused myself. I just want to get in sync and understand what is happeningI tried to do another pull request to see if that helps. I appreciate all your help.

**Comment by SD10** [comment]
You probably wanted to rebase and not merge. The goal is to get your branch even with SwifterSwift `master`.
