### ISSUE TITLE
Add timestamp to text extension

### ISSUE THREAD

**Issue by SD10** [SwifterSwift/SwifterSwift#358]
Add an extension to turn a timestamp into text stating how long it's been from now. This is commonly used in social media / messaging applications.

Supporting these formats would be good:

- now
- N seconds ago
- N minutes ago
- N hours ago
- N days ago
- N week ago
- N month ago
- N years ago

**Comment by Vyax** [comment]
I could implement this, but we need a way to localize this feature. Does Foundation provide translations for terms like "hour(s)" or "year(s)"?

**Comment by Najdan** [comment]
I found few possible solutions for this issue but I didn't had time to finish it. `DateComponentFormatter` looks like best, but I found problems with it which seems like bugs. I'll attach code and screenshots so if @Vyax you have more time you can improve it. I'm really short on time these days. One of my questions was translation support too and [`DateComponentFormatter`](https://developer.apple.com/documentation/foundation/datecomponentsformatter) supports translations by default.

<img width="2032" alt="358-maximumunitcount1" src="https://user-images.githubusercontent.com/4264802/35553853-d2187c24-0599-11e8-9022-3fa814794b25.png">
<img width="2032" alt="358-maximumunitcount2" src="https://user-images.githubusercontent.com/4264802/35553854-d235200e-0599-11e8-9e50-6ea37fc13369.png">
<img width="1136" alt="358-maximumunitcountdocumentation" src="https://user-images.githubusercontent.com/4264802/35553855-d24eed90-0599-11e8-84a5-65e5efeeb17e.png">

Here is the gist for code used in playground https://gist.github.com/Najdan/bd747aba595829292f93904acb7b7e8c

**Comment by omaralbeik** [comment]
It looks like this is beyond the scope of SwifterSwift, I'll close this issue for now, feel free to open it again if you find an easy way to handle localization without adding the actual localization text to the project
