### ISSUE TITLE
About Array Extensions

### ISSUE THREAD

**Issue by BackWorld** [SwifterSwift/SwifterSwift#368]
**> How can I get a subarray with a Range from an parent array?**
```
let array = [1, 2, 3, 4]
let subarray = array[0..<2] = [1, 2]
// or
let subarray = array.subArray(from 0..<2) = [1, 2]
```
> The Array Extension
```
extension Array{
    public func subArray(from range: Range) -> Array{
// TODO:
    }
}
```

> Look forward to your help.

**Comment by nathanbacon** [comment]
`let subarray = array[0..<2]`
This would return an array slice which leaves the rest of the array in memory but not allocating in new memory. Are you asking how make a new array, allocating new memory for the subarray? 

`array[0..<2].map { $0 }` would allocate new memory for the slice and the rest of the array would be thrown out when it goes out of scope.

**Comment by BackWorld** [comment]
So thanks.
