### ISSUE TITLE
Someone write me a script to count the number of extensions ❤️ 

### ISSUE THREAD

**Issue by SD10** [SwifterSwift/SwifterSwift#372]
It would be nice to get the new count of the number of SwifterSwift extensions! 
Maybe we could check for all `public var` and `public func` in all source files 😂

**Comment by omaralbeik** [comment]
@pvtmert, tagging you here because I know you love this stuff :)

**Comment by pvtmert** [comment]
yes i do :)

**Comment by omaralbeik** [comment]
I created a small script and named it [SwiftMeter](https://github.com/SwifterSwift/SwiftMeter) to scan our code base and generate some useful statistics, here is the initial report
```
{
    "functions": 229, 
    "ib_inspectables": 28, 
    "failable_initializers": 9, 
    "static_functions": 40, 
    "total_static_units": 542, 
    "variables": 220, 
    "code_lines": 4207, 
    "structs": 5, 
    "total_non_static_units": 468, 
    "swift_files": 56, 
    "classes": 0, 
    "extensions": 101, 
    "total_lines": 8941, 
    "initializers": 10, 
    "static_variables": 502, 
    "enums": 6, 
    "operators": 11, 
    "total_units": 1010
}
```

**Comment by SD10** [comment]
Going to close this 👍
