### ISSUE TITLE
Conflict between SwifterSwift and React-Native

### ISSUE THREAD

**Issue by syq7970** [SwifterSwift/SwifterSwift#383]
[ x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
I have a React-Native based project, and I use SwifterSwift in the native part.

### What did you expect to happen?
Everything will be OK.

### What happened instead?
Got a crash when I set text component borderColor in JS part.
I think there is some conflict between SwifterSwift and React-Native. 

<img width="613" alt="default" src="https://user-images.githubusercontent.com/12478505/35551254-3fce274e-05c9-11e8-8396-5edd70e7ee66.png">
<img width="534" alt="default" src="https://user-images.githubusercontent.com/12478505/35551259-458cb70e-05c9-11e8-8dbc-42b210d9e6a6.png">
<img width="723" alt="default" src="https://user-images.githubusercontent.com/12478505/35551273-5159f100-05c9-11e8-9272-7642c18326e6.png">

### SwifterSwift Environment

- SwifterSwift version: 4.1.1
- Xcode version: 9.2
- macOS version running Xcode: 10.13.3
- Swift version: 4.0
- Platform(s) running SwifterSwift: iOS

### Demo Project
https://github.com/syq7970/RNSwifterSwiftBugDemo

**Comment by SD10** [comment]
I'm not sure how to handle this one. I'm unfamiliar with react native 😕

**Comment by syq7970** [comment]
@SD10 @omaralbeik Thanks for the reply, I will update the PR as you suggest
