### ISSUE TITLE
array.sum() crash 

### ISSUE THREAD

**Issue by a1bertwang** [SwifterSwift/SwifterSwift#391]
### What did you do?
> I invoke [UInt8].sum() then I got a crash. The total variable should not be a UInt8 type(I think). sorry about my english ==!

### SwifterSwift Environment

- SwifterSwift version: 4.0.0+
- Xcode version: 9.2
- macOS version running Xcode: 10.13.3
- Swift version: 4.0
- Platform(s) running SwifterSwift: 4.0

**Comment by akuzminskyi** [comment]
As for me, this looks like correct behavior("out of stack space") because a developer precisely indicates what type of data he works.

**Comment by a1bertwang** [comment]
UInt8.max is 255. If the total variable is over than UInt8.max then got a type overflow.The total should not be input array's type in this case. Function sum() should think about type overflow.

**Comment by SD10** [comment]
I don't think this is something that SwifterSwift should be responsible for. It's kind of an edge case. I would just write my own sum function and handle the return type accordingly 😅
