### ISSUE TITLE
Collection.randomItem crash with empty collection

### ISSUE THREAD

**Issue by LucianoPAlmeida** [SwifterSwift/SwifterSwift#404]
Collection.random item extension is not handling the empty array case.
Also, the tests for this extensions are in the wrong file (ArrayTests), should be in the CollectionExtensionsTests.

**Comment by SD10** [comment]
Whoever fixes this, make sure they add a test to handle the empty case 😅

**Comment by calebkleveter** [comment]
Issue 404 handles non-existent cases in a `Collection` 😂.
