### ISSUE TITLE
[Discussion] Add SwiftLint Run Script Phase

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#410]
Shouldn't we add [SwiftLint run script phase](https://github.com/realm/SwiftLint#xcode) to Xcode?

**Comment by LucianoPAlmeida** [comment]
@omaralbeik We have it added, that phase does nothing when the machine where the code is being compiled doesn't have swiftlint installed

**Comment by BennX** [comment]
@LucianoPAlmeida @omaralbeik can confirm that it is within the phases and runs when installed. I tend to oversee the warnings 😞

**Comment by omaralbeik** [comment]
@LucianoPAlmeida I see, thank you :)

**Comment by omaralbeik** [comment]
@BennX No problems :)

**Comment by BennX** [comment]
@omaralbeik In case it's not installed it'll inform the Users where to get it 👍 
<img width="280" alt="screen shot 2018-02-18 at 5 04 58 pm" src="https://user-images.githubusercontent.com/4281635/36353976-e5d44656-14cd-11e8-8c52-502b7b4a87b6.png">
