### ISSUE TITLE
Recursive version of UIView.firstResponder property

### ISSUE THREAD

**Issue by LucianoPAlmeida** [SwifterSwift/SwifterSwift#415]
SwifterSwift has a property that finds a subview that is firstResponder from a view.
<img width="677" alt="screen shot 2018-03-04 at 17 53 08" src="https://user-images.githubusercontent.com/8292651/36950515-b4162a54-1fd5-11e8-9c52-d7c9b66c3d77.png">

But this extension just searches in the subviews, and not recursive in the subviews of subviews of the subviews and so on... 
The proposal implements a recursive version that searches recursively in the view hierarchy
I implemented a version, that could be a start for who takes this
```swift
    func recursiveFirstResponder() -> UIResponder? {
        guard !subviews.isEmpty else { return nil }
        for subview in subviews {
            if subview.isFirstResponder {
                return subview
            } else {
                if let responder = subview.recursiveFirstResponder() {
                    return responder
                }
            }
           
        }
        return nil
    }
```

**Comment by calebkleveter** [comment]
How much of a concern is the performance of this method? It seems to me that the preposed implementation would be pretty slow.

**Comment by LucianoPAlmeida** [comment]
Hey @calebkleveter the more performant the best :) 
Indeed this is not the most performant implementation, but actually is very simple to improve :))

**Comment by LucianoPAlmeida** [comment]
I've implemented a better version
```swift 
    func firstResponder() -> UIView? {
        guard
            !isFirstResponder else { return self }
        guard
            !subviews.isEmpty else { return nil }
        
        if let responder = subviews.first(where: { $0.isFirstResponder }) {
            return responder
        }
        for subview in subviews {
            if let responder = subview.firstResponder() {
                return responder
            }
        }
        return nil
    }
```
Didn't send a PR because I think there are some points need to discuss
1. It is better to do another version that is recursive or update the firstResponder existing to handle this edge case.
2. If the answer to the first one is updating the existing extension( which I prefer), I think it should become a method instead of a property.

@omaralbeik, @SD10 what do you guys think?

**Comment by SD10** [comment]
@LucianoPAlmeida For what reason do you want to find the first responder?

**Comment by LucianoPAlmeida** [comment]
@SD10 It's very rare, but sometimes I have to access a text field inside an keyboard event handler for example, in a generic way, like a BaseViewController. But, the use case where I tried to use the UIView.firstResponder extension and notice that it was not recursive, was to find a textField that was inside a cell, on a tableView.

**Comment by SD10** [comment]
@LucianoPAlmeida I think the best way would be to tell `UIApplication` to resign the first responder. Events bubble up through the`UIResponder` chain to `UIApplication` before exiting.

```Swift
UIApplication.shared.sendAction(#selector(resignFirstResponder), to: nil, for: nil, from: nil)
```

**Comment by LucianoPAlmeida** [comment]
@SD10 this  works only if I wanted just resign. But there's cases where I actually needs the instance of the text field to perform some operations on it :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BennX** [comment]
If a iterative solution is not slower then a recursive solution like in sort algorithms i would pick the iterative solution. Lower complexity and smaller memory food print.
