### ISSUE TITLE
Refactor ArrayExtensions

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#427]
Some methods like `sum`, `average` can be moved from ArrayExtensions to CollectionExtensions, this will make them accessible for other Collection types as well.

**Comment by LucianoPAlmeida** [comment]
Hey @omaralbeik I think some extension also can be moved to Sequence instead of Collection. 
For example: `count(where:)` and `forEachReversed()` I think could be on Sequence.
