### ISSUE TITLE
Your app links against the MapKit framework but does not appear to include Maps functionality. 

### ISSUE THREAD

**Issue by lugq1001** [SwifterSwift/SwifterSwift#429]
> MapKit was introduced in the framework, causing my application review to be rejected by Apple. Is there any solution?

========================================================================
### Rejected Information

Guideline 2.1 - Performance

Your app links against the MapKit framework but does not appear to include Maps functionality. 

Next Steps

If you do not intend to use Maps, please unlink the MapKit framework. If you would like to use Maps, please add the "com.apple.developer.maps" entitlement and submit an updated binary for review.

**Comment by LucianoPAlmeida** [comment]
Hey @lugq1001 are you installing it via Cocoapods? 
If you are:
Today we have the following Subspecs 
'SwiftStdlib' 
'Foundation' 
'UIKit'  
'AppKit' 
'CoreGraphics' 
'CoreLocation'
'MapKit'
 You can use this subspecs to install only ones that you need. For example, installing only stdlib subspecs `pod 'SwifterSwift/SwiftStdlib'` :)) That way you can just ignore MapKit Spec

**Comment by LucianoPAlmeida** [comment]
Hey @lugq1001 :))
I'm not sure, but I think at this time, Carthage does not provide a way to build only specific repository submodules. All submodules and their dependencies will be built with the Carthage instalation :((

**Comment by SD10** [comment]
@lugq1001 You can also just copy and paste the SwifterSwift extensions that you need. You don't have to use a package manager

**Comment by omaralbeik** [comment]
We're adding `#if canImport(module)` statements everywhere in the next release, @SD10, @LucianoPAlmeida do you think it will help here?

@lugq1001 could you try installing SwifterSwift from master, I'm not sure if this will help, but worth the try 😅

**Comment by SD10** [comment]
I'm not sure if it is because his platform is iOS but I'm not sure if the `@available` attribute on the MapKit extension only makes it available to tvOS extensions currently.

**Comment by LucianoPAlmeida** [comment]
I don't think it will because if Carthage compiles for iOS, for example, this canImport(MapKit) will always be true, even if not using the Mapkit extensions. But I don't know enough about Carthage to affirm that with 100% sure.

**Comment by omaralbeik** [comment]
@lugq1001 We recently released v4.3 with a possible solution to this issue, could you try and let us know 🙂

**Comment by omaralbeik** [comment]
@lugq1001 I'll close this issue for now, please let us know if you have the same problem again
