### ISSUE TITLE
remove(from view: UIView) extension to UIGestureRecognizer

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#443]
UIKit lets us remove gesture recognizers from views by using the `removeGestureRecognizer(_:)` method, sometimes we have an optional recognizer, and the code becomes like:
```swift
if let recognizer = leftEdgePanGestureRecognizer {
    view.removeGestureRecognizer(recognizer)
}
```

It would be nice to have this as an extension to `UIGestureRecognizer` so we can chain the methods like:
```swift
leftEdgePanGestureRecognizer?.remove(from: view)
```

**Comment by mmdock** [comment]
@omaralbeik 
I was under the impression that a UIGestureRecognizer could only be used with a single view.

So, why would you need the remove(from:) ?

```
public extension UIGestureRecognizer {

    public func remove() {

        self.view?.removeGestureRecognizer(self)

    }

}
```

Something like that should work (haven't tested yet)

Per docs:

view

The view the gesture recognizer is attached to. (read-only)

@property(nonatomic, readonly) UIView *view

Discussion You attach (or add) a gesture recognizer to a UIView object using the addGestureRecognizer: method.

**Comment by omaralbeik** [comment]
@mmdock Thanks for bringing this, I didn't know `UIGestureRecognizer` can't be added to more than one `UIView` 😅
In this case I agree with you it doesn't make any sense to me to have a `view` argment in the method 👍

**Comment by mmdock** [comment]
This is being worked on #456
