### ISSUE TITLE
Add extension to generate random character

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#448]
Add an extension to `Character` to generate a random character

**Comment by mmdock** [comment]
@omaralbeik isn't there a lib for this already? https://github.com/thellimist/SwiftRandom
Just get a random string of length 1(from SwiftRandom), then get the subscript of index 0 on the string (from SwifterSwift's extensions).

**Comment by omaralbeik** [comment]
Thank you @mmdock 🙂
Our goal is to make **SwifterSwift** the widest place to find extensions (if not already :trollface:)
Users should be able to copy a single extension and start using it in no time, while in [SwiftRandom](https://github.com/thellimist/SwiftRandom) users are expected to install the entire project to use this simple extension

**Comment by mmdock** [comment]
@omaralbeik gotcha - i'll take a gander at this in a few hours; trying to get familiar with doing pull requests with the UIGestureRecognizer task on the other thread before I start more.
