### ISSUE TITLE
Add MapKit to install using Cocoapods in README

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#472]
Add `SwifterSwift/MapKit` subspec to [install using Cocoapods](https://github.com/SwifterSwift/SwifterSwift#--integrate-corelocation-extensions-only) in README

**Comment by rafalellys** [comment]
Update complete. PR #481. Thanks!

**Comment by omaralbeik** [comment]
Thanks for taking care of this @rafalellys 🚀

**Comment by rafalellys** [comment]
My pleasure @omaralbeik 😄
