### ISSUE TITLE
Add [UIView] to UIStackView

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#474]
Create an extension to add an array of views to `UIStackView`.

### Suggested names:
- `addArrangedSubviews(_views: [UIView])`
- `appendArrangedSubviews(_views: [UIView])`

**Comment by jdisho** [comment]
Calling dips ☝️😜

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
