### ISSUE TITLE
UIWindow extension to switch the rootViewController with animation

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#477]
Add an extension to change `rootViewController` in a `UIWindow` with animation, duration, UIViewAnimationOptions and a completion handler.

**Comment by ratulSharker** [comment]
Hi @omaralbeik , i have following implementation regarding this issue


```swift
public func switchRootVC(to viewController: UIViewController, duration: TimeInterval, completion: @escaping () -> Void) {
        viewController.view.alpha = 0.0
        viewController.view.frame = CGRect.init(x: 0, y: frame.size.height, width: frame.size.width, height: frame.size.height)
        addSubview(viewController.view)
        
        UIView.animate(withDuration: duration, animations: { 
            viewController.view.alpha = 1.0
            viewController.view.frame = self.frame
        }) { (_) in
            self.rootViewController = viewController
            completion()
        }
    }
```

with `duration = 1.0` it look like following

![Output](https://imgur.com/download/WIsIiF4)

It will restrict the developer to the animation provided in the `switchRootVC` implementation. Will it be overkill to provide interface for providing custom animation by the callee of this method ?

Please share your thought.

**Comment by kpavankotesh** [comment]
Any iOS 13 implementation for the same ?

**Comment by musatrtr** [comment]
I testes it in iOS 13.5 in simulator. It is working well.
