### ISSUE TITLE
Update CONTRIBUTING.md for unit test guidelines

### ISSUE THREAD

**Issue by SD10** [SwifterSwift/SwifterSwift#488]
We should separate any guidelines for writing unit tests into its own section called "Adding Tests".

I'd like to mention the following 3 things, in addition to anything that exists already:
1. We use one subclass of `XCTestCase` for every extended SwifterSwift type.
2. The subclass should be marked as `final`.
3. There should be a 1:1 ratio between SwifterSwift methods/properties and their backing unit tests.
4. We should not add SwifterSwift source files to the test target directly, but rather import SwifterSwift into the test target by using: `@testable import SwifterSwift`

**Comment by LucianoPAlmeida** [comment]
Closed by #518
