### ISSUE TITLE
Upgrade to Swift 4.1

### ISSUE THREAD

**Issue by SD10** [SwifterSwift/SwifterSwift#489]
It probably wouldn't hurt to do a SwifterSwift 4.4 release in the near future. 
We have a few new extensions and should probably upgrade to Swift 4.1. 

cc @LucianoPAlmeida If you want to take this on LMK 👌

**Comment by LucianoPAlmeida** [comment]
@SD10 For sure we can work on that :)) 
I think we already did the 4.1 upgrade on  #428 that was in the 4.3.0 release 
But indeed will be good to release those new extensions 💯
