### ISSUE TITLE
Documentation has dead links

### ISSUE THREAD

**Issue by bjimenezned** [SwifterSwift/SwifterSwift#499]
There are several dead links in the documentation site sidebar
Examples:
Calendar
http://swifterswift.com/docs/Extensions/Calendar.html

Color and all the subpages
http://swifterswift.com/docs/Extensions/Color.html

File Manager
http://swifterswift.com/docs/Extensions/FileManager.html

Floating point
http://swifterswift.com/docs/Extensions/FloatingPoint.html

MKPolyline
http://swifterswift.com/docs/Extensions/MKPolyline.html

NSPredicate
http://swifterswift.com/docs/Extensions/NSPredicate.html

and others more

**Comment by LucianoPAlmeida** [comment]
Hey @bjimenezned 
Thank you for finding this issue, we'll investigate this :)) 
cc @omaralbeik

**Comment by SD10** [comment]
I don't know if we need to regenerate the documentation with Jazzy?

**Comment by omaralbeik** [comment]
Thank you for reporting this @bjimenezned 💯
I had the `/docs` directory added to `.gitigore` file in the website repo by accident in the last release 😅

**All links should be working now**
