### ISSUE TITLE
Trivial request: docs link edit?

### ISSUE THREAD

**Issue by wdcurry** [SwifterSwift/SwifterSwift#506]
This is utterly trivial, but would be a sweet change: on the main swifterswift site, please consider edits the topmost docs link to take us directly to the docs and not to another link to the docs. This is a wee bit silly ;) .. I know i can bookmark the docs of course, but this is just a simple thought. Cheers!

**Comment by omaralbeik** [comment]
Fixed, @wdcurry thanks for reporting this 💯
