### ISSUE TITLE
Using NetworkExtension module in UIDeviceExtension

### ISSUE THREAD

**Issue by marcocapano** [SwifterSwift/SwifterSwift#521]
Hi! I'm working on an extension of UIDevice to give people access to bssid, ssid and signal strength by simple doing 
`let SSID = UIDevice.current.ssid`

The extension is working as expected but it needs special entitlements to work. You can request those at https://developer.apple.com//contact/request/network-extension/ .

What should I do now? Should the library itself include entitlements? (But can it?)
Should the library include just the extension, giving to the users the job to add entitlements to their apps?
Should the library not at all include such an extension, since it requires special entitlements ?

[x ] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

**Comment by marcocapano** [comment]
Update: Apple responded me that they will not give me entitlements for a library.

So two options remain:

- we include just the code, and the user is responsible of adding entitlements if he wants to use this extension (A #warning in Swift 4.2 ?)
- we don't include such an extension at all, meaning that maybe we should close related issues.

**Comment by DimaZava** [comment]
@marcocapano You have to request special entitlements for network extension for obtaining list of visible WiFi ssids, for gathering only current active I use any extra capabilities.

```
import SystemConfiguration.CaptiveNetwork

extension UIDevice {
    
    public var SSID: String? {
        
        guard let interfaceNames = CNCopySupportedInterfaces() as? [String] else {
            return nil
        }
        return interfaceNames.compactMap { name in
            guard let info = CNCopyCurrentNetworkInfo(name as CFString) as? [String:AnyObject] else {
                return nil
            }
            guard let ssid = info[kCNNetworkInfoKeySSID as String] as? String else {
                return nil
            }
            return ssid
            }.first
    }
}
```

So in the same way you can get BSSID and some other current wifi connection's properties

**Comment by SD10** [comment]
Haven't read this entire thread but `SSID` -> `ssid` if anyone adds an extension from the discussion 😛

**Comment by omaralbeik** [comment]
Thank you for your extension @marcocapano 
I think we should not include extensions that require specific entitlements
