### ISSUE TITLE
carthage build failure

### ISSUE THREAD

**Issue by xvwvx** [SwifterSwift/SwifterSwift#524]
> Please fill out this template when filing an issue.
>
> All comment lines beginning with an **>** instruct you with what info we expect. You can delete those lines once you've filled in the info.
>

[ ] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
> carthage build --platform iOS

### What did you expect to happen?
> Please replace this with what you expected to happen.

### What happened instead?
```
Could not cast value of type 'Swift.Int64' (0x10efdbf70) to 'Swift.String' (0x10efe24c8).
/Users/snow/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/SwifterSwift/4.4.0/Build/Intermediates.noindex/ArchiveIntermediates/SwifterSwift-iOS/IntermediateBuildFilesPath/SwifterSwift.build/Release-iphoneos/SwifterSwift-iOS.build/Script-074EAF161F7B859500C74636.sh: line 6: 44861 Abort trap: 6           swiftlint
Command /bin/sh failed with exit code 134
```

### SwifterSwift Environment

- SwifterSwift version:
4.4.0
- Xcode version:
9.4.1
- macOS version running Xcode:
10.13.4
- Swift version:
4.1
- Platform(s) running SwifterSwift:
iOS

### Demo Project
> github "SwifterSwift/SwifterSwift" ~> 4.0

**Comment by LucianoPAlmeida** [comment]
Hey @xvwvx 
Sorry for the delay :)
Are you still having this issue?

**Comment by LucianoPAlmeida** [comment]
Closing this due inactivity. But feel free to reopen if still having this issue :))
