### ISSUE TITLE
No UIView extension properties visible under Interface Builder for my Storyboard

### ISSUE THREAD

**Issue by larjohn** [SwifterSwift/SwifterSwift#531]
> Please fill out this template when filing an issue.
>
> All comment lines beginning with an **>** instruct you with what info we expect. You can delete those lines once you've filled in the info.
>

[x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?

1. I have added SwifterSwift to my cartfile
2. I have fetched and built it with Carthage (`carthage update SwifterSwift --platform iOS`)
3. I have added the framework to Carthage inputs and Link Libraries with Binary lists in Build Phase of project settings
5. I have imported SwifterSwift both in my AppDelegate and the ViewController of my View
4. I have built the project 

### What did you expect to happen?
I thought some new properties would appear under the properties editor, when, for instance, I create a UIButton.

### What happened instead?
Only the default properties appear. Nevertheless, the extension properties are visible from code.

### SwifterSwift Environment

- SwifterSwift version: 4.4.0
- Xcode version: 9.4.1
- macOS version running Xcode: 10.13.6
- Swift version: 4.1
- Platform(s) running SwifterSwift: iOS

### Demo Project
>Please link to or upload a project we can download that reproduces the issue.

**Comment by LucianoPAlmeida** [comment]
Hey @larjohn :))
Have you added the Carthage build folder to the framework search paths? 
Also can you make check if "Run script only when installing" is unchecked? 
Those are the two first things that I could thought :)

**Comment by larjohn** [comment]
@LucianoPAlmeida Yes and yes ... must be something else :(

**Comment by LucianoPAlmeida** [comment]
Hey @larjohn :))
Sorry for the delay on the response, but I believe you don't have to.
I've found that same issue reported in some other frameworks, seems like an old issue and I think there is a bug for that.
But there's some people that have done some workaround that, take a look at https://github.com/Carthage/Carthage/issues/763 
And again, sorry for the delay on the answer 😭

**Comment by LucianoPAlmeida** [comment]
Closing this due inactivity. But feel free to reopen to further discussions :))
