### ISSUE TITLE
Feature Request : NSView extension

### ISSUE THREAD

**Issue by phiren** [SwifterSwift/SwifterSwift#533]
Can you please add below:
```
@IBDesignable
extension NSView
{
	@IBInspectable var backgroundColor: NSColor? {
		get {
			if let colorRef = self.layer?.backgroundColor {
				return NSColor(CGColor: colorRef)
			} else {
				return nil
			}
		}
		set {
			self.wantsLayer = true
			self.layer?.backgroundColor = newValue?.CGColor
		}
	}
}
```

**Comment by guykogus** [comment]
You’re welcome to open a pull request yourself and do it 🙂

**Comment by phiren** [comment]
Created first pull request, hope someone will approve and merge to master.

**Comment by halossd** [comment]
When I use NSTextField.backgroundColor, this is ambiguous property now

**Comment by 342261733** [comment]
When I use NSTextField.backgroundColor, this is ambiguous property now. same problem
