### ISSUE TITLE
Update Exemples.md documentation file.

### ISSUE THREAD

**Issue by LucianoPAlmeida** [SwifterSwift/SwifterSwift#535]
The [Exemples.md](https://github.com/SwifterSwift/SwifterSwift/blob/master/Examples/Examples.md) was last updated on the Swift 3 release and needs to be updated. 

[x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

**Comment by SD10** [comment]
Do we need this file anymore even? I don't think it's that useful personally
