### ISSUE TITLE
Xcode 10 + Swift 4.2 support

### ISSUE THREAD

**Issue by martinstoyanov** [SwifterSwift/SwifterSwift#548]
- [x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
> Attempted to run the latest SwiftierSwift version (4.4.0) on Xcode 10

### What did you expect to happen?
> Succesful compile

### What happened instead?
> 31 errors 

### SwifterSwift Environment

- SwifterSwift version: 4.4.0
- Xcode version: 10
- macOS version running Xcode: 10.13
- Swift version: 4.2
- Platform(s) running SwifterSwift: iOS

**Comment by calebkleveter** [comment]
Can you edit your issue with the errors you got?

**Comment by RamblinWreck77** [comment]
Hello! Thanks for a great set of tools! Any update on this? For now setting just SwifterSwift back to Swift 4 in Xcode 10 works, but pod install sets it back every time.

**Comment by guykogus** [comment]
@RamblinWreck77 you're welcome to follow updates for PR https://github.com/SwifterSwift/SwifterSwift/pull/562

**Comment by LucianoPAlmeida** [comment]
Hey people :)) 
v4.5.0 is out \o/
