### ISSUE TITLE
When shadows and rounded corners are set at the same time, the shadow effect disappears

### ISSUE THREAD

**Issue by q351941406** [SwifterSwift/SwifterSwift#551]
When shadows and rounded corners are set at the same time, the shadow effect disappears

**Comment by jianstm** [comment]
Hi, @q351941406 , `roundCorners()` is incompatible with `addShadow(ofColor:)` i think, it sets a `mask` to the view.

If you want all corners rounded, use `view.cornerRadius = r`, then call `view.addShadow(ofColor:)`, it will work. If you only want specified corners rounded, a workaround is to add the view with specified corners rounded to a container view with shadow:

**Comment by bernikowich** [comment]
You cannot apply shadow to UIView with mask. But there is workaround:
http://travisjeffery.com/b/2012/08/ios-how-to-mask-and-shadow-an-image/
