### ISSUE TITLE
SelectedImage for tabbar doesn't work well on iPhoneX

### ISSUE THREAD

**Issue by tobitech** [SwifterSwift/SwifterSwift#558]
https://github.com/SwifterSwift/SwifterSwift/blob/2d48141ac50bb38e7f6d0d82747f63e1e4414237/Sources/Extensions/UIKit/UITabBarExtensions.swift#L22

Please can you provide a fix for this method to work well on iPhoneX. Thanks

**Comment by LucianoPAlmeida** [comment]
Hey @tobitech :))
Can you explain the error and what is happening on the iPhone X?
Also, if you want to, feel free to submit a PR with a fix 👍

**Comment by tobitech** [comment]
the selected background rect is pushed downwards.

<img width="332" alt="screen shot 2018-08-31 at 2 00 03 pm" src="https://user-images.githubusercontent.com/8595853/44913810-4d2da680-ad26-11e8-9373-161f4496dbe8.png">

**Comment by tobitech** [comment]
another issue i just noticed is when the device orientation changes to landscape, and one selects a new tabbar item, the selectedbackground image maintains the modified size that shows in landscape and isn't back to appropriate size until another tab is selected

**Comment by LucianoPAlmeida** [comment]
Closing this since you found a solution :))
