### ISSUE TITLE
Nested Dictionary String Key value

### ISSUE THREAD

**Issue by LucianoPAlmeida** [SwifterSwift/SwifterSwift#565]
When having a nested JSON like 

```
{  
   "error":{  
      "statusCode":422,
      "name":"ValidationError",
      "message":"Errors ",
      "details":{  
         "context":"Context",
         "codes":{  
            "password":[  
               "presence"
            ],
            "email":[  
               "uniqueness"
            ]
         },
         "messages":{  
            "password":[  
               "can't be blank"
            ],
            "email":[  
               "Email already exists"
            ]
         }
      }
   }
}

```
And transforming to a dictionary, if we want to check the value of error->details->codes->passwod.
Probably we have to guarding nested dictionaries until we get our value like
```swift
guard let error = json["error"] as? [String: [String: Any]], 
let details = error["details"] .... till we get the value ["presence"].
```
So, with that being said, the proposedProposed extension is

```swift
extension Dictionary where Key == String {
    
    subscript(dotPath path: String) -> Any? {
        ....
    }
}

json[dotPath: "error.details.codes.password"] -> ["presence"]

```

* [x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

**Comment by calebkleveter** [comment]
Do we want this to return type `Any` or a generic type `T`?

**Comment by calebkleveter** [comment]
Here's a fix: https://github.com/SwifterSwift/SwifterSwift/pull/574
