### ISSUE TITLE
SwifterSwift.podspec Add s.swift_version = "4.2" , Please

### ISSUE THREAD

**Issue by lixiang1994** [SwifterSwift/SwifterSwift#567]
> Please fill out this template when filing an issue.
>
> All comment lines beginning with an **>** instruct you with what info we expect. You can delete those lines once you've filled in the info.
>

[ ] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
> Please replace this with what you did.

### What did you expect to happen?
> Please replace this with what you expected to happen.

### What happened instead?
> Please replace this with of what happened instead.

### SwifterSwift Environment

- SwifterSwift version: 4.5.0
- Xcode version: 10
- macOS version running Xcode:
- Swift version: 4.2
- Platform(s) running SwifterSwift:

### Demo Project
>Please link to or upload a project we can download that reproduces the issue.

**Comment by guykogus** [comment]
This is already in progress but has a strange issue with CI...
https://github.com/SwifterSwift/SwifterSwift/pull/566

**Comment by lixiang1994** [comment]
OK
