### ISSUE TITLE
Where to put extensions of `Dispatch`?

### ISSUE THREAD

**Issue by jianstm** [SwifterSwift/SwifterSwift#584]
Hi, I want to add some extensions of `Dispatch`, no idea where to put them. `Foundation`? We can use `Dispatch` if we `import Foundation`, but it's indeed a separate module.

**Comment by guykogus** [comment]
You'd need to create a new section for it. You can call `import Dispatch` since it's its own framework, so just like we have folders for `Foundation`, `UIKit`, etc. you'd create a new one for `Dispatch`.

**Comment by jianstm** [comment]
@guykogus Thanks!
