### ISSUE TITLE
UIImage: Tinted image results in flipped image

### ISSUE THREAD

**Issue by wousser** [SwifterSwift/SwifterSwift#586]
[x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
Tinted image
```
backgroundImage.image = UIImage(named: "image")?.tint(UIColor.black, blendMode: .normal)
```

### What did you expect to happen?
Image with tinted color

### What happened instead?
Image with tinted color that is vertically flipped

### SwifterSwift Environment

- SwifterSwift version: 4.5.0
- Xcode version: Version 10.0 (10A255)
- macOS version running Xcode:
- Swift version:
- Platform(s) running SwifterSwift:

### Demo Project
-

**Comment by HimmaHorde** [comment]
I had changed this function

**Comment by HimmaHorde** [comment]
` func filled(withColor color: UIColor) -> UIImage ` this will return the image with tinted color.

I have modified this function to blend layers
```oc
    func blend(_ color: UIColor, mode: CGBlendMode) -> UIImage {
        let rect = CGRect(x: 0, y: 0, width: size.width, height: size.height)
        UIGraphicsBeginImageContextWithOptions(size, false, scale)
        color.setFill()
        guard let context = UIGraphicsGetCurrentContext() else { return self }

        draw(in: rect)

        // 旋转画布用于添加填充层
        context.translateBy(x: 0, y: size.height)
        context.scaleBy(x: 1.0, y: -1.0)
        context.setBlendMode(mode)

        // 添加填充层
        guard let mask = cgImage else { return self }
        context.clip(to: rect, mask: mask)
        context.fill(rect)

        context.scaleBy(x: 1.0, y: -1.0)

        let newImage = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()
        return newImage
    }
```
eg.  
```
let image = UIImage.init(named: "TestImage.png")!

let mutiplyImage = image.blend(UIColor.red, mode: .multiply)
```
