### ISSUE TITLE
Why I can't use this extensions?

### ISSUE THREAD

**Issue by invisible66** [SwifterSwift/SwifterSwift#591]
### What did you do?
I installed SwifterSwift using CocoaPods

### What did you expect to happen?
I want to use extensions

### What happened instead?
SwifterSwift installed but I can't use extensions

### SwifterSwift Environment

- SwifterSwift version: 4.6.0
- Xcode version: 10.0
- macOS version running Xcode: HighSierra 
- Swift version: 4.2
- Platform(s) running SwifterSwift: IOS

### ScreenShot

![ekran resmi 2018-10-17 14 43 57](https://user-images.githubusercontent.com/8086679/47084069-2adee200-d21b-11e8-959e-0a28cb4c6df1.png)

**Comment by guykogus** [comment]
You might have to add
`import SwifterSwift`
At the top of your file

**Comment by invisible66** [comment]
> You might have to add
> `import SwifterSwift`
> At the top of your file

But it's an extension. I think, i don't need to import SwifterSwift. 
And i already tried. Not working.

**Comment by invisible66** [comment]
I removed pod and install manually.. I can use extensions now..
