### ISSUE TITLE
[UIImageView extension] UIImageView size does not fit size of downloaded UIImage

### ISSUE THREAD

**Issue by maxxx777** [SwifterSwift/SwifterSwift#601]
[x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
Use [UIImageView Extension](https://github.com/SwifterSwift/SwifterSwift/blob/master/Sources/Extensions/UIKit/UIImageViewExtensions.swift#L22) to download image
```
let imageView = UIImageView()
imageView.download(from: URL(string: "https://developer.apple.com/swift/images/swift-og.png")!,
                   contentMode: .scaleAspectFit,
                   placeholder: image1,
                   completionHandler: { downloadedImage in
})
```

### What did you expect to happen?
Size of `imageView` fits the size of `downloadedImage`.

### What happened instead?
`imageView` has initial size `{width: 0, height: 0}`

### SwifterSwift Environment

- SwifterSwift version: 4.6.0
- Xcode version: 10.0 (10A255)
- macOS version running Xcode: 10.13.6 (17G65)
- Swift version: 4.2
- Platform(s) running SwifterSwift: iOS

### Demo Project
Example can be found in Examples.playground from https://github.com/SwifterSwift/SwifterSwift/pull/596

**Comment by LucianoPAlmeida** [comment]
Hey @maxxx777 Sorry for the late response, we will take a look on that as soon as possible 👍
