### ISSUE TITLE
UIImageExtensions line 62 

### ISSUE THREAD

**Issue by Coder-XI** [SwifterSwift/SwifterSwift#625]
> Please fill out this template when filing an issue.
>
> All comment lines beginning with an **>** instruct you with what info we expect. You can delete those lines once you've filled in the info.
>

[ ] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
> Please replace this with what you did.

### What did you expect to happen?
> Please replace this with what you expected to happen.

### What happened instead?
> Please replace this with of what happened instead.

### SwifterSwift Environment

- SwifterSwift version:
- Xcode version:
- macOS version running Xcode:
- Swift version:
- Platform(s) running SwifterSwift:

### Demo Project
>Please link to or upload a project we can download that reproduces the issue.

**Comment by Coder-XI** [comment]
I find code in UIImageExtensions line 62 (version 4.6.0)

> guard rect.size.height < size.height && rect.size.height < size.height else { return self }

Why there two rect.size.height judgements?

**Comment by LucianoPAlmeida** [comment]
Hey @Coder-XI Thank's for report this :)) This is probably a mistake on implementation

**Comment by LucianoPAlmeida** [comment]
Fixed on #575 :))
