### ISSUE TITLE
Remove some Collection extensions

### ISSUE THREAD

**Issue by LucianoPAlmeida** [SwifterSwift/SwifterSwift#636]
Some [Collection Extensions](https://github.com/SwifterSwift/SwifterSwift/blob/master/Sources/Extensions/SwiftStdlib/CollectionExtensions.swift) 
* `firstIndex(where: )`
* `firstIndex(of:)`
* `lastIndex(where: )`
* `lastIndex(of:)`

Should be removed since they are now (since swift 4.2) part of the Swift Standard Library. 
See: [SE-0204](https://github.com/apple/swift-evolution/blob/master/proposals/0204-add-last-methods.md)

They have the exact same signature, so removing them will not cause any breaking changes :))

And also maybe we should check for some old extensions that are now provided by the stdlib.

**Comment by marcocapano** [comment]
I think we can close this since #637 is waiting to be accepted
Or maybe leave it open to discuss other extensions that may be unnecessary ?

**Comment by LucianoPAlmeida** [comment]
We close this as soon as the PR 
We can open a new one for the others :))
