### ISSUE TITLE
Fix `Date.yesterday` to go back exactly 1 day

### ISSUE THREAD

**Issue by guykogus** [SwifterSwift/SwifterSwift#640]
[x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
Following discussions of https://github.com/SwifterSwift/SwifterSwift/pull/578 it was agreed that the implementation should be changed to use `Calendar.date(byAdding:to:)`.

The problem with using `date.addingTimeInterval(-86400)` can be seen below.

```Swift
let timeZone = TimeZone(identifier: "America/Denver")!

let formatter = ISO8601DateFormatter()
formatter.timeZone = timeZone
let date = formatter.date(from: "2019-03-11T00:00:00-06:00")! // 11 Mar 2019 at 00:00
formatter.string(from: date) // 2019-03-11T00:00:00-06:00 (👆, obviously)

var calendar = Calendar.current
calendar.timeZone = timeZone
let yesterdayCalendar = calendar.date(byAdding: .day, value: -1, to: date)! // 10 Mar 2019 at 00:00
formatter.string(from: yesterdayCalendar) // 2019-03-10T00:00:00-07:00
yesterdayCalendar.timeIntervalSince(date) // -82800

let yesterday24Hours = date.addingTimeInterval(-86400) // 9 Mar 2019 at 23:00
formatter.string(from: yesterday24Hours) // 2019-03-09T23:00:00-07:00
```

### What did you expect to happen?
Going back to `yesterday` should go back to the previous calendar day.

### What happened instead?
In certain situations, as demonstrated above, it jumped back 2.

**Comment by LucianoPAlmeida** [comment]
Closed on #641 and #642 
Thank you guys 👍
