### ISSUE TITLE
Add Probot-Stale for Issues and PR

### ISSUE THREAD

**Issue by BennX** [SwifterSwift/SwifterSwift#644]
It might make sense to add a Stale Bot to the Issues and PR's.

https://github.com/probot/stale
https://github.com/apps/stale

What do you think?

**Comment by LucianoPAlmeida** [comment]
Sure @BennX 💯

**Comment by LucianoPAlmeida** [comment]
Now that I just closed a lot of stale PR's manually, I'm pretty sure it will be a great addition. 
Labeling help wanted in case someone wants to tackle this :))
