### ISSUE TITLE
Introduce a new `SwifterSwiftWrapper` type

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#645]
I wrote a [blog post](https://omaralbeik.com/blog/protocol_oriented_extensions) recently highlighting how to avoid extensions conflicts using a wrapper type, similar to what [RxSwift](https://github.com/ReactiveX/RxSwift), [Kingfisher](https://github.com/onevcat/Kingfisher) and other libraries do.

I believe SwifterSwift is a perfect application for this, it will reduce the number of conflicts with other frameworks (especially ones with Date extensions) and make the project more future proof in my opinion

The only issue I can see is it will introduce tons of breaking changes of course 😅

However, with the new Swift 5.0 release bringing ABI stability, I tought it is the right time to consider such a large change before releasing the next version.

Please let me know what do you think and respond with 👍 if you like the idea, or with 👎 if you think it is not a good fit for SwifterSwift

---

### `SwifterSwiftWrapper `
```swift
public struct SwifterSwiftWrapper<Base> {
    public let base: Base
    public init(_ base: Base) {
        self.base = base
    }
}
```

### `SwifterSwiftCompatible `
```swift
public protocol SwifterSwiftCompatible {
    associatedtype CompatibleType
    static var swf: SwifterSwiftWrapper<CompatibleType>.Type { get set }
    var swf: SwifterSwiftWrapper<CompatibleType> { get set }
}

extension SwifterSwiftCompatible {
    public var swf: SwifterSwiftWrapper<Self> {
        get {
            return SwifterSwiftWrapper(self)
        }
        set {}
    }
    public static var swf: SwifterSwiftWrapper<Self>.Type {
        get {
            return SwifterSwiftWrapper<Self>.self
        }
        set {}
    }
}

```

#### Data+Extensions
```swift
extension Data: SwifterSwiftCompatible {}

public extension SwifterSwiftWrapper where Base == Data {
    /// SwifterSwift: Return data as an array of bytes.
    var bytes: [UInt8] {
        return [UInt8](base)
    }
}
```

#### String+Extensions
```swift
extension String: SwifterSwiftCompatible {}

public extension SwifterSwiftWrapper where Base == String {
    /// SwifterSwift: String decoded from base64 (if applicable).
    ///
    ///		"SGVsbG8gV29ybGQh".base64Decoded = Optional("Hello World!")
    ///
    var base64Decoded: String? {
        guard let decodedData = Data(base64Encoded: base) else { return nil }
        return String(data: decodedData, encoding: .utf8)
    }
}
```

#### Date+Extensions
```swift
extension Date: SwifterSwiftCompatible {}

public extension SwifterSwiftWrapper where Base == Date {
    /// SwifterSwift: Year.
    ///
    ///		Date().year -> 2017
    ///
    ///		var someDate = Date()
    ///		someDate.year = 2000 // sets someDate's year to 2000
    ///
    var year: Int {
        get {
            return Calendar.current.component(.year, from: base)
        }
        set {
            guard newValue > 0 else { return }
            let currentYear = Calendar.current.component(.year, from: base)
            let yearsToAdd = newValue - currentYear
            if let date = Calendar.current.date(byAdding: .year, value: yearsToAdd, to: base) {
                base = date
            }
        }
    }
}
```

**Comment by omaralbeik** [comment]
@SD10 @LucianoPAlmeida @guykogus @basememara

**Comment by freak4pc** [comment]
I'm personally kind of +0 ;]
If someone doesn't want the Data extensions, they can avoid using that specific subspec. 

I don't know if it adds too much, but as I mentioned I'm quite neutral. It is quite verbose, which is the main downside I'm feeling here.

**Comment by LucianoPAlmeida** [comment]
Hey @omaralbeik :)) 
I love the concept of this, but as far as adopting it here, I'm neutral like @freak4pc, like the idea but also think it makes more verbose, which is kinda less Swifter. Not to mention the breaking changes.
But although it is verbose, it makes clear that you use a SwifterSwift which can be good. 
Also, I think that there are some other ways that we can avoid the conflict with other module extensions e.g. "adjusting the import declarations to specific functions of a module" see [Resolving Symbol Name Collisions section here](https://nshipster.com/import/) 

In the end, I'm biassed to not adopting for two reasons:
* The breaking changes and verbosity(meaning that I feel that is more natural use it directly on the type). But the second one its personal preference :))

**Comment by basememara** [comment]
Good call on bringing this up during Swift 5 transition. That works around the breaking changes dilemma.

For the API itself, I know it’s the right thing to do... but I don’t wanna 😭

It’s an extra barrier to discovery. It’s nice seeing the custom API’s next to similar native calls. SwifterSwift seems to be more of a polyfill than sugar syntax.

I think Xcode needs to catch up here and show custom and native autocomplete results differently. And offer to resolve or fix them if there’s conflicts.

Maybe a section in the readme outlining a clean workaround to conflicts when they arise in consumer projects.

**Comment by BennX** [comment]
Hey @omaralbeik, I haven't come across that solution yet and it feels a bit clumsy. 

In my opinion conflicts are intended and aren't a bad thing. They indicate that you use two frameworks with same naming and indicate that you should be aware of this. Moreover, you must resolve it by detailing the usage of whatever function/extension you are using.

Thus, I must agree with @LucianoPAlmeida. I personally wouldn't introduce it into SwifterSwift because @LucianoPAlmeida said in another issue: 

> A lot of user just copy and paste parts of SwifterSwift without using the whole Library. 

That approach would make it harder to do this.

**Comment by guykogus** [comment]
@omaralbeik I'm in 2 minds about this. On the one hand, it's an excellent solution for avoiding conflicts and actually makes the project more easily usable as a wholly imported library. I know, it doesn't look as pretty when imported this way, but the conflicts are the biggest setback for this project. (@BennX I don't see how this would change the way people copy-paste parts of the project. They'll still be able to copy-paste into their own extension files.)
On the other hand, @LucianoPAlmeida's solution of resolving conflicts with more specific `import`s is a lot cleaner. Maybe this is something that we should include in the `README`. This helps us avoid a project-wide breaking change.

**Comment by freak4pc** [comment]
One more point you should consider is that - wrapping stuff in a `wrapper<Base>` type makes the extension itself has a generic constraint on Base. It's usually not an issue, but I've had cases where It was a major PITA (e.g. when having a Networking with some Reactive Base, it made it very hard to pass around freely).

**Comment by omaralbeik** [comment]
Thank you for your feedback guys, many thoughtful responses here 👏

I personally never use SwifterSwift as a dependency in any production project, Instead, I use it a resource and prefer to copy what I need, thus I never had conflict issues before.

However, when used as a dependency, our only solution to minimize conflicts is to use subspecs for now, well, what about users using Swift package manager or Chartage?

## What I like about using the wrapper type:
- Offer a starting point - or that magic door - for utilities and polyfills like [lodash](https://lodash.com/) for javascript.
- Make it easier to differentiate SwifterSwift extensions from others simply by reading the code.
- Eliminate conflicts with other frameworks.
- It will give us a chance to look at all extensions one by one when porting them.

## What I don't like on the other hand:
- Tons of breaking changes (eventually every extension should be modified)
- It will make slightly harder to use the project as a reference, copying a single unit will still require to copy the main wrapper struct, or replace all occurrences of `base` with `self`
- As @freak4pc mentioned, the new wrapper type might be limiting in the future

I definitely believe we should have a section in README highlighting how to solve conflicts as @LucianoPAlmeida is suggesting.

Either way, I think we should release the next major version soon to keep up with the new Swift 5 release.

Let's keep this issue open untill the next release to get broader feedback from other contributors as well 😃

**Comment by omaralbeik** [comment]
I'm going to close this issue for now, thank you all guys for your valuable comments 😃

**Comment by Asura19** [comment]
@omaralbeik 
I try to import var of SwifterSwift after reading the blog https://nshipster.com/import/, but it failed, how can I resolve it?
<img width="1230" alt="iShot2022-06-20 14 17 37" src="https://user-images.githubusercontent.com/13399701/174537092-b5a43c76-69f1-4a89-b102-475b2ebea7da.png">
