### ISSUE TITLE
UIEdgeInsetsExtensions Not Public

### ISSUE THREAD

**Issue by chulbert** [SwifterSwift/SwifterSwift#651]
[X] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
Upgraded to 5.0.

### What did you expect to happen?
UIEdgeInsets extension methods remain public.

### What happened instead?
UIEdgeInsets extension methods became internal.  It looks the extensions were never declared public so the cleanup activity on their functions resulted in an access level of internal.

### SwifterSwift Environment

- SwifterSwift version: 5.0
- Xcode version: 10.2
- macOS version running Xcode: 10.14.4
- Swift version: 5.0
- Platform(s) running SwifterSwift: iOS

**Comment by LucianoPAlmeida** [comment]
@chulbert Thank's for reporting, we'll fix as soon as possible 👍 Feel free to send a PR too :))
