### ISSUE TITLE
Add Array Extension for filtered on the  KeyPath

### ISSUE THREAD

**Issue by fanglinwei** [SwifterSwift/SwifterSwift#653]
```swift
public extension Array where Element: Equatable {
    
     // Returns a deduplicated array based on the optional key path.
    public func filtered<E: Equatable>(duplication path: KeyPath<Element, E>) -> [Element] {
        return reduce(into: [Element]()) { (result, e) in
            let contains = result.contains { $0[keyPath: path] == e[keyPath: path] }
            result += contains ? [] : [e]
        }
    }
}
```

**Comment by guykogus** [comment]
Hey @fanglinwei, why not make a PR to add this feature? 😉

Also, a minor suggestion: Checking `contains` on an `Array` has complexity `O(n)`, which means that your function is, at worst case where you have an array that won't need any filtering, `O(n²)`. If you use a `Set` you can get `O(n)` complexity, but you lose the ordering. What do you think?

```Swift
public extension Array where Element: Hashable {
    /// Returns a deduplicated array based on the optional key path.
    ///
    /// - Parameter path: <#path description#>
    /// - Returns: <#return value description#>
    public func filtered<E: Equatable>(keyPath path: KeyPath<Element, E>) -> [Element] {
        return Array(reduce(into: Set<Element>()) { (result, element) in
            if !result.contains { $0[keyPath: path] == element[keyPath: path] } {
                result.insert(element)
            }
        })
    }
}
```

**Comment by chulbert** [comment]
This looks like a variant `withoutDuplicates` with a custom equality predicate.  That's an awfully specific use case but if we want to include it I would recommend something a little more flexible like a closure that takes two parameters and returns a boolean.

**Comment by RomanPodymov** [comment]
Hello @chulbert 
I added `withoutDuplicates` with a custom comparator in #704.
