### ISSUE TITLE
Color extension recommend,

### ISSUE THREAD

**Issue by fanglinwei** [SwifterSwift/SwifterSwift#657]
In swift, colorLiteral can reflect color, is this more intuitive?

<img width="717" alt="企业微信截图_0f1fe2fa-733a-4980-85f7-ddfafbcaa567" src="https://user-images.githubusercontent.com/16839723/55553597-319eda00-5713-11e9-872f-23368ab54a1b.png">

```swift
public static let facebook1 = #colorLiteral(red: 0.231372549, green: 0.3490196078, blue: 0.5960784314, alpha: 1)

```

**Comment by guykogus** [comment]
I think it's a matter of taste. Personally I wouldn't focus on changing it, but happy to hear the thoughts of others.

**Comment by chulbert** [comment]
I think it's more useful to see the values in source code than a color swatch.

**Comment by omaralbeik** [comment]
Thank you for your suggestion @fanglinwei, I see how color literals makes the code looks better in Xcode, however, I have to agree with @guykogus and @chulbert here for the following two reasons

1. Color literals do not look like this in another text editors
2. Using values is more readable; especially for people wanting to copy and paste the values

**Comment by mmdock** [comment]
Personally, i do this:

```
extension UIColor {

static let facebook: Color = 0x3B5998
```

but i have my `Color` in my personal project setup differently than here in SwifterSwift:

```
class Color: UIColor, ExpressibleByIntegerLiteral {

    public required convenience init(integerLiteral value: IntegerLiteralType) {
        let red = CGFloat((value & 0xFF0000) >> 16) / 255
        let green = CGFloat((value & 0x00FF00) >> 8) / 255
        let blue = CGFloat(value & 0x0000FF) / 255
        self.init(red: red, green: green, blue: blue, alpha: 1)
    }
}
```

**Comment by omaralbeik** [comment]
I'm going to close this issue for now, feel free to open again to extend the discussion :)
