### ISSUE TITLE
Refactoring URLExtension.swift

### ISSUE THREAD

**Issue by ratulSharker** [SwifterSwift/SwifterSwift#661]
[x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
> I was reading `queryValue` extension method in `URLExtensions.swift`, i found some refactoring can be done in this method.

### What did you expect to happen?
> Refactor the extension method.

### What happened instead?
> Existing code is too verbose, and too much check is done and not straight forward.

### SwifterSwift Environment

- SwifterSwift version:
- Xcode version:
- macOS version running Xcode:
- Swift version:
- Platform(s) running SwifterSwift:

### Demo Project
The current implementation is looks like following

```swift
    func queryValue(for key: String) -> String? {
        let stringURL = absoluteString
        guard let items = URLComponents(string: stringURL)?.queryItems else { return nil }
        for item in items where item.name == key {
            return item.value
        }
        return nil
    }
```

But the refactored version will look like following

```swift
   func queryValue(for key: String) -> String? {
        return URLComponents(string: self)?.queryItems?.filter({ (queryItem) -> Bool in
            return queryItem.name == key
        }).first?.value
    }
```

**Is this refactored version make sense ? if so, i can create a pull request about this.**

**Comment by guykogus** [comment]
Hi @ratulSharker, thanks for spotting this refactor. Your code won't actually work because `self` is a `URL`, not a `string`. I think a better refactor would be:
```Swift
func queryValue(for key: String) -> String? {
    return URLComponents(url: self, resolvingAgainstBaseURL: true)?
        .queryItems?
        .first(where: { $0.name == key })?
        .value
}
```
What do you think? If you like it you're welcome to create a PR.

**Comment by ratulSharker** [comment]
I was using this as an extension of string thats why missed the `absoluteString` instead of `self`, Otherwise everything is good to go with the extension written. Then the code would be like following

```swift
   func queryValue(for key: String) -> String? {
        return URLComponents(string: absoluteString)?.queryItems?.filter({ (queryItem) -> Bool in
            return queryItem.name == key
        }).first?.value
    }
```

@guykogus i agree your code segment is better refactored in case of using short notation for filtering.

I was unaware of the method `init(url:resolvingAgainstBaseURL:)`, i checked the [appledoc](https://developer.apple.com/documentation/foundation/urlcomponents/3126811-init) which show me no useful info, then this [answer](https://stackoverflow.com/questions/38720933/whats-the-difference-between-passing-false-and-true-to-resolvingagainstbaseurl) put some light about what it means. What is the reason for using this initializer in particular ?

**Comment by guykogus** [comment]
It doesn't really matter which initialiser you use, I just liked the idea of passing the `URL` object itself rather than the string representation. Either way is fine.

**Comment by ratulSharker** [comment]
Yes using the `first(where:)` is faster rather than `filter`, so the final code portion is like following

```swift
func queryValue(for key: String) -> String? {
    return URLComponents(string: absoluteString)?
    .queryItems?
    .first(where: { $0.name == key })?
    .value
}
```

is it good to go ? @guykogus

**Comment by guykogus** [comment]
Sure, go ahead and create the PR ;)

**Comment by chulbert** [comment]
I would second @guykogus recommendation to initialize `URLComponents` with `URL` instead the unrelated type `String`.  Additionally, it appears to be more performant to initialize with an instance of `URL`.
