### ISSUE TITLE
Can't use .count property correctly of Range<String.Index> 

### ISSUE THREAD

**Issue by Natai** [SwifterSwift/SwifterSwift#665]
> Please fill out this template when filing an issue.
>
> All comment lines beginning with an **>** instruct you with what info we expect. You can delete those lines once you've filled in the info.
>

[ ] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
> get cout of a Range<String.Index> 

### What did you expect to happen?
> get .cout correctly

### What happened instead?
> xcode show error: Ambiguous reference to member 'count(where:)'
```
let text = "hello"
let maxIndex = text.index(text.startIndex, offsetBy: 2)
let maxRange = text.rangeOfComposedCharacterSequence(at: maxIndex)
maxRange.count
```

### SwifterSwift Environment

- SwifterSwift version: 4.6.0
- Xcode version: 10.1
- macOS version running Xcode: 10.13.6
- Swift version: 4.2
- Platform(s) running SwifterSwift: iOS

### Demo Project
>Please link to or upload a project we can download that reproduces the issue.

**Comment by RomanPodymov** [comment]
Hello @Natai 
Get `Type 'String.Index' does not conform to protocol 'Strideable'` when compile the code from the issue even if I remove `SwifterSwift` from project. Are you sure that your code is correct?

**Comment by guykogus** [comment]
I can see this problem on Xcode 10.2.1. The problem is that the `Sequence` extension has a `count(where:)` function that clashes.
