### ISSUE TITLE
Remove some character extensions

### ISSUE THREAD

**Issue by LucianoPAlmeida** [SwifterSwift/SwifterSwift#673]
Character extensions `isNumber`, `isLetter`, `isLowercased`, `isUppercased` and `isWhiteSpace` should be removed because they are now on the stdlib. 

The name and signatures are the same, so remove them are safe and will not break anything :)

**Comment by ChristopherAaronBrown** [comment]
I'm new to open source projects and this sounds like something I can tackle. If this is still open, can I get it a swing?

**Comment by LucianoPAlmeida** [comment]
@ChristopherAaronBrown Welcome to OS \o/
There is already a PR to this #675, but we are always opening new `good first issue' issues, so I'll make sure to add you if you want to contribute :))
