### ISSUE TITLE
Cannot subscript a value of type 'String' with an index of type '(safe: Range<Int>)'

### ISSUE THREAD

**Issue by ningkexin** [SwifterSwift/SwifterSwift#688]
swift 5.0

SwifterSwift (5.0.0)

```swift
        let str = "hello world";
        let str1 = str[safe: 0..<3]
```

The above code will prompt an error. I will rewrite an extension and write these functions. It is not. Why?

**Comment by RomanPodymov** [comment]
Hello @ningkexin 
This code works for me in Xcode 10.2.1 and I also use SwifterSwift 5.0.0. What Xcode version are you using?

**Comment by LucianoPAlmeida** [comment]
Hey @ningkexin @RomanPodymov :))
@ningkexin Can you elaborate more on what error it is giving you, so we can check?

**Comment by LucianoPAlmeida** [comment]
I just notice that these two(this one and the one that takes a ClosedRange) extensions could be improved by using a `RangeExpresion` since the string type is a collection.

**Comment by ningkexin** [comment]
@RomanPodymov I also use Version 10.2.1 (10E1001)

**Comment by ningkexin** [comment]
@LucianoPAlmeida I don't know why this is causing the problem, but I can probably provide my usage environment. I am using it under the old project (Objective-C). In addition, I used swift4.2 before. I didn't use this POD at first. I just tried the extension of String, which didn't cause any problems during the use. Then I tried the swift5.0 version yesterday, and this problem has appeared!

**Comment by ningkexin** [comment]
![image](https://user-images.githubusercontent.com/17719524/59325067-333cdd80-8d14-11e9-8fba-0c6f718a211a.png)
Xcode also indexes two definitions, but I commented out that my extension is not compiled.

**Comment by LucianoPAlmeida** [comment]
This duplication is probably because Xcode didn’t reindexed after you comment. But my question is more about the error message. What the error log the compiler is outputting?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ningkexin** [comment]
@LucianoPAlmeida 
- Please see the error message below. I have already "Clean Build Folder" before this.
![image](https://user-images.githubusercontent.com/17719524/59586132-c317c880-9114-11e9-9dcf-c56ca563fee4.png)

**Comment by guykogus** [comment]
Sorry if this is an obvious question, but have you called `import SwifterSwift`?

**Comment by ningkexin** [comment]
Oh, it’s stupid, I solved my problem!
