### ISSUE TITLE
Why is the `isRunningOnSimulator` and `deviceName` methods gone?

### ISSUE THREAD

**Issue by Jinxiansen** [SwifterSwift/SwifterSwift#691]
🤔

**Comment by guykogus** [comment]
@Jinxiansen when/where were they a part of this library?

**Comment by Jinxiansen** [comment]
http://cocoadocs.org/docsets/SwifterSwift/1.1/Classes/SwifterSwift.html#/s:ZvC12SwifterSwift12SwifterSwift20isRunningOnSimulatorSb
I used SwifterSwift a long, long time ago, and with `SwifterSwift` I would have no such method.

![133](https://user-images.githubusercontent.com/16829428/60507709-56e3ba00-9cfb-11e9-8d1f-edf56ca34ad6.png)


< English is not my native language; please excuse typing errors.

**Comment by guykogus** [comment]
@omaralbeik it looks like this disappeared when creating version 5.0.0. Was there any reason in particular that the properties/methods from SwifterSwift.swift were deleted instead of moved?

**Comment by Jinxiansen** [comment]
Oh, what is the reason for the deletion? I still like these methods very much, but now I am not.😔😔😔

**Comment by omaralbeik** [comment]
Hey @Jinxiansen
Sorry for the inconvenience here

This extension and many others have been removed and re-introduced into their own relevant types. more details in [#654](https://github.com/SwifterSwift/SwifterSwift/issues/654)

You can use
```swift
UIApplication.shared.inferredEnvironment
```

As for the `deviceName` property, feel free to open a pull request and add it under `UIDeviceExtensions` 😃
