### ISSUE TITLE
Mutating versions of removeDuplicates(keyPath:)

### ISSUE THREAD

**Issue by RomanPodymov** [SwifterSwift/SwifterSwift#710]
- [x] 🚀 I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

Currently there are `nonmutating` `withoutDuplicates()` and `mutating` `removeDuplicates()` in `extension Array`. Let's add `mutating` versions of `func withoutDuplicates<E: Equatable>(keyPath path: KeyPath<Element, E>) -> [Element]` and `func withoutDuplicates<E: Hashable>(keyPath path: KeyPath<Element, E>) -> [Element]`.

### SwifterSwift Environment

- SwifterSwift version: 5.0.0
- Xcode version: 10.3
- macOS version running Xcode: 10.14.6
- Swift version: 5.0
- Platform(s) running SwifterSwift: macOS

**Comment by iglushchuk** [comment]
I can handle it :)

**Comment by LucianoPAlmeida** [comment]
Thank's @RomanPodymov @iglushchuk :)
