### ISSUE TITLE
Use XcodeGen

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#714]
It would be great to use [XcodeGen](https://github.com/yonaskolb/XcodeGen) to auto-generate the `.xcodeproj` and `xcworkspace` files from a `yml` or `json` file

This will make the code cleaner and help reduce merge conflicts :)

**Comment by Saik0s** [comment]
Hi @omaralbeik, I would like to work on this improvement.

**Comment by LucianoPAlmeida** [comment]
@Saik0s Go for it ;)

**Comment by moritzsternemann** [comment]
Hey @Saik0s 👋 what's your progress? Maybe I can help out 😃

**Comment by Saik0s** [comment]
Hi @moritzsternemann! I am half way through, it just takes some time to write the instruction file for all the targets, so going to finish it in upcoming couple of days. Thanks!

**Comment by Saik0s** [comment]
Hi guys, unfortunately, I am not able to focus on this ticket right now and can get back to it at the end of the next week. @moritzsternemann If you want to pick it up - feel free. In another case, I will work on it next week.
