### ISSUE TITLE
UIImage.tint(color:blendMode:) improvement

### ISSUE THREAD

**Issue by LucianoPAlmeida** [SwifterSwift/SwifterSwift#731]
#Hacktoberfest 

Here we can do a minor tweak where this extension is implemented using an old `UIGraphicsBeginImageContextWithOptions` API. That is not recommended. 
We can provide an improvement for it and make this using `UIGraphicsImageRenderer` API.

Note: `UIGraphicsImageRenderer` is only available from iOS 10. So we should maintain the current implementation for lower iOS versions like:
```swift
if #available(iOS 10.0, tvOS 10.0, *) {
        // UIGraphicsImageRenderer new implementation
} else {
       // Current implementation with UIGraphicsBeginImageContextWithOptions
}
```
See #721 for an example.

**Comment by FraDeliro** [comment]
Thanks @LucianoPAlmeida, I will pick up this one :)
