### ISSUE TITLE
UIImage.filled(withColor:) improvement

### ISSUE THREAD

**Issue by LucianoPAlmeida** [SwifterSwift/SwifterSwift#732]
### Hacktoberfest 

Here we can do a minor tweak where this extension is implemented using an old `UIGraphicsBeginImageContextWithOptions` API. That is not recommended. 
We can provide an improvement for it and make this using `UIGraphicsImageRenderer` API.

Note: `UIGraphicsImageRenderer` is only available from iOS 10. So we should maintain the current implementation for lower iOS versions like:
```swift
if #available(iOS 10.0, tvOS 10.0, *) {
        // UIGraphicsImageRenderer new implementation
} else {
       // Current implementation with UIGraphicsBeginImageContextWithOptions
}
```
See #721 for an example.

**Comment by FraDeliro** [comment]
Hi @LucianoPAlmeida I could pick up this one :)

**Comment by raysarebest** [comment]
@FraDeliro Sorry for not commenting, before I started, but I was literally just about to click the button to make a PR for this 😅

**Comment by FraDeliro** [comment]
@raysarebest No worries :) go for it 👍

**Comment by LucianoPAlmeida** [comment]
@FraDeliro @raysarebest Thanks for taking this one, @FraDeliro there are another issues like this one you could take, just make sure to comment on that so people know there’s someone already working :))

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
