### ISSUE TITLE
Extend Sequence to get sum by keypath

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#735]
Extend The `Sequence` type with a `sum(for keyPath:)` function to return the sum of nested number for all objects within a sequence

Examples from [**Swift by Sundell**](https://swiftbysundell.com/articles/reducers-in-swift/)'s article on reducers
```swift
let unreadCount = mailboxes.sum(for: \.unreadMessages.count)
let totalScore = levels.sum(for: \.playerScore)
let meetingDuration = today.meetings.sum(for: \.duration)
```

**Comment by moritzsternemann** [comment]
I'd like to work on this task 😃 can you assign it to me?
