### ISSUE TITLE
StoreKit Extensions

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#740]
Create a new `localizedPrice` variable to return the localized price string for `SKProduct` utilizing the `priceLocale` property.
```swift
extension SKProduct {
    /// SwifterSwift: Localized price of `SKProduct`
    var localizedPrice: String? { ... }
}
```

Steps:
1. Create a new folder named `StoreKit`
2. Create a new file SKProductExtensions file and add the extension in it
3. Make sure to wrap the extension with `#if canImport(StoreKit) ... #endif`
4. Write a test for the extension
5. Add the new `StoreKit` subspec to [`SwifterSwift.podspec`](https://github.com/SwifterSwift/SwifterSwift/blob/master/SwifterSwift.podspec)
6. Submit the PR 🚀

**Comment by lareenmelo** [comment]
Hellooo, I'll give this a try!

**Comment by omaralbeik** [comment]
Sure @lareenmelo, go for it!

**Comment by mmdock** [comment]
@lareenmelo you still working on this ?

**Comment by lareenmelo** [comment]
Hi! It's okay you can go ahead and do it, I was currently working on another thing so I had it stack. But you go ahead!
