### ISSUE TITLE
Add base64String extension to UIImage

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#742]
Add a `base64String` property to return the encoded image as a base 64 string

```swift
public extension UIImage {
    /// SwifterSwift: Base 64 representation of the image.
    var base64String: String? { ... }
}
```

**Comment by moritzsternemann** [comment]
@omaralbeik Have you thought of a specific format to use for encoding (JPEG, PNG, ...)?

**Comment by omaralbeik** [comment]
I was thinking maybe use JPEG with `compressionQuality=1.0`, but now I see it makes sense to change it into a function with those parameters 🤔

**Comment by moritzsternemann** [comment]
Hmm the problem is that I can get the data either using `UIImage.pngData()` or `UIImage.jpegData(compressionQuality:)`. We could implement both versions or maybe reduce the scope to the jpeg, compressionQuality 1 version, because the other methods in the UIImage extension use these settings as well.

**Comment by guykogus** [comment]
If you look at the first extension we have for `UIImage`, we already have:
```Swift
var bytesSize: Int {
    return jpegData(compressionQuality: 1)?.count ?? 0
}
```
I'm not really a fan of it, personally, as it's the size of the uncompressed JPEG encoding, not the number of bytes in the `UIImage` object. It's the same issue here with this suggestions. If we had some enum type, e.g.
```Swift
enum ImageEncoding {
   case jpeg(compressionQuality: CGFloat)
   case png
}
```
we could then pass that as a parameter to decide how to convert an image to data. At the end of the day, all this function is going to do is be a short-hand for `jpegData(compressionQuality: 1)?.base64EncodedString()`, which may not be what callers want or expect.

**Comment by moritzsternemann** [comment]
We could access the internal data of the UIImage (`.cgImage?.dataProvider?.data as Data?`) but this is not the same data one would pass to `UIImage.init(data:)`. I think using the png representation and mentioning this in the documentation comment would be the best solution here.

**Comment by moritzsternemann** [comment]
...or implement two separate methods:
```swift
func pngBase64String() -> String? {}
func jpegBase64String(compressionQuality: CGFloat) -> String? {}
```

**Comment by guykogus** [comment]
I'd go for 2 separate methods. You could even add a third if you want `bitmapBase64String()` when getting the data from `CGDataProvider`.
Regardless, just having a single `base64String()` function may very well confuse callers, as I don't believe that they should have to check the function documentation to know the format of the image.

**Comment by moritzsternemann** [comment]
@guykogus Sounds good.

I did some further research into the bitmap representation and came to the conclusion that it's not a good solution. If the UIImage is backed by a CGImage, than `UIImage.cgImage` contains an internal representation. If the image is backed by a CIImage, `UIImage.ciImage` contains another internal representation.
In both cases the data of the backing structure is not a bitmap as in raw bytes of the image.
A CIImage can be rendered to a bitmap using [this method of CIContext](https://developer.apple.com/documentation/coreimage/cicontext/1437897-render) but I think that's a little too specific for generic extensions.
