### ISSUE TITLE
displayName is nil

### ISSUE THREAD

**Issue by nobut** [SwifterSwift/SwifterSwift#754]
Xcode11.2.1 does not use displayName. Without this CFBundleDisplayName field, there is CFBundleName in Info.plist

**Comment by nobut** [comment]
Xcode11.2.1 New Project Info.plist will not have CFBundleDisplayName

**Comment by nobut** [comment]
extension Bundle {
    public var appIcon: UIImage? {
        if let icons = infoDictionary?["CFBundleIcons"] as? [String: Any],
            let primaryIcon = icons["CFBundlePrimaryIcon"] as? [String: Any],
            let iconFiles = primaryIcon["CFBundleIconFiles"] as? [String],
            let lastIcon = iconFiles.last {
            return UIImage(named: lastIcon)
        }
        return nil
    }
}
This extension is also good, you can add it.

**Comment by guykogus** [comment]
@nobut you're always welcome to open a PR with suggested extensions :)
The only problem with the `appIcon` extension is that usually the app icons come from the Assets bundle. In that case you can just get the appIcon using `UIImage(named: "AppIcon")`.

**Comment by nobut** [comment]
Thank you very much.Is there a succinct way to get the app name?

**Comment by mmdock** [comment]
@nobut I just checked out `displayName` extension var for myself and works for me on iOS 11.2.1.  There seems to be some people on reddit also complaining about encountering the issue you are descibing when updating to 11.2.1.

Go to your target, click general, and make sure the product name is there. If it looks greyed out, it’s actually blank. Click the name and fill it back in.  This seems to be the common solution.  Let me know if it works for you

**Comment by nobut** [comment]
I am talking about using Xcode 11.2.1 instead of iOS12.1.1. I mean the newly created project. There is no CFBundleDisplayName field in Info.plist. Then I can't use UIApplication.shared.displayName to get the app name.
<img width="656" alt="Screen Shot 2019-11-12 at 4 18 16 PM" src="https://user-images.githubusercontent.com/28843198/68654160-4e807300-0568-11ea-8f89-756c8e703c17.png">
<img width="546" alt="Screen Shot 2019-11-12 at 4 19 43 PM" src="https://user-images.githubusercontent.com/28843198/68654161-4f190980-0568-11ea-9fde-451586cb8d9a.png">

**Comment by mmdock** [comment]
@nobut  sorry, meant to write `Xcode 11.2.1` not `iOS 11.2.1`.  

I am currently on that same build and mine is working correctly.  Can you follow the instructions I gave before and check on the Product name in the target?
