### ISSUE TITLE
Fix `compressed(quality:)` on UIImage extension

### ISSUE THREAD

**Issue by mmdock** [SwifterSwift/SwifterSwift#755]
`compressed(quality:)` extension function calls another SwifterSwift function `compressedData(quality:)`.

According to the SwifterSwift contributing guidelines:
> Do not use an existing SwifterSwift extension inside another SwifterSwift extension. All extensions should be able to be copied and pasted and work immediately without having to copy another extension.

Therefore, someone should update this function to make the above guideline true in this case.

This is meant to be a good first simple issue for new contributors.  Or for someone bored I guess.

**Comment by cyber-gh** [comment]
I'd like to give it a try.

**Comment by LucianoPAlmeida** [comment]
Cool \o/ go for it @cyber-gh :)

**Comment by LucianoPAlmeida** [comment]
Thank's @mmdock and @cyber-gh 👍
