### ISSUE TITLE
Use of unresolved identifier 'searchTextField' error in UISearchBar extension 

### ISSUE THREAD

**Issue by hamza-farooq-astutesol** [SwifterSwift/SwifterSwift#767]
hello devs. I am currently facing an issue regarding this library, i just updated the pod and now i am facing thus issue. I also tried deleting and reinstalling the pod but it didn't help at all. Looking for some assistance here. Thank you in advance.

**Comment by LucianoPAlmeida** [comment]
Hi @hamza-farooq-astutesol 
Ca you give more information about what version of pods, what version of the library, xcode ... and if is possible the exact error message you getting :)

**Comment by hamza-farooq-astutesol** [comment]
> Hi @hamza-farooq-astutesol
> Ca you give more information about what version of pods, what version of the library, xcode ... and if is possible the exact error message you getting :)

i am using:
xcode's Version: 10.2,
swift's version: 5
library's version: latest - pod 'SwifterSwift' to install the pod

**Comment by hamza-farooq-astutesol** [comment]
![Screenshot 2019-11-25 at 4 41 40 PM](https://user-images.githubusercontent.com/58171976/69537712-804efc00-0fa2-11ea-9ad3-4e6cffa30eaf.png)

**Comment by LucianoPAlmeida** [comment]
Given that you are using the Xcode 10.2, and this property is available on iOS 13 SDK that comes with Xcode 11, this is expected. Have you try to compile it with Xcode 11?

**Comment by hamza-farooq-astutesol** [comment]
I should have known that. My bad. Yes it working fine now. Thank you very much.
