### ISSUE TITLE
access conflict 

### ISSUE THREAD

**Issue by tospery** [SwifterSwift/SwifterSwift#768]
When use the ManualLayout library, the view's x/y/width/height is conflict. and without origin/size/center/centerX/centerY.
https://github.com/isair/ManualLayout

**Comment by LucianoPAlmeida** [comment]
Hey @tospery :)
I viable solution to that is to do adjust your imports in a way to disambiguate the use of the properties. Meaning, you choose one `ManualLayout` or `SwifterSwift` and add the specific import to get rid of the naming symbol conflict.
Example:
```swift
import var SwifterSwift.height
```
For more information, see the discussion on #645
