### ISSUE TITLE
New CLLocation (and others) functions

### ISSUE THREAD

**Issue by furiosFast** [SwifterSwift/SwifterSwift#770]
Hi,
first of all, great job, congratulations!
I discovered this repository at the swiftcoin of turin and I have already implemented it in all my projects.
I wanted to ask you if I can recommend some new works to integrate with Swifter Swift that I think could be useful as well as me to other programmers as well

Thanks

**Comment by LucianoPAlmeida** [comment]
Hi @furiosFast :))

> I wanted to ask you if I can recommend some new works to integrate with Swifter Swift that I think could be useful as well as me to other programmers as well
> 

For sure, feel free to submit new ideas as issues or even Pull requests with implementation if you like :) 
We are always open to discuss things that can move this project forward \o/

**Comment by LucianoPAlmeida** [comment]
Just closing this because it is neither a discussion or an actual issue of the project 
But feel free to bring on the new ideas :))
