### ISSUE TITLE
Upgrade iOS minimum deployment target dependency for the project

### ISSUE THREAD

**Issue by LucianoPAlmeida** [SwifterSwift/SwifterSwift#794]
Current our minimum deployment target for iOS 8.0, and we want to upgrade it to iOS 10.0 
To do that we need to change it in the project and also make sure the Podspec and documentation e.g. readme is updated too.

**Comment by trevorphillips** [comment]
#800

**Comment by LucianoPAlmeida** [comment]
Thank you :)
