### ISSUE TITLE
url safe base64 encoding and decoding

### ISSUE THREAD

**Issue by pynixwang** [SwifterSwift/SwifterSwift#795]
### What did you do?
> decode url safe base64 (base62) string

### What did you expect to happen?
> decode it

### What happened instead?
> return nil

### SwifterSwift Environment

- SwifterSwift version: latest
- Xcode version: 11
- macOS version running Xcode: 10.15
- Swift version: 5.1
- Platform(s) running SwifterSwift: macOS

### Demo Project
>Please link to or upload a project we can download that reproduces the issue.

**Comment by omaralbeik** [comment]
@pynixwang Thanks for bringing this!
Could you please share more information, I'm not sure I understand the issue

**Comment by pynixwang** [comment]
url safe base64 decoding.

**Comment by DimaZava** [comment]
@pynixwang Can you please provide sample project contains data and operation which fails

**Comment by pynixwang** [comment]
@DimaZava @omaralbeik 
```
let s = "aHR0cDovL2V4YW1wbGUuY29tL3h4eA"
print(s.base64Decoded)  // => nil
```

**Comment by pynixwang** [comment]
some padding char is removed

**Comment by pynixwang** [comment]
but ruby can decode it
```
Base64.urlsafe_decode64 "aHR0cDovL2V4YW1wbGUuY29tL3h4eA" # => "http://example.com/xxx"
```

**Comment by trevorphillips** [comment]
@pynixwang 
Encoding `http://example.com/xxx` -> `aHR0cDovL2V4YW1wbGUuY29tL3h4eA==`
Seems that trying to decode `aHR0cDovL2V4YW1wbGUuY29tL3h4eA` doesn't work in swift because it doesn't include those extra `==` at the end.

**Comment by LucianoPAlmeida** [comment]
Thank you @pynixwang and @trevorphillips 
The PR referenced above just fixes that \o/
