### ISSUE TITLE
WKWebView extensions

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#802]
I noticed we don't have any extensions for `WKWebView` 🤔, please use this issue to brainstorm ideas for useful extensions to evaluate javascript, get the view height, and more ...

**Comment by hamtiko** [comment]
@omaralbeik I think it is good to start to copy old `UIWebView` `loadURL(_:)` and `loadURLString(_:)` extensions and update them to work with `WKWebView`.

I have created a https://github.com/SwifterSwift/SwifterSwift/pull/851 PR  for this, could you please check and give your thoughts.

Thanks.
