### ISSUE TITLE
watchOS support

### ISSUE THREAD

**Issue by omaralbeik** [SwifterSwift/SwifterSwift#81]

**Comment by omaralbeik** [comment]
@pawurb Could you help please.

**Comment by pawurb** [comment]
Sure, will look into it. AFAIK testing watchOS is not as straightforward because out of the box it does not support test targets, but alamofire does it somehow so will try to copy their approach.

**Comment by omaralbeik** [comment]
@pawurb That would be great, thank you!

**Comment by omaralbeik** [comment]
@pawurb watchOS support added in v1.4.6, thanks for the great work!
