### ISSUE TITLE
String Safely subscript - out of bounds

### ISSUE THREAD

**Issue by Raber93** [SwifterSwift/SwifterSwift#815]
> Please fill out this template when filing an issue.
>
> All comment lines beginning with an **>** instruct you with what info we expect. You can delete those lines once you've filled in the info.
>

[ ] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
> Used safely subscript string within a closed range: "A"[safe: 0...1]?? "" 

### What did you expect to happen?
> Expected nil

### What happened instead?
> PIt crashed with: "Fatal error: index is out of bounds"

### SwifterSwift Environment

- SwifterSwift version: 5.1
- Xcode version: 11.3.1
- macOS version running Xcode: 10.15.3
- Swift version: 5.1
- Platform(s) running SwifterSwift:

### Demo Project
>Please link to or upload a project we can download that reproduces the issue.

**Comment by LucianoPAlmeida** [comment]
This seems like a very simple detail in the implementation, I would say it is an easy fix ... PR's are welcome :))  

If someone wants to jump in the file where these subscripts are is `SwiftStdlib/StringExtensions.swift` :))

**Comment by LucianoPAlmeida** [comment]
And @Raber93 Thank you for reporting :)

**Comment by LucianoPAlmeida** [comment]
Fixed on master @Raber93 \o/
