### ISSUE TITLE
ambiguous use of localizedPrice

### ISSUE THREAD

**Issue by canaksoy** [SwifterSwift/SwifterSwift#828]
product.localizedPrice gives "ambiguous use of" error when pod using with https://github.com/bizz84/SwiftyStoreKit 

### SwifterSwift Environment

- SwifterSwift version: 5.2.0
- Xcode version: 11.3.1
- macOS version running Xcode:
- Swift version: 4.2
- Platform(s) running SwifterSwift: iOS

**Comment by guykogus** [comment]
We actually had a discussion about dealing with these kinds of issues in https://github.com/SwifterSwift/SwifterSwift/issues/645. Can you try implement the suggested specific imports in https://nshipster.com/import/ and let us know if it works?
Thanks

**Comment by LucianoPAlmeida** [comment]
Closing, Thanks @canaksoy @guykogus :)
