### ISSUE TITLE
NSAttributedString make `applying(attributes:)` public

### ISSUE THREAD

**Issue by joeljfischer** [SwifterSwift/SwifterSwift#831]
[x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
Attempted to use `NSAttributedString.applying` to the whole string, but the method to do so (without specifying a part of the string) is `fileprivate`.

### What did you expect to happen?
The method to be public

### What happened instead?
The method was not available

### SwifterSwift Environment

- SwifterSwift version: 5.2.0
- Xcode version: n/a
- macOS version running Xcode: n/a
- Swift version: n/a
- Platform(s) running SwifterSwift: n/a

### Demo Project
n/a

**Comment by LucianoPAlmeida** [comment]
Humm, I see ... thanks for reporting @joeljfischer :)
I'm not sure if the intention of this method was to be public but I think there is no harm in doing that since it could be useful.

**Comment by LucianoPAlmeida** [comment]
If anyone wants to take this here is the method https://github.com/SwifterSwift/SwifterSwift/blob/e81ec9d666f7aef3ebc70cb88fced3df72e1e9a0/Sources/SwifterSwift/Foundation/NSAttributedStringExtensions.swift#L69
