### ISSUE TITLE
Project failed to compile because of lint errors

### ISSUE THREAD

**Issue by spicymatt** [SwifterSwift/SwifterSwift#833]
[X ] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
Run carthage update on a projet referencing SwifterSwift

### What did you expect to happen?
Project should compile

### What happened instead?
Project failed to compile because of lint errors in the macOS test cases

I open the project checked-out by Carthage and failed to compile it because of lint related errors:
Variable name should only contain alphanumeric characters: e.g __allTests__CalendarExtensionTests
Variable name should only contain alphanumeric characters: '__allTests__DateExtensionsTests' (identifier_name)
etc...
33 errors in total, all in the test package

I'm not terribly familiar with swiftlint, but I understand that the .yml that is at the root of the checked-out project takes precedence over any other configuration so I don't really see how to make it compile out of the box because those lint parameters from the project will be used.

### SwifterSwift Environment

- SwifterSwift version: 5.2
- Xcode version: 11.2
- macOS version running Xcode: 10.14
- Swift version: 5
- Platform(s) running SwifterSwift: MacOS

**Comment by LucianoPAlmeida** [comment]
Thanks for reporting, that's weird because all those files were removed in #808 ... So if you are using the latest version it shouldn't be a problem, anyways we can investigate that :)

**Comment by spicymatt** [comment]
hello,
Thanks for responding...and finding the solution.
For some reason, I had to delete the Carthage/ folder and redo the `carthage update --platform macOS  --no-use-binaries` to make it work. I was using 5.1 before the first attempt, and for some reason, the Carthage checkout was not reflecting the change you mention.
I should have tried to cleanup Carthage/ before asking but I never had to do it before.
Thanks anyway.
Matthieu

**Comment by LucianoPAlmeida** [comment]
Right, maybe it is some Carthage caching/update problem, not really sure ... but glad you make it work :) 
Closing 👍
