### ISSUE TITLE
set/object method of UserDefaults for Codable is not working for date objects

### ISSUE THREAD

**Issue by hassan31** [SwifterSwift/SwifterSwift#839]
> Please fill out this template when filing an issue.
>
> All comment lines beginning with an **>** instruct you with what info we expect. You can delete those lines once you've filled in the info.
>

[ ] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
> When I add date object in Codable Object 
```
struct TestObject: Codable {
    var itemId: Int
    var firstName: String?
    var lastName: String
    var dob: Date?
}
```
```
let key = "codableTestKey"
let codable = TestObject(itemId: 1, firstName: nil, lastName: "Joe", dob: nil)
UserDefaults.standard.set(object: codable, forKey: key)
let retrievedCodable = UserDefaults.standard.object(TestObject.self, with: key)
```

### What did you expect to happen?
> If I add date object in Codable object, it should work as expected. It should not be nil.

### What happened instead?
> After retrieving the Codable object, retrievedCodable is nil due to date object

### SwifterSwift Environment

- SwifterSwift version:
- Xcode version: 11.4.1
- macOS version running Xcode:
- Swift version: 5.2
- Platform(s) running SwifterSwift:

### Demo Project
> Please look into attached screenshot, I've used your unit test of UserDefaultsExtension
<img width="1154" alt="Screen Shot 2020-05-07 at 12 48 34 AM" src="https://user-images.githubusercontent.com/3063382/81255813-ab7f5200-8ffc-11ea-9733-ff74b68f8276.png">

**Comment by guykogus** [comment]
@hassan31 this is a bug in Xcode. If you type `po retrievedCodable.date` it will print out the correct value. For some reason the Variables View isn't showing the date correctly.

**Comment by hassan31** [comment]
@guykogus awesome, thanks a lot, it saved my a lot of time by saving user's information in Userdefaults one by one.
