### ISSUE TITLE
UIImage.rotated(by:) should use UIGraphicsBeginImageContextWithOptions rather than UIGraphicsBeginImageContext

### ISSUE THREAD

**Issue by miku1958** [SwifterSwift/SwifterSwift#840]
[ ] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
> rotate UIImage

### What did you expect to happen?
> the same image but rotated

### What happened instead?
> I get a blur image, and I look up the newest code 
https://github.com/SwifterSwift/SwifterSwift/blob/a50de462dba6a65e86f0ed9140327b43b8c26fb0/Sources/SwifterSwift/UIKit/UIImageExtensions.swift#L118
https://github.com/SwifterSwift/SwifterSwift/blob/a50de462dba6a65e86f0ed9140327b43b8c26fb0/Sources/SwifterSwift/UIKit/UIImageExtensions.swift#L148
it still wrong, you should use :
UIGraphicsBeginImageContextWithOptions(roundedDestRect.size, false, 0)

### SwifterSwift Environment

- SwifterSwift version: 5.0.0
- Xcode version:
- macOS version running Xcode:
- Swift version:
- Platform(s) running SwifterSwift:

### Demo Project
>Please link to or upload a project we can download that reproduces the issue.

**Comment by LucianoPAlmeida** [comment]
I think since we upgrade the minimum deployment target for this project to iOS 10.0, it would be a good thing to update those methods to use `UIGraphicsImageRenderer` API's instead...

**Comment by guykogus** [comment]
Solved by #904
