### ISSUE TITLE
Add Date.toGlobalTime() and Date.toLocalTime()

### ISSUE THREAD

**Issue by abdurrehmanio** [SwifterSwift/SwifterSwift#847]
extension Date {
    
    // Convert local time to UTC (or GMT)
    func toGlobalTime() -> Date {
        let timezone = TimeZone.current
        let seconds = -TimeInterval(timezone.secondsFromGMT(for: self))
        return Date(timeInterval: seconds, since: self)
    }
    
    // Convert UTC (or GMT) to local time
    func toLocalTime() -> Date {
        let timezone = TimeZone.current
        let seconds = TimeInterval(timezone.secondsFromGMT(for: self))
        return Date(timeInterval: seconds, since: self)
    }
    
}

**Comment by chulbert** [comment]
These methods do not do what you think they do.  Date objects exist independent of time zone or calendar.  They are not “in” a time zone so they cannot be converted to/from.

**Comment by LucianoPAlmeida** [comment]
I think @chulbert is right, the `Date` objects do not have timezone information. 
Timezone information is more commonly used on Date formatters to present it to the user :)

**Comment by LucianoPAlmeida** [comment]
Closing, feel free to re-open if you still want to discuss this :)

**Comment by abdurrehmanio** [comment]
> These methods do not do what you think they do. Date objects exist independent of time zone or calendar. They are not “in” a time zone so they cannot be converted to/from.

I'm using this extension in a project recently to solve the issue of DateTime mismatch based on the user's timezone and its working perfectly as I intended. So thought of requesting this to be added in SwifterSwift. 

For example: consider server is saving time in UTC. By default when we show that date-time in App, it been shown what we get in API. But it shows the wrong time for users of different timezones. So this extension will help to convert API date-time to local, and while sending any date time, user can send them based on UTC.

**Comment by LucianoPAlmeida** [comment]
> So thought of requesting this to be added in SwifterSwift.

Thanks for the suggestion @abdurrehmanio 💯 

> But it shows the wrong time for users of different timezones. So this extension will help to convert API date-time to local, and while sending any date time, user can send them based on UTC.

The point is exactly this, is that this logic shouldn't be modify the date object based on a timezone, but IMHO it should be on your date formatter where you ensure to use the timezone to present the correct date for the users :)
