### ISSUE TITLE
Project build failed

### ISSUE THREAD

**Issue by ganweiming** [SwifterSwift/SwifterSwift#848]
> Please fill out this template when filing an issue.
>
> All comment lines beginning with an **>** instruct you with what info we expect. You can delete those lines once you've filled in the info.
>

[ ] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
i clone a project from git the project build success, but when i delete an Controller.swift file or folder, then build failed

### What did you expect to happen?
![45C627281C73E37B13438570B3224640](https://user-images.githubusercontent.com/18005096/82541134-8fde8480-9b82-11ea-8a45-3c08baa8ae82.png)
![A75A2EFF4A4B8AEB9C5DE08A98DE169D](https://user-images.githubusercontent.com/18005096/82541159-966cfc00-9b82-11ea-8c3c-6aab24d874b9.png)

### SwifterSwift Environment

- SwifterSwift version: 5.1.0
- Xcode version:11.5
- macOS version running Xcode:10.15.4
- Swift version:5.0
- Platform(s) running SwifterSwift:13.5

### Demo Project
>Please link to or upload a project we can download that reproduces the issue.

**Comment by guykogus** [comment]
Are you calling `import SwifterSwift` in those files?

**Comment by ganweiming** [comment]
sry i didn't, but why can i build success before i delete files and i didn't import in many way, i just wanna know about it, thanks so much
