### ISSUE TITLE
UIImage.filled(withColor: ) missing clip mask above iOS10

### ISSUE THREAD

**Issue by miku1958** [SwifterSwift/SwifterSwift#849]
[current code](https://github.com/SwifterSwift/SwifterSwift/blob/a50de462dba6a65e86f0ed9140327b43b8c26fb0/Sources/SwifterSwift/UIKit/UIImageExtensions.swift#L170)
```
        #if !os(watchOS)
        if #available(tvOS 10.0, *) {
            let format = UIGraphicsImageRendererFormat()
            format.scale = scale
            let renderer = UIGraphicsImageRenderer(size: size, format: format)
            return renderer.image { context in
                color.setFill()
                context.fill(CGRect(origin: .zero, size: size))
            }
        }
        #endif
```
just render a color to image
it should  add 
```
context.cgContext.clip(to: rect, mask: mask)
```
before color.setFill()

and also, the result after using UIGraphicsImageRenderer is different from old version, the old version is fliped vertically

**Comment by LucianoPAlmeida** [comment]
Thanks for reporting @miku1958
