### ISSUE TITLE
Fix travis tests

### ISSUE THREAD

**Issue by pawurb** [SwifterSwift/SwifterSwift#85]
Currently build is displayed as passing but looking at the travis logs https://travis-ci.org/omaralbeik/SwifterSwift tests are not executing. Looks like the following commit broke travis config: https://github.com/SwifterSwift/SwifterSwift/commit/e1d7bc4c65e81fd299e99af37b6f1157fc110a4c

**Comment by omaralbeik** [comment]
@pawurb I needed to grant Travis access to repo again since I moved the project repo from my personal account to the "SwifterSwift" organization account.

https://travis-ci.org/SwifterSwift/SwifterSwift
```
Executed 129 tests, with 0 failures (0 unexpected) in 0.170 (0.304) seconds
```
Thank you!
