### ISSUE TITLE
Request add the calculate text size method to UILabel

### ISSUE THREAD

**Issue by tospery** [SwifterSwift/SwifterSwift#850]
Hope the UILabelExtensions can add the method, that support to calculate text size.
Like TTTAttributedLabel's sizeThatFitsAttributedString:withConstraints:limitedToNumberOfLines function

**Comment by daliadanila** [comment]
@tospery you mean something like this?

let string = //some long string

let attributes = [NSAttributedString.Key.foregroundColor: UIColor.red, NSAttributedString.Key.font: UIFont.boldSystemFont(ofSize: 16) ]

let attributedString = NSAttributedString(string: string, attributes: attributes)

let label = UILabel()

label.numberOfLines = 20

label.attributedText = attributedString

let singleLineSize = UILabel.size(thatFitsAttributedString: attributedString, withConstraints: CGSize(width: 100, height: CGFloat.greatestFiniteMagnitude))

label.backgroundColor = UIColor.white

label.frame = CGRect.init(x: 0, y: 0, width: singleLineSize.width, height: singleLineSize.height)

let testView = UIView.init(frame: CGRect.init(x: 0, y: 0, width: 500, height: singleLineSize.height))

testView.backgroundColor = UIColor.blue

testView.addSubview(label)

<img width="512" alt="Screenshot 2020-05-27 at 15 53 44" src="https://user-images.githubusercontent.com/4118291/83036228-4387be80-a032-11ea-88ca-b3014530f2ec.png">

**Comment by tospery** [comment]
Yes, I mean that

**Comment by daliadanila** [comment]
@tospery cool, I’ll make a PR shortly

**Comment by tospery** [comment]
I think it's better to pass in UILabel's numberOfLines with the limitedToNumberOfLines parameter of the method

**Comment by tospery** [comment]
You can refer to the realization of the OC version: https://github.com/TTTAttributedLabel/TTTAttributedLabel/blob/master/TTTAttributedLabel/TTTAttributedLabel.m（TTTAttributedLabel->sizeThatFitsAttributedString:withConstraints:limitedToNumberOfLines）

**Comment by daliadanila** [comment]
I had a look, but there doesn't seem to be an equivalent in Swift for `CTFramesetterSuggestFrameSizeForAttributedStringWithConstraints` or a similar method in CT that receives the number of lines.

**Comment by tospery** [comment]
CTFramesetterSuggestFrameSizeForAttributedStringWithConstraints is not a system method, you can see its implementation

**Comment by LucianoPAlmeida** [comment]
@tospery We move this discussion to #853
