### ISSUE TITLE
Make CAGradientLayerExtensions public.

### ISSUE THREAD

**Issue by denandreychuk** [SwifterSwift/SwifterSwift#855]
For now, its has internal access level and do not accessible.

**Comment by LucianoPAlmeida** [comment]
Thank you for reporting @denandreychuk :) 
If the problem is just making it public, that's a good first issue if someone wants to give it a try.

**Comment by denandreychuk** [comment]
https://github.com/SwifterSwift/SwifterSwift/pull/856
