### ISSUE TITLE
Remove `map(by:)`, `compactMap(by:)` and `filter(by:)` for Swift 5.2

### ISSUE THREAD

**Issue by RomanPodymov** [SwifterSwift/SwifterSwift#861]
🚀
- [x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
I run tests for **SwifterSwift-macOS**.

### What did you expect to happen?
Instead of `map(by:)`, `compactMap(by:)` and `filter(by:)` there should be `map()`, `compactMap()` and `filter()` with KeyPaths as functions.

### What happened instead?
`map(by:)`, `compactMap(by:)` and `filter(by:)` are using.

### SwifterSwift Environment

- SwifterSwift version: 5.2.0
- Xcode version: 11.5
- macOS version running Xcode: 10.15.5
- Swift version: 5.2
- Platform(s) running SwifterSwift: macOS

**Comment by LucianoPAlmeida** [comment]
Those indeed could be deprecated, thanks for reporting @RomanPodymov :)
