### ISSUE TITLE
UITextField addPaddingLeftIcon doesn't work on iOS 13

### ISSUE THREAD

**Issue by Jayxiang** [SwifterSwift/SwifterSwift#876]
### I use addPaddingLeftIcon in extension UITextField
e.g.
```
textField.addPaddingLeftIcon(image, padding: 30)
```
below iOS 13
<img width="194" alt="iOS12" src="https://user-images.githubusercontent.com/12928482/87008049-bd949100-c1f5-11ea-862e-31b2e9153bc7.png">
above iOS 13
<img width="207" alt="iOS13" src="https://user-images.githubusercontent.com/12928482/87008115-d7ce6f00-c1f5-11ea-91f4-007689a7a64d.png">

Similar issues: [stackoverflow](https://stackoverflow.com/questions/58166160/ios-13-spacing-issue-with-uitextfield-rightview)

So I wrap it in a plain UIView

**Comment by moKelani** [comment]
you can change right padding and left padding from the extension which I made
...........
you can use IBDesignable or not as you see
@IBDesignable
extension UITextField {
    
    @IBInspectable var paddingLeftCustom: CGFloat {
        get {
            return leftView!.frame.size.width
        }
        set {
            let paddingView = UIView(frame: CGRect(x: 0, y: 0, width: newValue, height: frame.size.height))
            if leftView == nil {
                leftView = paddingView
                leftViewMode = .always
            }
            
        }
    }

    @IBInspectable var paddingRightCustom: CGFloat {
        get {
            return rightView!.frame.size.width
        }
        set {
            let paddingView = UIView(frame: CGRect(x: 0, y: 0, width: newValue, height: frame.size.height))
            if rightView == nil {
                rightView = paddingView
                rightViewMode = .always
            }
            
        }
    }
}
