### ISSUE TITLE
want more helpers?

### ISSUE THREAD

**Issue by gurgeous** [SwifterSwift/SwifterSwift#879]
Thanks for creating such a great library! SwifterSwift is amazing and helped me get rid of many of our custom extensions. Want a few more? Here are additional helpers that I can add if you want:

- CGFloat.random
- CGRect x, y, width, height, center, centerX, centerY, left, top, right, bottom
- CGSize init(square: CGFloat)
- String escapeRegex
- UIColor image(ofSize: CGSize)
- UIImage averageColor

### UIView
- loadFromNib(withClass name: T.Type)
- frame - origin, width, height, size, top, left, bottom, right
- bounds - boundsWidth, boundsHeight, boundsSize
- constraints - allConstraints, findConstraint(attribute: NSLayoutConstraint.Attribute), widthConstraint, heightConstraint, leadingConstraint, trailingConstraint, topConstraint, bottomConstraint
^ these are for finding existing constraints and are typically used to modify a constant

Let me know if any of these are of interest and I'll put together a PR.

(I also have a fair number of NSRegularExpression, NSString and NSMutableAttributedString extensions but I think those are of less interest. Let me know if you'd like to see those too.)

**Comment by guykogus** [comment]
> * CGFloat.random **- Part of the standard library**
> * CGRect x, y, width, height, center, centerX, centerY, left, top, right, bottom **- already have min/mid/max(X/Y) etc**
> * CGSize init(square: CGFloat) **- Not a huge saving, IMO**
> * String escapeRegex **- 👍**
> * UIColor image(ofSize: CGSize) **- what's the benefit of this?**
> * UIImage averageColor **- could be interesting**
> 
> ### UIView
> * loadFromNib(withClass name: T.Type) **- Good idea, for now we just have it returning `UIView`**
> * frame - origin, width, height, size, top, left, bottom, right **- Same as with `CGRect`, no need**
> * bounds - boundsWidth, boundsHeight, boundsSize **- not much of a benefit here calling `boundsWidth` instead of `bounds.width`, for example**
> * constraints - allConstraints, findConstraint(attribute: NSLayoutConstraint.Attribute), widthConstraint, heightConstraint, leadingConstraint, trailingConstraint, topConstraint, bottomConstraint **- 👍**
>   ^ these are for finding existing constraints and are typically used to modify a constant
> 
> (I also have a fair number of NSRegularExpression, NSString and NSMutableAttributedString extensions but I think those are of less interest. Let me know if you'd like to see those too.) **- If you have anything here that we don't have already please feel free to share**

**Comment by gurgeous** [comment]
Great! A few more comments:

- UIColor.image(ofSize), creates a UIImage filled with a particular color. Handy for programmatic UI and testing purposes.
- UIImage.averageColor, calculates the average color of a UIImage. This is useful for creating background images. In my current project I use this to figure out if the status bar style should be light or dark over a photo.

Here's what I've got for the other classes:

### NSRegularExpression
- versions of enumerateMatches, matches, numberOfMatches, firstMatch, rangeOfFirstMatch, stringByReplacingMatches, replaceMatches that operate on the entire string (no range required)

### String
- stringByReplacingMatches(regex, withTemplate) and stringByReplacingMatches(pattern, withTemplate), which call into NSRegularExpression
- squished, which compacts all whitespace and trims

### NSAttributedString/NSMutableAttributedString/String

- NSAttributedString.withAttribute/withAttributes, same as `applying`. Probably we should just make `applying` public and support the singular case as well.
- NSAttributedString.font & link, similar to `color`
- NSMutableAttributedString.append(string)
- NSMutableAttributedString.addAttribute & addAttributes that operate on the entire string (no range required)
- String.withAttribute/withAttributes, same as above
- String.font/link/color, same as above

The intent here is to make NSAttributedString, NSMutableAttributedString and String all work together to support attributed properties. I don't know how anyone can build attributed text without this stuff. Example usage:

```swift
var s = NSMutableAttributedString()
s.append("\(count) ".font(Self.countFont))
s.append(label.font(Self.labelFont))
s.color(.red)
```

**Comment by gurgeous** [comment]
Here is a WIP for the first set of additions: https://github.com/SwifterSwift/SwifterSwift/compare/master...gurgeous:more-extensions?expand=1

Feedback is welcome. Let me know if this looks good and I will submit a PR w/ changelog entries. Thanks @guykogus!

**Comment by LucianoPAlmeida** [comment]
@gurgeous Just one note, make sure to open one PR per extension, this makes easier o discuss a single topic in a PR and also for review :)

**Comment by gurgeous** [comment]
OK, I will break this up into a few PRs and add changelog entries

**Comment by LucianoPAlmeida** [comment]
> OK, I will break this up into a few PRs and add changelog entries

Thank you! We will take a look at it ASAP :)

**Comment by gurgeous** [comment]
I'll go ahead and close this. We can explore the additional helpers listed above in separate issues if we want.
