### ISSUE TITLE
UIImage rotated changes the size of the original image

### ISSUE THREAD

**Issue by cyber-gh** [SwifterSwift/SwifterSwift#881]
[ ] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

This is more like a suggestion, not an issue

### What did you do?
Tried to use UIImage rotated(by angle: Measurement<UnitAngle>) on a round image

### What did you expect to happen?
The image to be rotated, preserving the original size

### What happened instead?
The image was rotated, but it was smaller than original

### SwifterSwift Environment

- SwifterSwift version: latest (just copy pasted from the github repo directly)
- Xcode version: 11
- macOS version running Xcode: Catalina
- Swift version: 5
- Platform(s) running SwifterSwift: 

From this file
https://github.com/SwifterSwift/SwifterSwift/blob/master/Sources/SwifterSwift/UIKit/UIImageExtensions.swift
`func rotated(by angle: Measurement<UnitAngle>) -> UIImage? `

It contains the following piece of code:
```
let roundedDestRect = CGRect(x: destRect.origin.x.rounded(),
                                     y: destRect.origin.y.rounded(),
                                     width: destRect.width.rounded(),
                                     height: destRect.height.rounded())

```
In order to preserve the original size, I have made the following modification:
```
let roundedDestRect = CGRect(x: destRect.origin.x.rounded(),
                y: destRect.origin.y.rounded(),
                width: self.size.width,
                height: self.size.height)
```
To be honest, I'm not sure why the size is being changed, maybe there is a reason for it.

What I'm trying to say, maybe we could add an additional parameter,` preserverOriginalSize: Bool = false`

**Comment by LucianoPAlmeida** [comment]
cc @guykogus

**Comment by cyber-gh** [comment]
I can take care of this

**Comment by LucianoPAlmeida** [comment]
> I can take care of this

Awesome! Thanks :)

**Comment by guykogus** [comment]
I think it makes sense for the image size to change if you rotate an image. Imagine you have a 10x20 point rectangle and you rotate it 90 degrees. Now it'll be 20x10. To maintain the exact same original size means to scale the image too, which is not the purpose of the function. If the caller wants to do that they can scale the image after rotating it themselves.
