### ISSUE TITLE
Tap

### ISSUE THREAD

**Issue by gurgeous** [SwifterSwift/SwifterSwift#882]
Another idea for consideration. Have you seen this pattern? https://github.com/devxoul/Then. We use this heavily in Ruby with `tap` and rely on it for our Swift project too. Would be nice to pull this into SwifterSwift since it's so simple and helpful. Example courtesy of the Then project:

### old

```swift
let label: UILabel = {
  let label = UILabel()
  label.textAlignment = .center
  label.textColor = .black
  label.text = "Hello, World!"
  return label
}()
```

### new

```swift
let label = UILabel().then {
  $0.textAlignment = .center
  $0.textColor = .black
  $0.text = "Hello, World!"
}
```

We use this pattern for subviews, autolayout with [Anchorage](https://github.com/Rightpoint/Anchorage), viewDidLoad setup, dependency injection, NSMutableAttributedString construction...

**Comment by omaralbeik** [comment]
Well, the of SwifterSwift, is that we don't add classes, structs, protocols, or any new types, instead try to extend already available types with small **modular** extensions that can be copy-pasted into any other project without having to add SwifterSwift as a dependency.
Adding `then`, will require adding a type, so I don't think it is suitable for this project

**Comment by gurgeous** [comment]
ok, thanks
