### ISSUE TITLE
swiftformat?

### ISSUE THREAD

**Issue by gurgeous** [SwifterSwift/SwifterSwift#887]
As long as I have some PRs hanging out there, here's another topic for discussion. Would you consider adopting [swiftformat](https://github.com/nicklockwood/SwiftFormat)? We use this quite happily in my current project alongside similar tools in (prettier, rubocop, etc).

Swiftformat would make it easier for newcomers (like me) to make contributions and not have to worry about whitespace/formatting issues. I spent a fair bit of time ironing out formatting issues for those PRs, unfortunately. I'm not familiar with Danger, but I imagine you could enforce via the Dangerfile and the PR checklist.

**Comment by omaralbeik** [comment]
Oh yeah I remember using Swiftformat for one project, that thing that prevents you from `cmd`+`z` every time it runs 😜

**Comment by gurgeous** [comment]
When we first added swiftformat to our project, we used an Xcode build phase. The behavior was as you described - no undo, Xcode getting confused between in-memory version and disk version, etc. We hated it.

We switched to a pre commit hook instead and those problems went away. Now we rely on it heavily. Not sure how best to add swiftformat here, but I'm sure there's a way if we are interested. For example, I think that the Firebase SDK just has a convention "please run this script" and verifies via CI.

**Comment by gurgeous** [comment]
Other examples we might look at - Alamofire, CryptoSwift, etc

**Comment by LucianoPAlmeida** [comment]
I like the idea of using git hooks for it ... I'm using recently a formating tool that I run manually after `git add` files. So a pre-commit hook would be a good way ... not sure how to set up because it requires to copy the script to `.git/hooks` we probably would have it as a session describing how to do it in the readme

**Comment by gurgeous** [comment]
The nice thing about swiftformat is that it doesn't break anything if people fail to run the tool. Alamofire has the config but no docs or enforcement. CryptoSwift has a dedicated (manual) script and a checkbox in the pull request template. Firebase has a CI check.

In terms of getting started, perhaps:

1. add `.swiftformat` (after discussion)
1. run `swiftformat`, which will create a large PR
1. encourage core devs to add [pre-commit hook](https://github.com/nicklockwood/SwiftFormat#git-pre-commit-hook) (optional)
1. tune `.swiftlint.yml` to exclude warnings fixed by swiftformat. for example, `trailing_whitespace` (optional)

Here are some sample configs from popular projects:

https://github.com/airbnb/swift/blob/master/resources/airbnb.swiftformat
https://github.com/Alamofire/Alamofire/blob/master/.swiftformat
https://github.com/krzyzanowskim/CryptoSwift/blob/master/.swiftformat
https://github.com/firebase/firebase-ios-sdk/blob/master/scripts/style.sh#L87
https://github.com/kareman/SwiftShell/blob/master/.swiftformat
https://github.com/fastlane/fastlane/blob/master/fastlane/swift/formatting/.swiftformat

In my app we use a relatively simple config:

```
--exclude Carthage,Generated,Vendor
--header "{file} - Copyright {year} XXXXXX"
--maxwidth 120
```

**Comment by omaralbeik** [comment]
Nice, I like the idea!
![nice](https://media.giphy.com/media/yyZRSvISN1vvW/giphy.gif)

**Comment by LucianoPAlmeida** [comment]
I just did a test to know how this works and never used it, running it on the project with Alamofire rules ... there was 204/210 files modified, most of then imports alphabetically and line breaks ... I did see some indentation but were few because normally Xcode already does that for us. I still think is a good idea... just didn't see the large gain using it. 
One question @gurgeous since you use it
* There is a rule to limit the max columns per line like [clang-format ColumnLimit](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)? Like a line can't be than 80 and formatting accordingly?

**Comment by gurgeous** [comment]
With these formatting tools, the actual rules are less important than just having the tool turned on. Autoformatting sidesteps many issues for contributors since we don't have to discuss formatting anymore. I don't have a strong opinion about the formatting rules since I'm new to the project. Personally I'd mostly use the defaults in swiftformat unless someone feels strongly about a particular style choice.

@LucianoPAlmeida, as you surmised `maxwidth` is the max line width. I am not familiar with clang's ColumnLimit but I assume it's similar. Swiftformat will wrap comments and jump through hoops when calling long functions with many arguments. Personally I like that nice and wide but I have no preference. I believe the default is "don't wrap", so I'd recommend we set something here - 80, 100 or 120. :)

See https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md

**Comment by gurgeous** [comment]
I'd be happy to get the ball rolling if there are no objections. I'd propose a simple config, nearly default:

```
--header "{file} - Copyright {year} SwifterSwift"
--maxwidth 120
```

Questions:

1. Any other thoughts on rules? Personally I like default for simplicity, but I really have no opinion.
1. I like --header. Are we fine with that text?
1. Any swift files that should be excluded? Typically - generated files, 3rd party, etc.
1. Where should I put the pre-commit script for committers? I would use `bin/` but since we don't have that, maybe I'll leave it in the root directory. It will include install instructions.

**Comment by LucianoPAlmeida** [comment]
> 1. Any other thoughts on rules? Personally I like default for simplicity, but I really have no opinion.

I'd like to enforce those
```
--closingparen same-line
--commas inline
--comments indent
--ifdef no-indent
--importgrouping testable-top
```

> 2. I like --header. Are we fine with that text?

It's fine by me 

> 3. Any swift files that should be excluded? Typically - generated files, 3rd party, etc.

Not that I can remember

> 4. Where should I put the pre-commit script for committers? I would use bin/ but since we don't have that, maybe I'll leave it in the root directory. It will include install instructions.

if you are talking about an `.sh` file we can consider a folder called `scripts`

**Comment by gurgeous** [comment]
I think `--comments` is deprecated:

```
$ swiftformat --comments indent
warning: --comments option is deprecated. Relative indent within multiline comments is now preserved by default.
```

Rest looks fine to me!

**Comment by gurgeous** [comment]
Here's a branch to consider. I ran swiftformat and didn't make any further changes:

https://github.com/SwifterSwift/SwifterSwift/compare/master...gurgeous:swiftformat?w=1

Looks pretty good for a first pass. A few thoughts:

1. Long line wrapping broke some swiftlint:disables (replace with `swiftlint:disable:next`)
1. I think it broke URLExtensions.swift (exclude for now, report bug?)

If I fixed those two issues I'm pretty sure all tests would pass. Any more thoughts on the config now that we have something concrete to examine?

**Comment by gurgeous** [comment]
I reported the URLExtensions problem - https://github.com/nicklockwood/SwiftFormat/issues/698

**Comment by LucianoPAlmeida** [comment]
Looks promising, I think it would be nice to put up a PR for those changes :)

**Comment by gurgeous** [comment]
OK, here it is. BTW, Nick already fixed the issue I reported. Should be released soon. In my PR I manually reordered that import so the bug is no longer triggered.
