### ISSUE TITLE
proposed NSAttributedString and related extensions

### ISSUE THREAD

**Issue by gurgeous** [SwifterSwift/SwifterSwift#899]
I am using NSAttributedString and friends quite heavily in my current project. The current stuff in SwifterSwift is a fine start, but insufficient for serious usage in my opinion. I propose adding the following (see below). A few questions:

1. Is this worthwhile? Do you agree?
1. `colored` should return a @discardableResult, for chaining.
1. Naming: It's a shame that `applying` deviated from the `addAttribute` naming convention established in NSAttributedString. It might be better to rename `applying` to `withAttribute`. The `apply` function proposed for NSMutableAttributedString below would no longer be necessary.
1. Naming: The word `colored` is unfortunately an ethnic slur in the US. A nicer name would be `textColor`, `color`, or `foregroundColor` to match the proposed `font/link/paragraphStyle` functions. This would be a good time to make this trivial change.
1. Not really a question, but I'm a bit nervous about correctly implementing the `Linux` checks. I have no experience with that. Hopefully you guys will be patient with me.

### NSAttributedString

```swift
// like applying, but for a single attribute
func applying(name: NSAttributedString.Key, value: Any) -> NSAttributedString

@discardableResult func font(_ font: UIFont?) -> NSAttributedString
@discardableResult func link(_ link: URL?) -> NSAttributedString
@discardableResult func paragraphStyle(_ paragraphStyle: NSParagraphStyle?) -> NSAttributedString
```

### NSMutableAttributedString

```swift
// identical to addAttribute(s)
apply(_ name: NSAttributedString.Key, value: Any)
apply(_ attrs: [NSAttributedString.Key: Any] = [:])
```

### String

```swift
// same as NSAttributedString
func applying(attributes: [NSAttributedString.Key: Any]) -> NSAttributedString
func applying(name: NSAttributedString.Key, value: Any) -> NSAttributedString

@discardableResult func color(with color: Color) -> NSAttributedString
@discardableResult func font(_ font: UIFont?) -> NSAttributedString
@discardableResult func link(_ link: URL?) -> NSAttributedString
@discardableResult func paragraphStyle(_ paragraphStyle: NSParagraphStyle?) -> NSAttributedString
```

**Comment by guykogus** [comment]
2. I'm not sure why the functions have `@discardableResult`. If you discard the result then it's completely useless.

3. I also think that the naming should be consistent, e.g.
```Swift
func applying(font: UIFont?) -> NSAttributedString
func applying(link: URL?) -> NSAttributedString
func applying(paragraphStyle: NSParagraphStyle?) -> NSAttributedString
```
what do you think?

I've actually got a different way of approaching this in my project. E.g.

```Swift
extension NSAttributedString {
    var attributes: [Key: Any]? {
        guard !string.isEmpty else { return nil }
        return attributes(at: 0, effectiveRange: nil)
    }

    @objc var kern: CGFloat? { attributes?.kern }
}

extension NSMutableAttributedString {
    override var kern: CGFloat? {
        get { super.kern }
        set { replaceAttribute(.kern, value: NSNumber(value: Double(newValue))) }
    }
}
```

4. The use of `colored` is not necessarily problematic in this instance. The issue with terms like `blacklist`, for example, is that they subtly ingrain the idea that black is bad, which is why that term is being pushed out of technical jargon. Here we are setting the colour of text, to any possible colour, so we adequately use the verb "to colour" in its past participle form. It is not part of the problem with the negative associations created by other terminology because it does not perpetuate any racial stereotypes. Seeing the code `string.colored(.black)` is very different to seeing `blacklist.add(badUser)`.
Of course, these things are subjective, and I wouldn't worry just because there will always be somebody being oversensitive to anything, but if we receive any feedback that a person of colour is offended by this function then of course we should be open to changing it. I just don't personally believe that it makes sense to preempt it in this situation.

5. Don't worry about the Linux checks. We generally just wait to see the results of the CI Linux build and `#if` out anything that doesn't compile there 😅

**Comment by gurgeous** [comment]
OK, thanks. I like your idea of just calling them all `applying`. That would also be a good time to rename `colored`. 😄 I agree that this is a trivial issue, but possibly worth addressing as long as we are in there.

Re: NSAttributedString, NSMutableString, vars...

The current approach leads to code like:

```swift
var helloWorld: NSAttributedString? {
  let hello = "hello".applying(.red)
  let world = "world".applying(UIFont.boldSystemFont(ofSize: 12)
  return hello + " " + world  
}
```

With NSMutableAttributedString/vars, would that look more like:

```swift
var helloWorld: NSAttributedString? {
  let hello = NSMutableAttributedString(string: "hello")
  hello.color = .red
  let world = NSMutableAttributedString(string: "world")
  world.font = UIFont.boldSystemFont(ofSize: 12)
  return hello + " " + world  
}
```

The var version has a lot of appeal, but I probably prefer `applying` for brevity and chaining. Not totally sure, though. I could easily be swayed.

If we decide to proceed with applying, that would look like:

```swift
// NSAttributedString
func applying(attributes: [NSAttributedString.Key: Any]) -> NSAttributedString // we already have this
func applying(name: NSAttributedString.Key, value: Any) -> NSAttributedString
func applying(color: UIColor?) -> NSAttributedString
func applying(font: UIFont?) -> NSAttributedString
func applying(link: URL?) -> NSAttributedString
func applying(paragraphStyle: NSParagraphStyle?) -> NSAttributedString

// String
func applying(attributes: [NSAttributedString.Key: Any]) -> NSAttributedString // we already have this
func applying(name: NSAttributedString.Key, value: Any) -> NSAttributedString
func applying(color: UIColor?) -> NSAttributedString
func applying(font: UIFont?) -> NSAttributedString
func applying(link: URL?) -> NSAttributedString
func applying(paragraphStyle: NSParagraphStyle?) -> NSAttributedString
```

**Comment by guykogus** [comment]
Re: `colored`, the issue itself is not trivial and it's great that you're raising it and trying to deal with it. However, applying a broad stroke can be a sign of misunderstanding the nuances of the issue and can distract from the real problems. This is something I'd be happy to discuss in further detail in our Slack channel.

Re: NSAttributedString, I agree that the `var`s are really appealing for the mutable form, but it'd be more consistent to use `apply` to match `applying`.
Also, there's no need to duplicate the functions for `String`. The caller can create the original `NSAttributedString` themselves really easily, so it's overkill.

**Comment by gurgeous** [comment]
OK, let's start with NSAttributedString.applying and friends. I still think we should do String, because I am quite often doing things like:

```swift
var result = NSMutableAttributedString()
result += "greetings".localized().applying(font: .headerFont)
result += "friends".localized().applying(font: .bodyFont)
return result
```

without String extensions that would become:


```swift
var result = NSMutableAttributedString()
result += NSAttributedString(string: "greetings".localized()).applying(font: .headerFont)
result += NSAttributedString(string: "friends".localized()).applying(font: .bodyFont)
return result
```

I accept your decision either way, of course. 😄

**Comment by guykogus** [comment]
Now your suggestion makes a lot of sense. I likes it! I wonder if it's possible to make `NSAttributedString` conform to `ExpressibleByStringLiteral` to make this kind of magic happen automatically 🤔😄

**Comment by guykogus** [comment]
> Now your suggestion makes a lot of sense. I likes it! I wonder if it's possible to make `NSAttributedString` conform to `ExpressibleByStringLiteral` to make this kind of magic happen automatically 🤔😄

Nope, magic unavailable. Conforming to `ExpressibleByStringLiteral` can only be done within the class' module definition.

**Comment by gurgeous** [comment]
That would've been nice. Worth a shot!

**Comment by gurgeous** [comment]
Just to close the loop on this, should I put together the PR as outlined above? `applying` for both `NSAttributedString` and `String`

**Comment by guykogus** [comment]
@gurgeous yes please! :D

**Comment by gurgeous** [comment]
OK, a few questions before I begin, to save us all time:

1. In the method signatures above the parameters are optional. Is that useful/necessary? If we want to support optionals, what should a nil value do? Personally I think support for optionals is strictly a convenience, and the actual behavior is not that important.
1. Are we sticking to the "don't call other SwifterSwift method" rule here? I noticed that many existing NSAttributedString extensions (`bolded`) don't follow that rule. It might be moot since copypasters will have to handle `Font` vs `UIFont`, etc... It would save me some time here to call `applying` from `applying`.

**Comment by guykogus** [comment]
1. I assume it'll be fine to make it optional. You probably won't have to do any `if`-`else`s or anything, so go for it.
2. Unfortunately there are breakages of that rule, but I personally believe we should continue to enforce it for all new methods, even in this case where it can't be copy-pasted directly because of the `Font` `typealias`. It's a bit of a shame, but it's not a lot of extra code to implement.

**Comment by gurgeous** [comment]
Making progress. Questions around testing:

1. Some test cases have `#if canImport` on the inside, others have it on the outside. Which do we prefer?
1. I can picture a single test case for the various `applying` flavors (color/font/link/paragraphStyle). That would have some benefits for code clarity. Any objection to that style of testing? I tend to be less rigorous around testing in my projects.

The completionist in me wants to clean up these tests and make them uniform. Perhaps someday, once I understand the style a bit better...

**Comment by gurgeous** [comment]
footnote - let me know if this would be easier to discuss via slack. I would join the channel, but the links in the readme seem to be broken.

**Comment by gurgeous** [comment]
Bump - let me know if you have any suggestions, otherwise I'll move forward with a PR

**Comment by guykogus** [comment]
@gurgeous sorry that we never continued this conversation, I guess I got distracted and then this was forgotten. Any chance you'd want to continue with the PR?

**Comment by gurgeous** [comment]
Oh, no worries. I'm not doing much swift at the moment, feel free to close!
