### ISSUE TITLE
Normalize SCNVectors extension

### ISSUE THREAD

**Issue by thisIsTheFoxe** [SwifterSwift/SwifterSwift#907]
I recently worked a lot with SceneKit and SCNVectors.
Now, there is a neat `normalize()` func that works for SIMD vectors, but there is no such thing for SCNVectors directly, leading to **a lot** of conversions between SCNVec and SIMD.
Would be great to have something like:

```swift
let v = SCNVector3(10, 5, 7)
let vNorm = v.normalize()
```
Where `v` can be of arbitrary length and `vNorm` should always have a length of 1 ([Wiki](https://en.wikipedia.org/wiki/Unit_vector)).

Alternative would be `v.toUnitVector()` or something like `v.scale(to: 1)`.
Another approach would be to make length set-able and then modifying/scaling the vector accordingly like `v.length = 1`.
Lmk what you think..

**Comment by LucianoPAlmeida** [comment]
Seems legit to me! :)
