### ISSUE TITLE
Ambiguous use of 'cornerRadius'

### ISSUE THREAD

**Issue by RaulVan** [SwifterSwift/SwifterSwift#909]
1. Found this candidate (AuthenticationServices.ASAuthorizationAppleIDButton)
2. Found this candidate (SwifterSwift.UIView)

**Comment by yanpanpan** [comment]
you can quick fix this issue like below: `appleBtn.setValue(24, forKey: "cornerRadius")`. It's ugly, I cannot find out a better solution.

**Comment by guykogus** [comment]
Can you show your code? You can import specific structs/functions/etc. What imports do you have in that file? Are you using `ASAuthorizationAppleIDButton`?

**Comment by yanpanpan** [comment]
Yes, I face the same problem when using `ASAuthorizationAppleIDButton `.

**Comment by yanpanpan** [comment]
SomeViewController.swift

``` swift
import AuthenticationServices

class SomeViewController: UIViewController {
    func someFunc() {
        let appleBtn = ASAuthorizationAppleIDButton()
        appleBtn.cornerRadius = 5
    }
}
```
AnotherViewController.swift
```swift
import SwifterSwift
class AnotherViewController: UIViewController{}
```

This should reproduce the compiler error.

**Comment by Jayxiang** [comment]
Same as #622 , rename this? @LucianoPAlmeida

**Comment by LucianoPAlmeida** [comment]
@Jayxiang yeah, I think we don't have many options in this case besides renaming. For those layer wrapper properties insert a `layer` prefix should be good. But we should probably audit those computed properties in the library that are likely to have naming conflicts.

**Comment by jeanmartin** [comment]
Here is one more example: https://github.com/andreamazz/AMPopTip
In https://github.com/andreamazz/AMPopTip/blob/master/Source/PopTip.swift the attribute `borderWidth` is defined.
This attribute is inaccessible to me.

**Comment by CainLuo** [comment]
Here is also an example: https://github.com/ElaWorkshop/TagListView, the
https://github.com/ElaWorkshop/TagListView/blob/master/TagListView/TagView.swift, here is not able to access the cornerRadius, in order to prevent the same property conflict can not be used, whether the method name or property name to prevent the same property from being used in conflict, can we add a prefix to the method name or property name?
