### ISSUE TITLE
Add NSUbiquitousKeyValueStore.url(forKey:)

### ISSUE THREAD

**Issue by RomanPodymov** [SwifterSwift/SwifterSwift#910]
🚀
- [x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
I tried to call `NSUbiquitousKeyValueStore.url(forKey:)` because I know there is [UserDefault.url(forKey:)](https://developer.apple.com/documentation/foundation/userdefaults/1408648-url).

### What did you expect to happen?
I want to have this function in `NSUbiquitousKeyValueStore`.

### What happened instead?
Did not find this function.

### SwifterSwift Environment

- SwifterSwift version: 5.2.0
- Xcode version: 12.0.1
- macOS version running Xcode: 10.15.7
- Swift version: 5.3
- Platform(s) running SwifterSwift: iOS

### Demo Project
I want to have the following function:

```
if let url = NSUbiquitousKeyValueStore.default.url(forKey: "key") {
    print(url.absoluteString)
}
```

**Comment by edi-stern** [comment]
I tried to do that, it's my first contribution ever on open source project so don't judge it very hard

**Comment by LucianoPAlmeida** [comment]
> I tried to do that, it's my first contribution ever on open source project so don't judge it very hard

Welcome to the project!
Why are the PR's closed?

**Comment by edi-stern** [comment]
> > I tried to do that, it's my first contribution ever on open source project so don't judge it very hard
> 
> Welcome to the project!
> Why are the PR's closed?

I got CocoaPods (watchOS) job failed and the other ones on CocoaPods cancelled, and I tried to see what's the issue so I closed the PR

**Comment by LucianoPAlmeida** [comment]
The issue is probably because this class is not available for watchOS so we have to add an extra !os(WatchOS) ...

**Comment by edi-stern** [comment]
> The issue is probably because this class is not available for watchOS so we have to add an extra !os(WatchOS) ...

You were right. thanks for help
