### ISSUE TITLE
UIViewExtensions -> isRightToLeft

### ISSUE THREAD

**Issue by FunnyFzl** [SwifterSwift/SwifterSwift#923]
UIViewExtensions -> isRightToLeft
@available(iOS 10.0, *)
    open var effectiveUserInterfaceLayoutDirection: UIUserInterfaceLayoutDirection { get }
Not
tvOS 10.0

**Comment by LucianoPAlmeida** [comment]
Hi @FunnyFzl!
Thanks for reporting this =]
As far as doc goes https://developer.apple.com/documentation/uikit/uiview/1648536-effectiveuserinterfacelayoutdire 
It should be ios10+, tvos10+ or Mac Catalyst 13.0+ 

Its a very simple fix, so marking as good first issue

**Comment by cHaLkdusT** [comment]
Hi @LucianoPAlmeida, submitted a PR https://github.com/SwifterSwift/SwifterSwift/pull/924
