### ISSUE TITLE
Update ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by RomanPodymov** [SwifterSwift/SwifterSwift#925]
🚀

- [x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
I created a new issue at https://github.com/SwifterSwift/SwifterSwift/issues.

### What did you expect to happen?
I expected to see an issue with correct formatting after clicking on **Preview**.

### What happened instead?
I see an issue with incorrect formatting after clicking on **Preview** (for example **[x]** should be replaced with **- [x]**).

**Comment by LucianoPAlmeida** [comment]
Fixed by #931

**Comment by RomanPodymov** [comment]
Hello @LucianoPAlmeida 
Many thanks.
