### ISSUE TITLE
Add Enum Angle to UIViewExtension

### ISSUE THREAD

**Issue by ShivaHuang** [SwifterSwift/SwifterSwift#928]
- [x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?

I tried to use function `rotate(byAngle:, ofType:, animated:, duration:, completion:)` from `UIViewExtension` but the signature is not that swifty.

### What did you expect to happen?

We had defined an enum `AngleUnit` for angle unit, why not put an associated value for the angle?

We can define an enum like this:

```swift
enum Angle {
    /// SwifterSwift: degrees.
    case degree(CGFloat)

    /// SwifterSwift: radians.
    case radians(CGFloat)
}
```

So we can invoke the rotate function like this:

```swift
view.rotate(byAngle: .degree(90.0))
```

The same technique is also used by Apple, please reference [DispatchTimeInterval](https://developer.apple.com/documentation/dispatch/dispatchtimeinterval).

Further more, enum `Angle` can be improved by adding some computed properties like:

```swift
extension Angle {
    // Get the angle value in degree.
    var degreeValue: CGFloat { ... }

    // Get the angle value in radians.
    var radiansValue: CGFloat { ... }
```

and maybe conform to protocols like `equatable`, `comparable`, `AdditiveArithmetic`.

For the `rotate` functions, I think `rotate(by angle: Angle, ...)` is more Swift API naming convention upheld.
The same applies to `rotate(to angle: Angle, ...)`.

### What happened instead?
Currently we need to invoke this function this way:

```swift
view.rotate(byAngle: 90, ofType: .degree)
```

### SwifterSwift Environment

- SwifterSwift version: 5.2
- Xcode version: 12.3
- macOS version running Xcode: macOS Big Sur 11.1
- Swift version: 5.3.2
- Platform(s) running SwifterSwift: iOS

### Demo Project

The sample implementation has already listed above. I'll happy to open a PR for this change.

**Comment by LucianoPAlmeida** [comment]
Ah, I see the point, but unfortunately, we avoid creating new types inside the library... but a solution I can see to this problem is having an API that takes a `Measurement` like `func rotate(angle: Measurement<UnitAngle>)` and then we could extend `Measurement` class like 
```swift 
extension Measurement where UnitType == UnitAngle {
   static func degrees(_ value: Double) { Measurement(value: value, unit: .degrees) }
   static func radias(_ value: Double) { Measurement(value: value, unit: .radians) }
}
```
So calls would be `view.rotate(by: .degrees(90.0))`

I think that would be a way to solve this without addition of another type ...

**Comment by ShivaHuang** [comment]
That is awesome!

I even don't know there are classes like `Measurement` and `UnitAngle` in `Foundation`.
And in this way, the enum `AngleUnit` can be deprecated to avoid introducing new type inside the library.

I'll make a PR for this.

Thank you again for the excellent hint!

**Comment by guykogus** [comment]
We actually use it already in `UIImage.rotated(by:)`, so that can be used as a simple guide.

**Comment by ShivaHuang** [comment]
@guykogus Thanks for the information.

After reading the contributing guide, I found there is a rule said:

> * Do not use an existing SwifterSwift extension inside another SwifterSwift extension. All extensions should be able to be copied and pasted and work immediately without having to copy another extension.

So I think creating an extension for `Measurement<UnitAngle>` may also not a good choice for this. It will be helpful but breaks the rule.

And I believe the following form is good enough for us.

```swift
view.rotated(by: Measurement(value: 180, unit: .degrees))
```

So I'll close this issue and keep working on https://github.com/SwifterSwift/SwifterSwift/issues/935.
