### ISSUE TITLE
导入swifterswift之后，XIB、Storyboard，异常的耗费性能，xcode无响应等问题

### ISSUE THREAD

**Issue by Aaronwk** [SwifterSwift/SwifterSwift#930]
> 导入swifterswift之后，XIB、Storyboard，异常的耗费性能，xcode无响应，请问，如何关闭有关XIB、Storyboard的扩展（@IBInspectable）

**Comment by Jayxiang** [comment]
刚开始确实感觉会卡一些，但不至于无响应吧。可能是你的电脑太旧了。关闭需要自己删掉相关的 IBInspectable 即可，一共也没几个。

**Comment by Aaronwk** [comment]
"关闭需要自己删掉相关的 IBInspectable 即可" 这个是去源码自己删除掉就行了是不。也可能是确实电脑太旧了

**Comment by Jayxiang** [comment]
是的，放到本地 pod 引入更方便修改一些。

**Comment by Aaronwk** [comment]
好的。感谢解答

**Comment by LucianoPAlmeida** [comment]
Thanks @Jayxiang :)
