### ISSUE TITLE
Installing SwifterSwift (5.2.0) via Swift Package Manager breaks/changes ViewController orientation behaviour in iOS 14.4

### ISSUE THREAD

**Issue by MeteC** [SwifterSwift/SwifterSwift#944]
**Describe the bug**
I noticed an app I work on is not rotating view controllers from portrait to landscape mode in iOS 14.4 devices, while it is behaving just fine for iOS13. I then noticed that this behaviour happens when installing SwifterSwift via Swift Package Manager (without even using a line of code from it.)

**To Reproduce**
1. Create new App project in Xcode, use Interface = "Storyboard", Language = "Swift".
2. Add something - label or button - to the centre of the main storyboard view controller so that you can see it rotate.
3. Launch the app once, rotate the device, it will rotate to landscape and back.
4. Add SwifterSwift 5.2.0 using Swift Package Manager
5. Clean and re-launch the app. Rotate the device - it will no longer rotate the view controller.

**Expected behavior**
No difference between a project with and one without SwifterSwift installed. 
This expected behaviour is still seen on iOS 13.
It is also seen in the Simulator running iOS 14.4.

**Smartphones:**
 - Device: Tested with iPhone 8 with iOS 14.4, and iPhone 7 with iOS 13.7

**Additional notes**
- It may be that the issue is iPhone 8 vs iPhone 7 since running it on a simulator with iOS 14.4 works as expected. Personally I think it's more likely it's the iOS version and not the device, but I'm unable to test that at present myself.
- The problem also happens when installing Manually, by bringing in the entire `Source/SwifterSwift` folder into the project.
- The problem **doesn't** happen when installing over CocoaPods!

- [x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

**Comment by MeteC** [comment]
I've traced it down to the `descendants()` function in `SKNodeExtensions.swift`.
But from there it gets really weird...

- If I comment out the `descendants()` declaration, the rotations work fine.
- If I change the name of the `descendants()` function to `foobar()`, I get the original rotation problem.
- If I change the return type of `descendants()` to `SKNode` (and mess with the function to get it to compile), I still get the original rotation problem. 
- But if I make that return type `SKNode?`, and return nil without calling any of `SKNode()`, `[SKNode]()`, or `self.children` - then I get no rotation problem.

Seems in fact if I have ANY function at all in that extension that does anything with `[SKNode]`, or indeed references any methods from the SKNode library, then I get this problem.

Anyone else??

**Comment by LucianoPAlmeida** [comment]
Thank you for reporting @MeteC :) 
We will check as soon as possible, but at first this seems a really weird behavior ...

**Comment by MeteC** [comment]
Thanks! Agreed.. **very** weird. Next week I'll get a chance to try the same thing with an iPhone X running iOS 14.4. Will report back if I get the same issue on multiple phones!

**Comment by MeteC** [comment]
Bit late, but I can now confirm I get the same problem on an iPhone X running iOS 14.4. 

The problem seems to persist unless both SceneKit AND SpriteKit folders are essentially removed. All down to the last `import SceneKit` call.

Have you guys managed to reproduce this? (It's really easy to on my end...)

**Comment by LucianoPAlmeida** [comment]
Hi @MeteC, sorry we still didn't have a chance to look at this. I'll try check it soon, I just forgot about it, sorry 😅

**Comment by LucianoPAlmeida** [comment]
@MeteC I wasn't able to reproduce it on a project that I just created. Which version of Xcode do you tested?
I tested in simulators with Xcode Version 12.4 (12D4e). 
And are some questions:
* Does this happens if instead of installing SwifterSwift, you remove swifter swift package and define `descendants()` with the same signature inside the test project?
* If you put a break point on descendants() inside the SwifterSwift, does it hit when rotate? (This is very unlikely but since this problem seems very weird already ...)

**Comment by MeteC** [comment]
Hi @LucianoPAlmeida , as I mentioned in my bug report (but perhaps I could have been clearer in my wording), I saw the expected behaviour (i.e. no problems) for iOS 13 and for the simulator running iOS 14 - I only see this problem on actual physical devices running iOS 14+.

I'm happy to test that for you:

1. I do see the problem without SwifterSwift at all, here is some minimal code I can put into my project to cause the same effect: 
(note it's not just the `descendants` method that causes the problem, but seemingly any of the extensions to SceneKit that call on SceneKit methods. So I hacked the SCNGeometry code out of SwifterSwift to test.)

```
//  BreakViewRotation.swift

import Foundation
import SceneKit

// MARK: - Properties
public extension SCNGeometry {
    
    /// This causes bizarre view rotation blockage when included in the code
    var boundingMax: SCNVector3 {
        return boundingBox.max
    }
    
    /// But this causes no problems
    var boundingMax2: SCNVector3 {
        return SCNVector3()
    }
}
```
Note the second function I define here causes no issues at all, so if you comment out the first `boundingMax` function, view controller orientation behaviour resumes as expected.

2. Correct, the break point doesn't get hit at all.

So is my computer going insane? Is it just iOS devices running iOS14 within my post code that have issues? Or is there some sort of Swift / iOS bug at play? 😅

**Comment by LucianoPAlmeida** [comment]
Right @MeteC,
Thank you for doing the tests!

I think we can close this then, since we confirm is not a SwifterSwift specific bug. This looks like something you could report on [feedbackassistant.apple.com](feedbackassistant.apple.com) if you have a sample project and a description on how to reproduce :) 

If there is anything else we can support you feel free to ping us. Otherwise you can close this :)

**Comment by MeteC** [comment]
Yep good idea, I've gone ahead and reported it there. Will close here. 

If I'm not the only one that sees this issue, then it's still probably worth alerting SwifterSwift users of this issue somehow though! It's not SwifterSwift's fault but it is unexpected behaviour that's indirectly caused by including the full SwifterSwift library. (I wonder why CocoaPods inclusion doesn't cause the same issue...)

**Comment by LucianoPAlmeida** [comment]
> I wonder why CocoaPods inclusion doesn't cause the same issue

I hint I had was that SPM links libraries statically by default, not sure about how pods does... but if they do dynamic linking that may be a difference there. But I really don't know it that would make sense

**Comment by MeteC** [comment]
Hey just to necromance this thread a bit, Apple got back to me saying iOS15 should have fixed this issue, and I can confirm it. 👍 👍

**Comment by LucianoPAlmeida** [comment]
Thanks for the info @MeteC =]
