### ISSUE TITLE
Make Date.weekday doc string non-ambiguous to non-americans

### ISSUE THREAD

**Issue by TheStalwart** [SwifterSwift/SwifterSwift#946]
:rocket:
**Is your feature request related to a problem? Please describe.**
Doc string states:
Date().weekday -> 5 // fifth day in the current week.
Guess what, 5 is not friday. It's thursday. It makes _some_ sense after i dug deeper, but as a programmer, i assumed monday could be 0 or 1, therefore thursday should be 3 or 4. Monday is 2! Because sunday is 1!

**Describe the solution you'd like**
The simplest way to make it more descriptive for non-americans, it would help a lot if doc was worded as following:
Date().weekday -> 5 // thursday in the current week.

**Describe alternatives you've considered**
A more elaborate description of the value explaining it's a 30+ year old derelict of a convention that a week starts with one day you try your best to stay sober before monday.

**Additional context**
I'm european. Our weeks start with monday. It's hard, but we cope.

- [x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

**Comment by rickramirr** [comment]
I would like to contribute but i think that this could change to a new calendar extension method because this depends on value of firstweekday. If you agree I could be adding it.

**Comment by guykogus** [comment]
@TheStalwart sorry for the very late reply to this issue.

I'm not sure what you would like to change about the documentation. It's not saying that Friday is the 5th day, just that if the result is `5` then you are looking at the 5th day of the week, which according to the Gregorian calendar is Thursday (as you mentioned). This is in line with the `Calendar` documentation for `weekday` units:

> The weekday units are the numbers 1 through N (where for the Gregorian calendar N=7 and 1 is Sunday).

Would it help if we added this clarification to the code document? This might be clearer than your suggestion, as writing that 5 means Thursday is only true for cultures that use the Gregorian calendar.

**Comment by TheStalwart** [comment]
>1 is Sunday

Yes, this would make a world of difference for european developers.

> writing that 5 means Thursday is only true for cultures that use the Gregorian calendar

Not all users of Gregorian calendar though.

>The most common is the International Standard ISO 8601, where Monday is the first day of the week

Another example i can easily think of is in latvian language monday is "pirmdiena" which literally translates as "first day", followed by "otrdiena" aka "second day" and so on.

**Comment by guykogus** [comment]
I tested to see what happens if you change `firstDayOfWeek` in the `Calendar` and it doesn't change the `weekday` value. As far as `Calendar` is concerned the value is locale-agnostic, so even for Latvians the Gregorian calendar is considered to have Sunday as the first day of the week. It makes sense considering the religious backgrounds of the calendar, where Saturday is the last day after creation, so it's going to be the 7th day of the week no matter your local preferences.

The point is, I'll make a tiny PR to make the documentation clearer :)
