### ISSUE TITLE
I found an occasional crash，when access the "averageColor" property, although the amount is small, but I hope it can be resolved，

### ISSUE THREAD

**Issue by Lihaiquan** [SwifterSwift/SwifterSwift#951]
I found an occasional crash：

0
CoreImage
CI::Context::recursive_render(CI::TileTask*, CI::Node*, CGRect const&, CI::Node*, bool) + 2332
1
CoreImage
CI::Context::recursive_render(CI::TileTask*, CI::Node*, CGRect const&, CI::Node*, bool) + 2332
2
CoreImage
CI::Context::recursive_render(CI::TileTask*, CI::Node*, CGRect const&, CI::Node*, bool) + 792
3
CoreImage
CI::Context::recursive_render(CI::TileTask*, CI::Node*, CGRect const&, CI::Node*, bool) + 792
4
CoreImage
CI::Context::recursive_render(CI::TileTask*, CI::Node*, CGRect const&, CI::Node*, bool) + 792
5
CoreImage
CI::Context::recursive_render(CI::TileTask*, CI::Node*, CGRect const&, CI::Node*, bool) + 792
6
CoreImage
CI::Context::render(CI::ProgramNode*, CGRect const&) + 116
7
CoreImage
invocation function for block in CI::image_get_bitmap(CI::Context*, CI::Image*, CGRect, CGColorSpace*, CI::Bitmap*, CI::RenderDestination const*) + 592
8
CoreImage
CI::recursive_tile(CI::RenderTask*, CI::Context*, CI::RenderDestination const*, char const*, CI::Node*, CGRect const&, CI::PixelFormat, CI::swizzle_info const&, CI::TileTask* (CI::ProgramNode*, CGRect) block_pointer) + 2348
9
CoreImage
CI::tile_node_graph(CI::Context*, CI::RenderDestination const*, char const*, CI::Node*, CGRect const&, CI::PixelFormat, CI::swizzle_info const&, CI::TileTask* (CI::ProgramNode*, CGRect) block_pointer) + 384
10
CoreImage
CI::image_get_bitmap(CI::Context*, CI::Image*, CGRect, CGColorSpace*, CI::Bitmap*, CI::RenderDestination const*) + 1036
11
CoreImage
-[CIContext render:toBitmap:rowBytes:bounds:format:colorSpace:] + 904

I want to know how to solve it，thanks

**Comment by guykogus** [comment]
What makes you think it's from `averageColor`? It doesn't appear in your crash report.

**Comment by Lihaiquan** [comment]
I transplanted the code to my project, the call stack shows that when I access averageColor, it crashes.


EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000
0
CoreImage
CI::Context::recursive_render(CI::TileTask*, CI::Node*, CGRect const&, CI::Node*, bool) + 2536
1
CoreImage
CI::Context::recursive_render(CI::TileTask*, CI::Node*, CGRect const&, CI::Node*, bool) + 2536
2
CoreImage
CI::Context::recursive_render(CI::TileTask*, CI::Node*, CGRect const&, CI::Node*, bool) + 896
3
CoreImage
CI::Context::recursive_render(CI::TileTask*, CI::Node*, CGRect const&, CI::Node*, bool) + 896
4
CoreImage
CI::Context::recursive_render(CI::TileTask*, CI::Node*, CGRect const&, CI::Node*, bool) + 896
5
CoreImage
CI::Context::recursive_render(CI::TileTask*, CI::Node*, CGRect const&, CI::Node*, bool) + 896
6
CoreImage
CI::Context::recursive_render(CI::TileTask*, CI::Node*, CGRect const&, CI::Node*, bool) + 896
7
CoreImage
CI::Context::render(CI::ProgramNode*, CGRect const&) + 124
8
CoreImage
invocation function for block in CI::image_get_bitmap(CI::Context*, CI::Image*, CGRect, CGColorSpace*, CI::Bitmap*, CI::RenderDestination const*) + 608
9
CoreImage
CI::recursive_tile(CI::RenderTask*, CI::Context*, CI::RenderDestination const*, char const*, CI::Node*, CGRect const&, CI::PixelFormat, CI::swizzle_info const&, CI::TileTask* (CI::ProgramNode*, CGRect) block_pointer) + 2428
10
CoreImage
CI::tile_node_graph(CI::Context*, CI::RenderDestination const*, char const*, CI::Node*, CGRect const&, CI::PixelFormat, CI::swizzle_info const&, CI::TileTask* (CI::ProgramNode*, CGRect) block_pointer) + 396
11
CoreImage
CI::image_get_bitmap(CI::Context*, CI::Image*, CGRect, CGColorSpace*, CI::Bitmap*, CI::RenderDestination const*) + 1044
12
CoreImage
-[CIContext render:toBitmap:rowBytes:bounds:format:colorSpace:] + 920
13
putong
<compiler-generated> - 第 9276020 行
UIImage.averageColor.getter + 9276020
