### ISSUE TITLE
When using snapkit layout, if the view has no width and height, calling roundcorners will result in abnormal view display

### ISSUE THREAD

**Issue by gouyaming** [SwifterSwift/SwifterSwift#955]
When using snapkit layout, if the view has no width and height, calling roundcorners will result in abnormal view display

**Comment by tqtuan1cmc** [comment]
Any one face the same issues ?
I getting wrong bound too.

**Comment by gouyaming** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
