### ISSUE TITLE
call the method that's name is same with other library

### ISSUE THREAD

**Issue by tospery** [SwifterSwift/SwifterSwift#957]
How do you call a method SwifterSwift when it has the same method name as another third-party library,
example:
cornerRadius both in SwifterSwift(UIViewExtensions) and PopupDialog(PopupDialogContainerView)
Other, the current file must import them at the same time

**Comment by Jayxiang** [comment]
```
let pop = popup.view as! PopupDialogContainerView
pop.setValue(20, forKey: "cornerRadius")
```
