### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by pawurb** [SwifterSwift/SwifterSwift#96]
Currently test coverage is quite low, with a bunch of extension files not being tested at all. 
<img width="609" alt="coverage" src="https://cloud.githubusercontent.com/assets/1131944/21925378/86b81bde-d97d-11e6-854d-49dcaa46e8b0.png">

Though there is no way to display a fancy coverage status badge in the readme it would still be nice to increase it. I don't have time to look into it right now but I would leave issue hanging around for others to see. 

If someone feels like earning some cheap OS karma and get started on collaborating here it would be the simplest way to do it.

**Comment by omaralbeik** [comment]
Definitely, I'll work on adding more tests for all not UI extensions soon.

**Comment by omaralbeik** [comment]
Glad that code coverage reached 64% recently
https://codecov.io/gh/SwifterSwift/SwifterSwift

**Comment by omaralbeik** [comment]
Glad that code coverage reached 84% recently
https://codecov.io/gh/SwifterSwift/SwifterSwift
