### ISSUE TITLE
isEmoji 在九宫格键盘上认为都是Emoji

### ISSUE THREAD

**Issue by pengzhiqiang110** [SwifterSwift/SwifterSwift#969]
isEmoji 这个属性在iPhone 九宫格键盘上识别准备 对于Emoji

**Comment by Jayxiang** [comment]
能看下代码和键盘截图吗？

**Comment by pengzhiqiang110** [comment]
> 能看下代码和键盘截图吗？

![IMG_0563](https://user-images.githubusercontent.com/37108809/123757486-9d6f4d80-d8f0-11eb-9c6a-62bf3c9442f8.PNG)
![截屏2021-06-29 下午3 40 44](https://user-images.githubusercontent.com/37108809/123757698-d1e30980-d8f0-11eb-90e4-8129e9acc7a8.png)
![截屏2021-06-29 下午3 37 16](https://user-images.githubusercontent.com/37108809/123757728-da3b4480-d8f0-11eb-9b4d-69e8058f5597.png)
就像这样,我在九宫格键盘 只要一输入内容 它就默认成Emoji了,但是在26宫格键盘不会出现的

**Comment by Jayxiang** [comment]
确实有这个问题，我没有找到好的办法。

**Comment by Jayxiang** [comment]
确实有这个问题，我没找到好的办法。只好先忽略掉➋-➒。
[参考](https://kangzubin.com/nine-keyboard-emoji/)

**Comment by pengzhiqiang110** [comment]
> 确实有这个问题，我没找到好的办法。只好先忽略掉➋-➒。
> [参考](https://kangzubin.com/nine-keyboard-emoji/)

试过了 可以 希望作者可以更新下 isEmoji  这个判断

**Comment by Jayxiang** [comment]
isEmoji 判断没问题，这个特殊情况需要自己过滤处理。你可以把这个 9 个表情放到固定数组里，如何含有就返回 true。

题外话：你这种表单，我们一般是提交的时候提示用户有表情符号。

**Comment by LucianoPAlmeida** [comment]
Thank you for the help with this @Jayxiang =]

I didn't understand the conversation, but looking into the implementation of `isEmoji` https://github.com/SwifterSwift/SwifterSwift/blob/cd23151ddb33b11bd5cf86304517c2d6ce03634a/Sources/SwifterSwift/SwiftStdlib/CharacterExtensions.swift#L10 it looks like we can do better at least for Darwin platforms. Since swift 5.0 (I think) it was introduced the `isEmoji` as a `UnicodeScalarProperty` see here https://github.com/apple/swift/blob/340c85503e66a774395cd213a9f0a12dfd8fd880/stdlib/public/core/UnicodeScalarProperties.swift#L593, so maybe we can use this... (for the available platforms)

**Comment by pengzhiqiang110** [comment]
> isEmoji 判断没问题，这个特殊情况需要自己过滤处理。你可以把这个 9 个表情放到固定数组里，如何含有就返回 true。
> 
> 题外话：你这种表单，我们一般是提交的时候提示用户有表情符号。

isEmoji这个判断没考虑周全的,我们自己是可以处理,但是作者更新了之后,我们集成不是更方便,不用再二次处理

**Comment by Jayxiang** [comment]
@LucianoPAlmeida Yes, I also think we can use the swift 5.0 `UnicodeScalarProperty `, but there seems to be something to be aware of, see this article[Understanding Swift Strings, Emoji, Characters, and Scalars](https://medium.com/@krmblr/understanding-swift-strings-characters-and-scalars-a4b82f2d8fde)

**Comment by Jayxiang** [comment]
@pengzhiqiang110 你是说目前哪个表情没有考虑，举个例子。我理解的你的问题是，➋-➒被当作表情处理了，导致九宫格不能输入。

**Comment by pengzhiqiang110** [comment]
> @pengzhiqiang110 你是说目前哪个表情没有考虑，举个例子。我理解的你的问题是，➋-➒被当作表情处理了，导致九宫格不能输入。

是啊 就是这个问题啊 难道不应该优化下吗

**Comment by Jayxiang** [comment]
不知道该如何优化，➋-➒本来就是表情符号。

**Comment by pengzhiqiang110** [comment]
> 不知道该如何优化，➋-➒本来就是表情符号。

九宫格我输入汉字 被认为是表情,导致无法输入,这不是问题吗,非要在这扯皮,真服了

**Comment by LucianoPAlmeida** [comment]
> @LucianoPAlmeida Yes, I also think we can use the swift 5.0 `UnicodeScalarProperty `, but there seems to be something to be aware of, see this article[Understanding Swift Strings, Emoji, Characters, and Scalars](https://medium.com/@krmblr/understanding-swift-strings-characters-and-scalars-a4b82f2d8fde)

Thanks for the reference, I'll take a look =]

**Comment by Jayxiang** [comment]
@pengzhiqiang110  ...文章你没认真看吧。不管你用不用 isEmoji，用九宫格输入的高亮都会被处理为 ➋-➒。这和 isEmoji 判断输入的是不是表情没有关系。你可以先看下什么是键盘高亮，总而言之这是苹果键盘的问题，不是 isEmoji 判断的问题。

>我们猜测，苹果之所以这么做是因为，对于九宫格拼音键盘，一个键代表着 3 或 4 个字母，当你点击一个键时，它并不知道你要输入那个字母，所以用一个带圆圈的数字符号作为临时占位，等输入结束时才替换为相应的字母。
在九宫格拼音键盘中，”ABC” 键 ~ “WXYZ” 键所对应的临时占位符号分别为 ➋➌ … ➒ ，表情 “^-^” 键所对应的为符号 ☻ ，而这些符号在 stringContainsEmoji: 方法中刚好都被判为是 Emoji，所以当输入框禁止输入 Emoji 表情时，就会导致拼音也无法输入。

**Comment by pengzhiqiang110** [comment]
> @pengzhiqiang110 ...文章你没认真看吧。不管你用不用 isEmoji，用九宫格输入的高亮都会被处理为 ➋-➒。这和 isEmoji 判断输入的是不是表情没有关系。你可以先看下什么是键盘高亮，总而言之这是苹果键盘的问题，不是 isEmoji 判断的问题。
> 
> > 我们猜测，苹果之所以这么做是因为，对于九宫格拼音键盘，一个键代表着 3 或 4 个字母，当你点击一个键时，它并不知道你要输入那个字母，所以用一个带圆圈的数字符号作为临时占位，等输入结束时才替换为相应的字母。
> > 在九宫格拼音键盘中，”ABC” 键 ~ “WXYZ” 键所对应的临时占位符号分别为 ➋➌ … ➒ ，表情 “^-^” 键所对应的为符号 ☻ ，而这些符号在 stringContainsEmoji: 方法中刚好都被判为是 Emoji，所以当输入框禁止输入 Emoji 表情时，就会导致拼音也无法输入。
明白你的意思 但是不改的话。isEmoji 这个在phone 九宫格的输入的时候 还是没法用,可以改进下isEmoji这个方法 或者再增加个方法处理➋-➒这种情况 ➋-➒的时候isEmoji 返回false

**Comment by Jayxiang** [comment]
首先这是键盘的问题，和判断没有关系，这个你应该理解了。
还是那句话：isEmoji 判断没问题，这个特殊情况需要自己判断处理。一共就 9 个表情
假如按照你说的➋-➒的时候 isEmoji 返回 false，那 isEmoji 判断不就有问题了吗？
你可以这样处理

```
    public func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
        print(string)
        let filterEmoji = ["➋", "➌", "➍", "➎", "➏", "➐", "➑", "➒", "☻"]
        if !filterEmoji.contains(string), string.containEmoji {
            return false
        }
        return true
    }
```

**Comment by pengzhiqiang110** [comment]
> let filterEmoji = ["➋", "➌", "➍", "➎", "➏", "➐", "➑", "➒", "☻"]

好的 这样确实比较合理些

**Comment by Jayxiang** [comment]
如果没有其他问题了，你可以关闭这个

**Comment by pengzhiqiang110** [comment]
> 首先这是键盘的问题，和判断没有关系，这个你应该理解了。
> 还是那句话：isEmoji 判断没问题，这个特殊情况需要自己判断处理。一共就 9 个表情
> 假如按照你说的➋-➒的时候 isEmoji 返回 false，那 isEmoji 判断不就有问题了吗？
> 你可以这样处理
> 
> ```
>     public func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
>         print(string)
>         let filterEmoji = ["➋", "➌", "➍", "➎", "➏", "➐", "➑", "➒", "☻"]
>         if !filterEmoji.contains(string), string.containEmoji {
>             return false
>         }
>         return true
>     }
> ```
