### ISSUE TITLE
XCode 13 

### ISSUE THREAD

**Issue by tzmoyal** [SwifterSwift/SwifterSwift#976]
Hey,

I'm trying to compile the latest 5.2.0 version on XCode 13 beta 3.

I'm getting an error on compilation:
"'shared' is unavailable in application extensions for iOS: use view controller based solutions where appropriate instead."

UIAlertControoler extension for example.

Thanks,
Tzahi

**Comment by LucianoPAlmeida** [comment]
@tzmoyal Thanks for the report :)
But seems not actually be a SwifterSwift bug and is a dupe I think... check the #915 for more details

**Comment by LucianoPAlmeida** [comment]
We are planning a release eventually, see #967
