### ISSUE TITLE
func joined(separator:) for NSAttributedStrings

### ISSUE THREAD

**Issue by RomanPodymov** [SwifterSwift/SwifterSwift#984]
🚀
**Is your feature request related to a problem? Please describe.**
In my projects I use a lot of `NSAttributedString`s, but did not find a convenient way how to create an `NSAttributedString` instance with different attributes for each range.

**Describe the solution you'd like**
I would like to add these functions:
```
public extension Array where Element: NSAttributedString {
    // https://stackoverflow.com/questions/32830519/is-there-joinwithseparator-for-attributed-strings
    func joined(separator: NSAttributedString) -> NSAttributedString {
        var isFirst = true
        return reduce(into: NSMutableAttributedString()) { result, element in
            if isFirst {
                isFirst = false
            } else {
                result.append(separator)
            }
            result.append(element)
        }
    }

    func joined(separator: String) -> NSAttributedString {
        joined(separator: NSAttributedString(string: separator))
    }
}
```

- [x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

**Comment by Jeffry1742** [comment]
Fixing

**Comment by Jeffry1742** [comment]
Hacking iPhone
