### ISSUE TITLE
On  iOS15, collectionView reloadData have finished , but sizeForItemAt does not work.

### ISSUE THREAD

**Issue by xiaoyao20084321** [SwifterSwift/SwifterSwift#998]
**Describe the bug**
On  iOS15, collectionView reloadData have finished , but sizeForItemAt does not work.

**Expected behavior**
On  iOS15，collectionView reloadData have finished ， and sizeForItemAt have finished.

**Comment by RomanPodymov** [comment]
Hello @xiaoyao20084321 
Are you sure this issue is related to SwifterSwift?

**Comment by xiaoyao20084321** [comment]
sorry, Problem with my own code
